### ISSUE TITLE
Add Get-AdobeAcrobatStandard2020

### ISSUE THREAD

**Issue by skest3qc** [aaronparker/Evergreen#114]
Hi Aaron,

it would be nice if you could add a cmdlet to get Adobe Acrobat Standard 2020 Updates, which can be downloaded here:

"ftp://ftp.adobe.com/pub/adobe/acrobat/win/Acrobat2020/"

Thanks
Selimir

**Comment by aaronparker** [comment]
Wouldn't the update returned by `Get-AdobeAcrobatProDC` also apply to Acrobat DC Standard?

**Comment by skest3qc** [comment]
No because they are from a different branch (Track)
https://supportdownloads.adobe.com/product.jsp?product=1&platform=Windows
![image](https://user-images.githubusercontent.com/8022790/107476229-b65fa800-6b75-11eb-9b35-e1d29013f15c.png)

**Comment by aaronparker** [comment]
Does this match your current version (using the Acrobat in-built updater) - [https://armmf.adobe.com/arm-manifests/mac/Acrobat2020/reader/current_version.txt](https://armmf.adobe.com/arm-manifests/mac/Acrobat2020/reader/current_version.txt)

**Comment by aaronparker** [comment]
So, I can find this update - does it apply to an Acrobat 2020 install? [https://ardownload2.adobe.com/pub/adobe/acrobat/win/Acrobat2020/2000130020/Acrobat2020Upd2000130020.msp](https://ardownload2.adobe.com/pub/adobe/acrobat/win/Acrobat2020/2000130020/Acrobat2020Upd2000130020.msp). It looks to be higher that what Adobe lists publically

**Comment by aaronparker** [comment]
`2020.001.30020` does line up with the most recent security update: [https://helpx.adobe.com/security/products/acrobat/apsb21-09.html](https://helpx.adobe.com/security/products/acrobat/apsb21-09.html).

**Comment by skest3qc** [comment]
> So, I can find this update - does it apply OK to an Acrobat 2020 install? https://ardownload2.adobe.com/pub/adobe/acrobat/win/Acrobat2020/2000130020/Acrobat2020Upd2000130020.msp.
> 
> `2020.001.30020` does line up with the most recent security update: https://helpx.adobe.com/security/products/acrobat/apsb21-09.html.

Yes :)

**Comment by aaronparker** [comment]
`Get-AdobeAcrobat` added to the `development` branch. This returns updates for Standard/Pro DC/2020:

```powershell
Version  : 20.001.30020
Type     : Updater
Language : Neutral
Track    : 2020
URI      : https://ardownload2.adobe.com/pub/adobe/acrobat/win/Acrobat2020/2000130020/Acrobat2020Upd2000130020.msp

Version  : 21.001.20135
Type     : Updater
Language : Neutral
Track    : DC
URI      : https://ardownload2.adobe.com/pub/adobe/acrobat/win/AcrobatDC/2100120135/AcrobatDCUpd2100120135.msp
```

**Comment by skest3qc** [comment]
Thanks Aaron :)
