### ISSUE TITLE
Foxit Reader Enterprise instead of Foxit Reader Download

### ISSUE THREAD

**Issue by Deyda** [aaronparker/Evergreen#116]
I'm having trouble with Foxit Reader right now. Could you also still make Foxit Reader Enterprise available through Evergreen.
The download link is for the latest version:
https://cdn01.foxitsoftware.com/product/reader/desktop/win/10.1.1/FoxitReader1011_L10N_Setup.msi

**Comment by aaronparker** [comment]
Released in `2104.355`
