### ISSUE TITLE
Get-MozillaFirefox issues with language Parameter (2102.291)

### ISSUE THREAD

**Issue by j81blog** [aaronparker/Evergreen#119]
**Describe the bug**
When specifying the parameter -Language for "Get-MozillaFirefox" on a commandline, you'll get the desired output.
But when running in a script within a deployment tool, this generates an error.

**To Reproduce**
Run "Get-MozillaFirefox -Language nl" within a deployment tool like Ivanti Automation.

**Expected behavior**
Desired result with data for specified Language

**Screenshots**
```PowerShell
Get-MozillaFirefox : A parameter cannot be found that matches parameter name 'Language'.
At line:2 char:20
+ Get-MozillaFirefox -Language nl
+                    ~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-MozillaFirefox], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Get-MozillaFirefox
```

**Desktop (please complete the following information):**
 - OS: Windows Server 2019
 - Module Version 2102.291

**Additional context**

Looks like the Parameter is not defined for the "Get-MozillaFirefox" module

```PowerShell
Function Get-MozillaFirefox {
    <#
        .SYNOPSIS
            Returns downloads for the latest Mozilla Firefox releases.

        .NOTES
            Site: https://stealthpuppy.com
            Author: Aaron Parker
            Twitter: @stealthpuppy

        .LINK
            https://github.com/aaronparker/Evergreen/

        .EXAMPLE
            Get-MozillaFirefox

            Description:
            Returns the version and download URIs for Firefox for Windows
    #>
    [OutputType([System.Management.Automation.PSObject])]
    [CmdletBinding()]
    Param()

    # Get application resource strings from its manifest

```

**Comment by aaronparker** [comment]
See breaking changes: [https://stealthpuppy.com/Evergreen/changelog.html#2101281](https://stealthpuppy.com/Evergreen/changelog.html#2101281)

**Comment by j81blog** [comment]
Sorry, missed that one. Validated and indeed this results in the required output.
