### ISSUE TITLE
ControlUp now provides a JSON

### ISSUE THREAD

**Issue by haavarstein** [aaronparker/Evergreen#120]
https://www.controlup.com/latest-agent-console/

{ "GAed_Version": "v8.2.0.758", "Agent" :{ "32bit-.net35": "https://downloads.controlup.com/agent/8.2.0.758/ControlUpAgent-net35-x86-8.2.0.758-signed.msi", "64bit-.net35": "https://downloads.controlup.com/agent/8.2.0.758/ControlUpAgent-net35-x64-8.2.0.758-signed.msi", "32bit-.net45": "https://downloads.controlup.com/agent/8.2.0.758/ControlUpAgent-net45-x86-8.2.0.758-signed.msi", "64bit-.net45": "https://downloads.controlup.com/agent/8.2.0.758/ControlUpAgent-net45-x64-8.2.0.758-signed.msi" }, "Console": "https://downloads.controlup.com/console/8.2.0.758/ControlUp.zip" }

**Comment by aaronparker** [comment]
Sweet

**Comment by aaronparker** [comment]
@haavarstein there's a 404 on these JSON URLs now. Is there another location?

**Comment by aaronparker** [comment]
I've disabled these functions in the latest release until we can find the JSON again #129
