### ISSUE TITLE
Get-AdobeAcrobatReaderDC

### ISSUE THREAD

**Issue by bmitchell76** [aaronparker/Evergreen#121]
I'm not yet sure if this is a bug or a change on the Adobe site. Still, Get-AdobeAcrobatReaderDC appears to return the latest Adobe Acrobat Reader DC; however, after downloading and installing the file, it appears to be Adobe Acrobat DC, not Reader.

**Comment by Deyda** [comment]
Yes at least the installer for English is misplaced at Adobe. The German one is still Reader.

**Comment by bmitchell76** [comment]
looks like English (UK) too, but looks like the expected file is still on the anticipated path.

http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/2100120135/AcroRdrDC2100120135_en_US.exe

PS C:\> Get-AdobeAcrobatReaderDC

Version      Type      Language     URI
-------      ----      --------     ---
21.001.20135 Installer English      http://ardownload.adobe.com/pub/adobe/**acrobat**/win/AcrobatDC/2100120135/AcroRdrDCx642100120135_en_US.exe
21.001.20135 Installer English (UK) http://ardownload.adobe.com/pub/adobe/**acrobat**/win/AcrobatDC/2100120135/AcroRdrDCx642100120135_en_US.exe
19.008.20071 Installer Danish       http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/1900820071/AcroRdrDC1900820071_da_DK.exe
19.008.20071 Installer Dutch        http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/1900820071/AcroRdrDC1900820071_nl_NL.exe
21.001.20140 Installer French       http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/2100120140/AcroRdrDC2100120140_fr_FR.exe
19.008.20071 Installer Finnish      http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/1900820071/AcroRdrDC1900820071_fi_FI.exe
21.001.20140 Installer German       http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/2100120140/AcroRdrDC2100120140_de_DE.exe
19.008.20071 Installer Italian      http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/1900820071/AcroRdrDC1900820071_it_IT.exe                                21.001.20140 Installer Japanese     http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/2100120140/AcroRdrDC2100120140_ja_JP.exe                                19.008.20071 Installer Korean       http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/1900820071/AcroRdrDC1900820071_ko_KR.exe                                19.008.20071 Installer Norwegian    http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/1900820071/AcroRdrDC1900820071_nb_NO.exe                                21.001.20140 Installer Spanish      http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/2100120140/AcroRdrDC2100120140_es_ES.exe
21.001.20142 Updater   Neutral      http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/2100120142/AcroRdrDCUpd2100120142.msp
21.001.20142 Updater   Multi        http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/2100120142/AcroRdrDCUpd2100120142_MUI.msp

**Comment by aaronparker** [comment]
The installer and shortcut after install shows as `Adobe Acrobat DC`, however, once installed it is Reader. There's definitely a change in the installer as I'm seeing the 64-bit version installed now instead of the 32-bit version of Reader.

**Comment by aaronparker** [comment]
The shortcut points to `C:\Program Files\Adobe\Acrobat DC\Acrobat\Acrobat.exe`; however, once launched it is Reader:

![image](https://user-images.githubusercontent.com/8227455/109736010-d1bf4f80-7c17-11eb-88cf-dfb56776bc28.png)

**Comment by aaronparker** [comment]
@bmitchell76 @Deyda could you please test the `development` branch 2302a2c2acc0c052a8c4140e76e065a0e8e7d131 for `Get-AdobeAcrobatReaderDC`? Note that this makes some changes to the output by returning x86 (the old installer) and x64 installers (the new installer with the behaviour above). This also removes the `.MSP` download at this time as I don't have a good way yet to determine whether the updater is a required or optional update (note the version differences in the list below).

```powershell
Version      : 21.001.20135
Language     : English
Architecture : x64
Name         : Reader DC 2021.001.20135 English Windows(64Bit)
URI          : http://ardownload.adobe.com/pub/adobe/acrobat/win/AcrobatDC/2100120135/AcroRdrDCx642100120135_en_US.exe

Version      : 21.001.20140
Language     : English
Architecture : x86
Name         : Reader DC 2021.001.20140 English for Windows
URI          : http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/2100120140/AcroRdrDC2100120140_en_US.exe

Version      : 21.001.20135
Language     : English (UK)
Architecture : x64
Name         : Reader DC 2021.001.20135 English UK Windows(64Bit)
URI          : http://ardownload.adobe.com/pub/adobe/acrobat/win/AcrobatDC/2100120135/AcroRdrDCx642100120135_en_US.exe

Version      : 21.001.20140
Language     : English (UK)
Architecture : x86
Name         : Reader DC 2021.001.20140 English UK for Windows
URI          : http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/2100120140/AcroRdrDC2100120140_en_US.exe

Version      : 19.008.20071
Language     : Danish
Architecture : x86
Name         : Reader DC 2019.008.20071 Danish for Windows
URI          : http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/1900820071/AcroRdrDC1900820071_da_DK.exe

Version      : 19.008.20071
Language     : Dutch
Architecture : x86
Name         : Reader DC 2019.008.20071 Dutch for Windows
URI          : http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/1900820071/AcroRdrDC1900820071_nl_NL.exe

Version      : 21.001.20140
Language     : French
Architecture : x86
Name         : Reader DC 2021.001.20140 French for Windows
URI          : http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/2100120140/AcroRdrDC2100120140_fr_FR.exe

Version      : 19.008.20071
Language     : Finnish
Architecture : x86
Name         : Reader DC 2019.008.20071 Finnish for Windows
URI          : http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/1900820071/AcroRdrDC1900820071_fi_FI.exe

Version      : 21.001.20140
Language     : German
Architecture : x86
Name         : Reader DC 2021.001.20140 German for Windows
URI          : http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/2100120140/AcroRdrDC2100120140_de_DE.exe

Version      : 19.008.20071
Language     : Italian
Architecture : x86
Name         : Reader DC 2019.008.20071 Italian for Windows
URI          : http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/1900820071/AcroRdrDC1900820071_it_IT.exe

Version      : 21.001.20140
Language     : Japanese
Architecture : x86
Name         : Reader DC 2021.001.20140 Japanese for Windows
URI          : http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/2100120140/AcroRdrDC2100120140_ja_JP.exe

Version      : 19.008.20071
Language     : Korean
Architecture : x86
Name         : Reader DC 2019.008.20071 Korean for Windows
URI          : http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/1900820071/AcroRdrDC1900820071_ko_KR.exe

Version      : 19.008.20071
Language     : Norwegian
Architecture : x86
Name         : Reader DC 2019.008.20071 Norwegian for Windows
URI          : http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/1900820071/AcroRdrDC1900820071_nb_NO.exe

Version      : 21.001.20140
Language     : Spanish
Architecture : x86
Name         : Reader DC 2021.001.20140 Spanish for Windows
URI          : http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/2100120140/AcroRdrDC2100120140_es_ES.exe
```

**Comment by bmitchell76** [comment]
Looks good

PS C:\> Get-AdobeAcrobatReaderDC | Where-Object {($_.language -eq "english") -and ($_.architecture -eq "x86")}


Version      : 21.001.20140
Language     : English
Architecture : x86
Name         : Reader DC 2021.001.20140 English for Windows
URI          : http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/2100120140/AcroRdrDC2100120140_en_US.exe

**Comment by Deyda** [comment]
Yeah the dev module looks good. I can confirm Aaron's statement as well. Installation and icons (even in Program & Features) looks like Adobe DC, with the prod module. But when I launch it, it is Adobe Reader DC. Strange :-/

**Comment by aaronparker** [comment]
I wonder how this bodes for VDI environments with Acrobat and Reader side-by-side

**Comment by Deyda** [comment]
It does not work. Tried it earlier on my test machine with my script.

**Comment by Mohrpheus78** [comment]
What about the Acrobat Reader DC Multi Language download? I can't get it anymore with Get-AdobeAcrobatReaderDC

**Comment by aaronparker** [comment]
Adobe Reader updates are included in `Get-AdobeAcrobat`. This has been split from `Get-AdobeAcrobatReaderDC` to keep similar retrieval methods in the same functions. Getting the installers is a different approach from getting the updaters.
