### ISSUE TITLE
7-zip download redirect

### ISSUE THREAD

**Issue by keteague** [aaronparker/evergreen#124]
**Describe the bug**
7zip.json contains:
  "Uri": "https://nchc.dl.sourceforge.net/project/sevenzip"
which is country-specific.
The web site has a redirect:
  https://sourceforge.net/projects/sevenzip/files/7-Zip/19.00/7z1900-x64.msi/download
which does a round-robin approach to download the file from a random sourceforge mirror.  Occasionally, one of those mirrors could be down or, in my case, inaccessible from my company network due to GeoIP filtering.  The above mentioned URI is in Taiwan and is an absolute no go from my network admins.

**To Reproduce**
1. Go to https://www.redirect-checker.org/index.php
2. Input https://sourceforge.net/projects/sevenzip/files/7-Zip/19.00/7z1900-x64.msi/download
3. Click on Analyse
4. Look at the redirect results
5. Repeat steps 3 and 4 to see that the redirect changes.

**Expected behavior**
Does "Uri" need to be statically defined in the .json file?  
Can "Uri" be defined based on the redirect?
Maybe remove nchc and make it:
  "Uri": "https://dl.sourceforge.net/project/sevenzip"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro, 20H2

**Additional context**

**Comment by aaronparker** [comment]
The problem with using `https://dl.sourceforge.net/project/sevenzip` is that it doesn't work with `Invoke-WebRequest` when downloading the installer. If you re-run `Get-7Zip` does it return the same URI value each time?

**Comment by DanGough** [comment]
A related issue - Invoke-WebRequest works with the 64-bit URL returned by the module:

https://nchc.dl.sourceforge.net/project/sevenzip/7-Zip/19.00/7z1900-x64.msi

But it just returns a HTML file for the 32-bit version:

https://nchc.dl.sourceforge.net/project/sevenzip/7-Zip/19.00/7z1900.msi

**Comment by keteague** [comment]
Not sure if this helps you:

https://www.reddit.com/r/PowerShell/comments/9gwbed/scrape_7zip_website_for_the_latest_version/

**Comment by DanGough** [comment]
CMPackager and Chocolatey both use web scraping. I know this project is trying to steer away from that, but if it gives better working URLs, use what works I guess!

Chocolatey:
[https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/automatic/7zip/update.ps1](https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/automatic/7zip/update.ps1)

CMPackager code:
[https://github.com/asjimene/CMPackager/blob/master/Disabled/7-Zip.xml](https://github.com/asjimene/CMPackager/blob/master/Disabled/7-Zip.xml)

My workflow has the option to use Evergreen, Winget, Chocolatey or custom scripts for sources, so I'm covered!

**Comment by aaronparker** [comment]
Yeah, not interested in using web scraping if I can help it. Downloads returned from SourceForge all use a common function, so this may affect others as well - KeePass, WinMerge, WinSCP etc.

**Comment by aaronparker** [comment]
How about we just remove the x86 version of 7-zip?

**Comment by keteague** [comment]
I don't see how removing the x86 version solves anything.  If Dan is querying for the 32-bit version, it would seem that he needs it.  I understand not many people use x86 anymore but it's not totally gone..

While I like what Chocolatey does, I'd prefer to get packages straight from the source which is why I'm choosing to use Evergreen.

How about a combination of best_release.json from sourceforge to get version and filename information combined with fetching the binaries from 7-zip.org?  The direct download links from 7-zip.org appears to be consistent.

https://www.7-zip.org/a/7z1900.exe
https://www.7-zip.org/a/7z1900-x64.exe
https://www.7-zip.org/a/7z1900.msi
https://www.7-zip.org/a/7z1900-x64.msi

If this isn't an option, I can attempt contact with the 7-zip maintainer to see if he's willing to maintain a .json file of the latest versions.

**Comment by keteague** [comment]
I've opened a case with Igor.

https://sourceforge.net/p/sevenzip/support-requests/383/

**Comment by DanGough** [comment]
I don't _need_ the 32-bit version, I'm just setting up an automated packaging pipeline and have just added it in for completeness. I expect I'll never actually make use of it though.

The URL works if I put it in my browser and let the redirect happen, so I'd rather it was left in than removed entirely.

**Comment by aaronparker** [comment]
I'll look at removing the 32-bit version

**Comment by DanGough** [comment]
Invoke-WebRequest works fine with the 32-bit URL if you set the user agent to Googlebot (it downloads HTML if you leave it empty or set it to Edge), so this could be potentially left in and just handled in the download function:

```powershell
Invoke-WebRequest -Uri 'https://nchc.dl.sourceforge.net/project/sevenzip/7-Zip/19.00/7z1900.msi' -OutFile 'C:\Temp\7z1900.msi' -UserAgent 'Googlebot/2.1 (+http://www.google.com/bot.html)'
```

**Comment by aaronparker** [comment]
The function is returning the latest 7-Zip `21.04` update and this issue does not occur with the latest release.
