### ISSUE TITLE
Get-Zoom returns string 'Latest' as version number for Citrix/VMware/VDI variants

### ISSUE THREAD

**Issue by DanGough** [aaronparker/Evergreen#125]
Instead of a version number, **Get-Zoom** returns '_Latest_' for the editions where _Platform = Citrix, VDI or VMware_.

This means we cannot determine if there is a new version without downloading the MSI and querying the ProductVersion property.

**Comment by aaronparker** [comment]
Zoom doesn't provide a method to find the latest version value of those downloads.

**Comment by DanGough** [comment]
Thanks, I'll report back if I find a better way than scripted download and inspection!

**Comment by aaronparker** [comment]
Added a note to the known issues: [https://stealthpuppy.com/Evergreen/knownissues.html](https://stealthpuppy.com/Evergreen/knownissues.html)
