### ISSUE TITLE
Get-AdoptOpenJDK only returns .zip files from v8

### ISSUE THREAD

**Issue by DanGough** [aaronparker/evergreen#126]
Currently this command is only returning zip files, from what may not be the best repo. The readme for 'openjdk8-upstream-binaries' states:
> Not to be confused with **openjdk8-binaries** (which are AdoptOpenJDK's **official** binary release). These are pure unaltered builds from the OpenJDK mercurial jdk8u code stream.

This repo does not contain the MSI installers. I would like this command to return .msi links from:

- AdoptOpenJDK/openjdk8-binaries
- AdoptOpenJDK/openjdk11-binaries
- AdoptOpenJDK/openjdk15-binaries

Or split the above into separate apps, e.g. Get-AdoptOpenJDK8, Get-AdoptOpenJDK11. 8 and 11 are LTS versions so some may wish to deploy all of the above.

To add to the confusion there are both JDK and JRE versions and multiple variants of each:

- Hotspot x86
- Hotspot x64
- OpenJ9 x86 Normal (openjdk8 only, seems to be depracated in 11 and 15)
- OpenJ9 x64 Normal
- OpenJ9 x64 Large Heap

It would be great to have them all listed so that users could filter to their desired one.

**Comment by aaronparker** [comment]
These will have to be split into seperate apps. Because they're all on GitHub, this should be straight forward.

**Comment by aaronparker** [comment]
AdoptOpenJDK official builds for 8, 11, and 16 add in c8524ed81a2dbe6c5340f8f2896f4884ee642eba

**Comment by DanGough** [comment]
The latest release returns Hotspot editions for v8 and v16, but OpenJ9 editions for v11. Would it be possible to add both variants to all versions or just stick to Hotspot?

I have no idea how many would prefer to install one over the other!

**Comment by aaronparker** [comment]
At this stage, I've just added specific repos from https://github.com/AdoptOpenJDK. [/Evergreen/Private/Get-GitHubRepoRelease](https://github.com/aaronparker/Evergreen/blob/main/Evergreen/Private/Get-GitHubRepoRelease.ps1) does a standard lookup of the release passed to it from the manifest with filtering for exe, msi etc., so it's a standard approach across all apps that leverage GitHub repos.

Can you take a look at the function and the manifest for each to see what might need to change?

**Comment by DanGough** [comment]
Sure, I've not dug into Evergreen's code fully yet but this is a good opportunity for me to attempt my first fix...

**Comment by DanGough** [comment]
This may be difficult to resolve without AdoptOpenJDK sorting out the tags in their repos.

Evergreen is using the tag 'latest' for all, e.g:

https://api.github.com/repos/AdoptOpenJDK/openjdk11-binaries/releases/latest
https://api.github.com/repos/AdoptOpenJDK/openjdk16-binaries/releases/latest

Browsing these, they only have the Hotspot releases listed for v16 and the OpenJ9 ones for v11:

https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/latest
https://github.com/AdoptOpenJDK/openjdk16-binaries/releases/latest

The homepage https://adoptopenjdk.net offers all variants up for grabs, so I assume they're all equally valid/desirable.

The other variants are there, they're just not tagged 'latest'. E.g:

https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk-11.0.10%2B9
https://github.com/AdoptOpenJDK/openjdk16-binaries/releases/tag/jdk-16%2B36_openj9-0.25.0

I'm not sure how you would know which specific releases to query in the code!

**Comment by DanGough** [comment]
I figured out the API calls that https://adoptopenjdk.net/releases.html uses by hitting F12 and checking the network tab:

https://api.adoptopenjdk.net/v3/assets/latest/8/hotspot?release=latest&jvm_impl=hotspot&vendor=adoptopenjdk&
https://api.adoptopenjdk.net/v3/assets/latest/8/openj9?release=latest&jvm_impl=openj9&vendor=adoptopenjdk&

https://api.adoptopenjdk.net/v3/assets/latest/11/hotspot?release=latest&jvm_impl=hotspot&vendor=adoptopenjdk&
https://api.adoptopenjdk.net/v3/assets/latest/11/openj9?release=latest&jvm_impl=openj9&vendor=adoptopenjdk&

https://api.adoptopenjdk.net/v3/assets/latest/16/hotspot?release=latest&jvm_impl=hotspot&vendor=adoptopenjdk&
https://api.adoptopenjdk.net/v3/assets/latest/16/openj9?release=latest&jvm_impl=openj9&vendor=adoptopenjdk&

It would be best to rebuild the function to use those instead of Github I reckon. I still need to level up in REST APIs, but I'll look into it!

**Comment by DanGough** [comment]
I couldn't work out how to do this using Evergreen but here is my implementation:

https://github.com/DanGough/Nevergreen/blob/dev/Nevergreen/Apps/Get-AdoptOpenJDK.ps1
