### ISSUE TITLE
Get-Microsoft.NET - URLs for LTS versions do not work

### ISSUE THREAD

**Issue by DanGough** [aaronparker/Evergreen#131]
Run:

`iwr (Get-Microsoft.NET | Where {$_.Channel -eq 'LTS' -and $_.Architecture -eq 'x64'} | Select -ExpandProperty URI)`

Response:

> BlobNotFoundThe specified blob does not exist.

URLs for the Current channel work fine.

**Comment by aaronparker** [comment]
Must have been temporary, as it returns the URL now.

**Comment by aaronparker** [comment]
It's an issue again. I'll check

**Comment by aaronparker** [comment]
Pushed a fix in de8af16c9df6a6a108ae9f6940e4ab0168e95ee9
