### ISSUE TITLE
Speed up results for MozillaFirefox

### ISSUE THREAD

**Issue by DanGough** [aaronparker/evergreen#136]
**Describe the bug**
Sometimes MozillaFirefox returns results quickly, other times it gets stuck for several minutes. Windows Powershell seems to be quicker than Powershell 7, but this could just be a fluke due to a limited number of tests. For example:

Windows Powershell: 2 minutes, 7 minutes, 8 minutes
Powershell 7: 8 minutes, 13 minutes, 14 minutes

I realise this one fires off a lot of queries for different languages/platforms/channels, but the runtime still seems excessive so it would be worth exploring to see if there is a way to speed things up! For instance using the new `ForEach-Object -Parallel` option?

**To Reproduce**
`Measure-Command {Get-EvergreenApp MozillaFirefox -Verbose}`

**Expected behavior**
I would hope to expect results back in under a minute.

**Desktop**
 - OS: Windows 10 x64 20H2
 - Module Version: 2101.256

**Comment by aaronparker** [comment]
I could reduce the number of languages in the manifest; however, I'd need to work. out a method to allow additional languages as required.

Using `ForEach-Object -Parallel` could work but would be PowerShell 7 only.

**Comment by aaronparker** [comment]
Here's what this returns by default, which amounts to 136 items passed back to the pipeline:

* Channel: `LATEST_FIREFOX_VERSION`, `FIREFOX_ESR`
* File types: `Exe`, `Msi`
* Architecture: `x86`, `x64`
* Languages: `en-US`, `en-GB`, `en-CA`, `es-ES`, `sv-SE`, `pt-BR`, `pt-PT`, `de`, `fr`, `it`, `ja`, `nl`, `zh-CN`, `zh-TW`, `ar`, `hi-IN`, `ru`

Removing just one item such as `x86` or one language would 1/2 the number of items and the time for the function to run.

**Comment by Deyda** [comment]
I would remove a file type (remove exe). I always use MSI when possible because it gives you more settings for the unattended installer.

**Comment by DanGough** [comment]
That's quite a few! I realise that filtering at source would require some hefty changes, and I wouldn't just remove results outright as someone somewhere may need them. If the parallel thing sorts it, then having the code only enable that method on PS7 would be workable in my view, and a good reason to to use the new platform. I will look into implementing this in my own workflow as currently I'm just going through 100+ apps in series! There are of course other methods of parallelisation such as jobs but then we're getting more complex.

**Comment by aaronparker** [comment]
[https://twitter.com/stealthpuppy/status/1380100038144126984?s=20](https://twitter.com/stealthpuppy/status/1380100038144126984?s=20)

**Comment by aaronparker** [comment]
Each download has a predictable URL: [https://download-installer.cdn.mozilla.net/pub/firefox/releases/87.0/win64/en-US/Firefox%20Setup%2087.0.exe](https://download-installer.cdn.mozilla.net/pub/firefox/releases/87.0/win64/en-US/Firefox%20Setup%2087.0.exe); however, using a simple string replace to generate the URLs doesn't provide any resiliency if those URLs happen to change.

**Comment by DanGough** [comment]
I guess I would rather have it return full results slowly than cripple it somehow. It's worth keeping the EXEs as some people might prefer them since their MSI packages are awful (just a wrapper for the exe, and it doesn't even upgrade over previous versions).

**Comment by aaronparker** [comment]
I'll try the `ForEach-Object -Parallel` approach when I can

**Comment by aaronparker** [comment]
I've implemented a solution where the required language/s can be passed to `MozillaFirefox` from `Get-EvergreenApp -AppParams`. This significantly reduces processing time, but returns `en-US` only by default.

`MozillaFirefox` now also returns the `MSIX` installers, so this approach to languages works across Windows PowerShell and PowerShell without requiring too much factoring of the code.

See commit: f53617847a1b322e208aad9e7cc2333a892e771c

**Comment by aaronparker** [comment]
Updated in `2111.488`
