### ISSUE TITLE
Slack is returning an exception: 403 error (forbidden)

### ISSUE THREAD

**Issue by DanGough** [aaronparker/Evergreen#140]
**Describe the bug**
`Get-EvergreenApp Slack` returns:

> WARNING: Resolve-SystemNetWebRequest: Error at URI: https://slack.com/ssb/download-win-msi.
> WARNING: Resolve-SystemNetWebRequest: Response:  -
> Exception: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2104.337\Private\Resolve-SystemNetWebRequest.ps1:25
> Line |
>   25 |          $webResponse = $httpWebRequest.GetResponse()
>      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      | Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (403) Forbidden."

The URL [https://slack.com/ssb/download-win-msi](https://slack.com/ssb/download-win-msi) does not work in Edge either.

**Comment by DanGough** [comment]
Working URL returned by Winget (and previously also by Evergreen) is:

[https://downloads.slack-edge.com/releases/windows/4.14.0/prod/x64/slack-standalone-4.14.0.0.msi](https://downloads.slack-edge.com/releases/windows/4.14.0/prod/x64/slack-standalone-4.14.0.0.msi)

**Comment by Deyda** [comment]
No Problem in my system with Slack Download.
![image](https://user-images.githubusercontent.com/59874195/114664880-a2aefa00-9cfc-11eb-9fc4-830321e2fb0d.png)

**Comment by aaronparker** [comment]
Working here now. A temporary issue?

**Comment by DanGough** [comment]
Yes, working here now also! Closing the issue, thanks.
