### ISSUE TITLE
Add Cisco Apps?

### ISSUE THREAD

**Issue by endoleg** [aaronparker/Evergreen#141]
I would love to see some Cisco Apps like 
Cisco Jabber 
Cisco Jabber JVDI
Cisco Webex Meetings
Cisco Webex Virtual Desktop Plug-in

Could you add this apps?
Maybe this yaml-file can help for Cisco Webex Meetings

https://github.com/microsoft/winget-pkgs/blob/master/manifests/c/Cisco/CiscoWebexMeetings/41.4.4.10/Cisco.CiscoWebexMeetings.yaml

**Comment by endoleg** [comment]
Latest CiscoJabberSetup.msi:

https://binaries.webex.com/static-content-pipeline/jabber-upgrade/production/jabberdesktop/apps/windows/public/latest/CiscoJabberSetup.msi

**Comment by endoleg** [comment]
Webex Teams:
https://binaries.webex.com/WebexTeamsDesktop-Windows-Gold/WebexTeams.msi

**Comment by endoleg** [comment]
Cisco Webex Meetings:
https://akamaicdn.webex.com/client/webexapp.msi

**Comment by Deyda** [comment]
Cisco Webex Teams VDI
https://www.webex.com/downloads/teams-vdi.html
https://binaries.webex.com/vdi-hvd-aws-gold/20210409082302/Webex.msi

**Comment by aaronparker** [comment]
I need something hosted by Cisco to find the current version of these apps. Best way to do this is to monitor what's going on via Fiddler, when the app checks for new versions. There's likely an API or similar that the app uses.

**Comment by AshleyHow** [comment]
@aaronparker I've managed to find something for some of these apps.

https://welcome.webex.com/webappng/api/v1/download?siteurl=welcome

This covers the below but I'm particularly interested in 'Cisco Webex Meetings' myself.

Cisco Webex Meetings
Cisco Webex Productivity Tools
Cisco Webex Meetings virtual desktop
Cisco Webex Meetings virtual desktop plug-in

**Comment by aaronparker** [comment]
Nice work. Where did you find the URL?

**Comment by AshleyHow** [comment]
https://welcome.webex.com/webappng/sites/welcome/dashboard/download 

If you use the dev tools in MS Edge and click network and filter by XHR the resource appears there.
