### ISSUE TITLE
ESET detects Powershell/Kryptic.Q trojan in Expand-GzipArchive.ps1

### ISSUE THREAD

**Issue by Juun89** [aaronparker/evergreen#151]
The title says it all. I can't find anything weird in the script, but can't find why it gets flagged either.

**Comment by aaronparker** [comment]
Wow. Is this when running `Get-EvergreenApp -Name VMwareHorizonClient` or when installing the module?

**Comment by Juun89** [comment]
Happened when I called Get-EvergreenApp -Name 7Zip. I'm not really sure if it's just a false positive from ESET though. I can however reproduce it. Even browsing the folder where Expand-GzipArchive.ps1 is located triggers ESET.

**Comment by aaronparker** [comment]
It could be the result of calling this code that malware might be using:

```powershell
$GzipStream = New-Object -TypeName "System.IO.Compression.GzipStream" $InputStream, `
        ([System.IO.Compression.CompressionMode]::Decompress)
```

**Comment by Juun89** [comment]
That single piece of code in a saved .ps1 file doesn't trigger it. It does trigger when I copy/paste all the code from the script. Ill try and find which part, or combination of it is.

**Comment by Juun89** [comment]
You were probably looking in the right direction, removing this line makes it not trigger ESET:
`$read = $GzipStream.Read($buffer, 0, $BufferSize)`
