### ISSUE TITLE
Add Wireshark

### ISSUE THREAD

**Issue by aaronparker** [aaronparker/Evergreen#153]
Add support for Wireshark

**Comment by aaronparker** [comment]
Added in d6c25cc4eac81d309c2aa54858123e656ae673c8

**Comment by DanGough** [comment]
Only .exe downloads are reported, but MSIs are available and preferred by many - Winget returns this:

https://www.wireshark.org/download/win64/all-versions/Wireshark-win64-3.4.5.msi

I see the feed XML only lists the exe though. Was this grabbed by watching the app try to auto-update? Maybe the MSI release queries a different feed?!

**Comment by aaronparker** [comment]
Yeah, Fiddler to see what Wireshark is doing when checking for updates. MSIs are also here, so I can add to the output:

```url
https://1.na.dl.wireshark.org/win64/Wireshark-win64-3.4.5.exe
```

**Comment by DanGough** [comment]
I wonder if you could use Wireshark for this instead of Fiddler!

**Comment by aaronparker** [comment]
You could, but Fiddler acts as a proxy, making it a little easier.

**Comment by DanGough** [comment]
I've tested this - the MSI auto updates to the EXE based installer!

If you'd like the function to output both types, the easiest way seems to be to just change the file extension to msi and the resulting URL works.

**Comment by aaronparker** [comment]
Added in 5a6c1a8a44dec82d42c558855f5047f56e8f81dc

**Comment by obuolinis** [comment]
Not sure I'm doing the right thing by reopening this but.... I'm wondering whether anyone uses Evergreen to check for new versions of Wireshark? How am i supposed to narrow it down to a single result when filters for Type and Architecture aren't enough, and the only remaining field to filter on is the exact version number which automation doesn't know in advance? Can you add a field "Latest" perhaps?
