### ISSUE TITLE
VLC reporting incorrect version

### ISSUE THREAD

**Issue by DanGough** [aaronparker/Evergreen#154]
3.0.13 was released today - now Evergreen is reporting 3.0.11 when it was reporting 3.0.12 last week!

Possibly a temporary glitch with their feed, [https://www.videolan.org](https://www.videolan.org) is currently displaying 3.0.13.

Using latest Evergreen v2105.366.

**Comment by DanGough** [comment]
It's now saying 3.0.12 again. Must be their end, hopefully it'll settle on 3.0.13 later on!

**Comment by endoleg** [comment]
https://git.videolan.org/?p=vlc/vlc-3.0.git;a=blob_plain;f=NEWS

**Comment by DanGough** [comment]
Closing - looks like they pulled 3.0.13 in favour of 3.0.14 which screwed things up momentarily!
