### ISSUE TITLE
Add putty

### ISSUE THREAD

**Issue by AshleyHow** [aaronparker/Evergreen#157]
Any chance to add Putty please?

https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html

**Comment by aaronparker** [comment]
PuTTY doesn't have an updater / update URI or do they keep a JSON manifest etc., for updates. The Evergreen project actively avoids scraping HTML to find application versions and URLs.

**Comment by AshleyHow** [comment]
Thanks for making me aware of the Nevergreen project and subsequently adding it @DanGough, much appreciated.
