### ISSUE TITLE
VMware Horizon Client reporting out of date version

### ISSUE THREAD

**Issue by DanGough** [aaronparker/evergreen#161]
Evergreen 2105.371 is reporting the latest version of this as 8.1.0.17349995.

Chocolatey lists 8.2.0.17759012.

I haven't looked at the code just yet, but perhaps they have a different feed for 8.1.x, 8.2.x, etc.

**Comment by aaronparker** [comment]
It's the same feed:

```
https://softwareupdate.vmware.com/horizon-clients/viewcrt-mac/viewcrt-windows.xml
```

However, the XML doesn't provide an easy way to sort for the latest release. See [known issues](https://stealthpuppy.com/Evergreen/knownissues.html#vmwarehorizonclient).

**Comment by aaronparker** [comment]
Ref: 

https://github.com/aaronparker/evergreen/blob/7589228006e5dd7fba9d07bbe4c4a795fc9a9fe5/Evergreen/Apps/Get-VMwareHorizonClient.ps1#L28
