### ISSUE TITLE
Add Microsoft Teams ring for beta and developer, add type exe and ARM64 [FEATURE]

### ISSUE THREAD

**Issue by JonathanPitre** [aaronparker/Evergreen#162]
**Is your feature request related to a problem? Please describe.**
Add Microsoft Teams ring for beta and developer, add type exe and ARM64

**Describe the solution you'd like**
Versions and URI can be grabbed here. I believe this is how winget gets the information.
https://github.com/ItzLevvie/MicrosoftTeams-msinternal/blob/master/defconfig

Exploration = Beta
Continuous Deployment = Developer

**Comment by aaronparker** [comment]
I've added `arm64` to the manifest in the development branch.

**Comment by aaronparker** [comment]
Currently Evergreen uses the following URL to find the Preview ring, where `ring3_9` is added to the query:

```
https://teams.microsoft.com/package/desktopclient/update/1.2.00.32462/windows/x64?ring=ring3_9
```

To add the Exploration or Continuous Deployment rings to Evergreen, we'll what the correct query should be, e.g., `?ring=ring3_9`.

**Comment by aaronparker** [comment]
Teams has the following rings listed in the code; however, none of them are returning versions different from the Preview ring:

* ring0
* ring1
* ring2
* ring3_9

**Comment by JonathanPitre** [comment]
Is it possible to grab the versions from the github page instead ?

**Comment by aaronparker** [comment]
No. Evergreen will use offical sources only.
