### ISSUE TITLE
Incorrect version number is returned for Veracrypt

### ISSUE THREAD

**Issue by AshleyHow** [aaronparker/evergreen#166]
First of all I want to thank you for adding the app to evergreen.

I've gone to test it today and noticed that the version being reported is '1.24' (an older version) when it should be '1.24-Update7'.

**Comment by aaronparker** [comment]
Yep, VeraCrypt's versioning system sucks.

It returns the right executables though. I'll have to update the RegEx at some point to capture the version number. Or create a PR that updates the RegEx here: [https://github.com/aaronparker/Evergreen/blob/2e2af8082151dec18ef059dd6e29b73e2ee48cf4/Evergreen/Manifests/VeraCrypt.json#L21](https://github.com/aaronparker/Evergreen/blob/2e2af8082151dec18ef059dd6e29b73e2ee48cf4/Evergreen/Manifests/VeraCrypt.json#L21)

**Comment by AshleyHow** [comment]
Resolved in latest release from my pull request.
