### ISSUE TITLE
[BUG] FoxitReader & LogMeInGoToOpener returning System.URI instead of String for URI property

### ISSUE THREAD

**Issue by DanGough** [aaronparker/evergreen#174]
Hi, I just found that some apps are returning System.Uri objects instead of strings and this inconsistency is throwing off the rest of my code. I can work around it but I expect the output from all apps to be consistent.

You can find all of the culprits by running:

```powershell
Find-EvergreenApp | Get-EvergreenApp | where-Object URI -isnot [string] -WarningAction Ignore
```

**Comment by aaronparker** [comment]
I'm not seeing the same on my machine (macOS, PowerShell 7). I have added Pester tests to confirm that the `Version` and `URI` properties are strings, so I'll see what that output is: [39303631](https://ci.appveyor.com/project/aaronparker/evergreen/builds/39303631)

**Comment by aaronparker** [comment]
That build picked up that the `URI` properties are URIs and not strings, but it was OK with the `Version` property
