### ISSUE TITLE
Get-EvergreenApp GitHubRelease -URI parameter not specified

### ISSUE THREAD

**Issue by JonathanPitre** [aaronparker/evergreen#183]
**Describe the bug**

I'm trying to pull the latest release of winget from github using the following commands:

`Get-EvergreenApp GitHubRelease | Where-Object {$_.URI -eq "https://api.github.com/repos/microsoft/winget-cli/releases/latest"}`

I get the following error
**WARNING: Get-GitHubRelease: -Uri parameter not specified. Using the default repository.**

I also tried this:

`Get-EvergreenApp GitHubRelease -URI 'https://api.github.com/repos/microsoft/winget-cli/releases/latest'` 

and I get this error:
**Get-EvergreenApp : A parameter cannot be found that matches parameter name 'URI'.**

Am I doing this wrong ? Thanks for your help.

![image](https://user-images.githubusercontent.com/15003329/120215305-90811080-c203-11eb-9408-cc262bfaa8d9.png)

**Comment by aaronparker** [comment]
This one won't work since the move to `Get-EvergreenApp`. Also there's no `URI` parameter on `Get-EvergreenApp`.

**Comment by JonathanPitre** [comment]
Yeah it was working fine in previous release. I assume there no alternative way to get this working at the moment ?

**Comment by aaronparker** [comment]
Not yet. I'm thinking of adding support for passing a hashtable to the internal app functions that would be used as parameters for those functions.

**Comment by DanGough** [comment]
Just in case you didn't spot it, your Winget example is already an Evergreen app - MicrosoftWindowsPackageManagerClient.

If you have other apps on GitHub you want to query, try copying an existing manifest/script, change the name/URL, and hey presto you've got a new Evergreen app to submit.

**Comment by aaronparker** [comment]
It should now be possible to pass a custom repo to `GitHubRelease` via `Get-EvergreenApp -AppParams`. See: https://stealthpuppy.com/evergreen/help/en-US/Get-EvergreenApp/
