### ISSUE TITLE
Get-evergreenapp OBSStudio not working due to a 404 errors

### ISSUE THREAD

**Issue by AshleyHow** [aaronparker/evergreen#184]
```
PS C:\Users\Ashley.How> get-evergreenapp OBSStudio
Internal application function: C:\Users\Ashley.How\Documents\WindowsPowerShell\Modules\Evergreen\2105.388\Apps\Get-OBSStudio.ps1, failed with: Invoke-RestMethodWrapper: The remote server returned an error:
(404) Not Found..
At C:\Users\Ashley.How\Documents\WindowsPowerShell\Modules\Evergreen\2105.388\Public\Get-EvergreenApp.ps1:54 char:17
+ ...             Throw "Internal application function: $Function, failed w ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Internal applic...04) Not Found..:String) [], RuntimeException
    + FullyQualifiedErrorId : Internal application function: C:\Users\Ashley.How\Documents\WindowsPowerShell\Modules\Evergreen\2105.388\Apps\Get-OBSStudio.ps1, failed with: Invoke-RestMethodWrapper: The remo
   te server returned an error: (404) Not Found..
```

I'm not sure if this is temporary issue but https://obsproject.com/update_studio/manifest.json returns a 404 currently. Appreciate this is down to OBS to fix so have logged an issue with them https://github.com/obsproject/obs-studio/issues/4783

I noticed that releases are also on github - https://github.com/obsproject/obs-studio/releases

**Comment by AshleyHow** [comment]
Got an update -

> It's not currently available because we're in the middle of an update. That's probably not the most reliable way to determine the current version. I'd probably check the git for the latest non-RC non-beta release tag instead. And even then, sometimes we delete the tag.

Does it make it a candidate for Nevergreen instead perhaps?

**Comment by AshleyHow** [comment]
> Also just as a note, we sometimes temporarily remove the file to halt updates. So what we'll usually do is release, then if we see anything go wrong, we'll pause the updates by temporarily removing/renaming the file, then when we're ready we'll put it back again. Kind of gives me a somewhat scuffed way to do rolling updates if I need to gauge how the update is going for users.

**Comment by aaronparker** [comment]
I'll take a look at the GitHub releases again, but the reason I've gone with the in-built updater method is that sometimes they're putting releases on the repo that don't include Windows. For example:  [26.1.2](https://github.com/obsproject/obs-studio/releases/tag/26.1.2).

**Comment by aaronparker** [comment]
`https://obsproject.com/update_studio/manifest.json` is back up and given the release types that sometimes appear on the GitHub repo, I'll still with the existing method and add to the known issues.

**Comment by aaronparker** [comment]
Added issue to the list of [known issues](https://stealthpuppy.com/evergreen/issues/#obs-studio)
