### ISSUE TITLE
Update Get-GitHubRepoRelease to support authenticated sessions to GitHub

### ISSUE THREAD

**Issue by aaronparker** [aaronparker/evergreen#195]
`Get-GitHubRepoRelease` has been updated to handle rate limiting for unauthenticated sessions to the GitHub API. Authenticated sessions to the API are not rate limited, thus `Get-GitHubRepoRelease` could be updated to support authenticated sessions to fix scenarios where rate limiting kicks in.

Ref: [https://github.com/aaronparker/evergreen/blob/07606fe401feccef723a72ecf520948135017cdb/Evergreen/Private/Get-GitHubRepoRelease.ps1#L56](https://github.com/aaronparker/evergreen/blob/07606fe401feccef723a72ecf520948135017cdb/Evergreen/Private/Get-GitHubRepoRelease.ps1#L56)

Ref: [https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting)

**Comment by aaronparker** [comment]
Thinking about how to implement this. The simplest approach might be to get `Get-GitHubRepoRelease` to check for an environment variable call `GITHUB_TOKEN`. That way it would work when a token is add manually and would also work when run in a GitHub workflow. This would be a simple way to add support for authentication to the GitHub API with a personal access token.

**Comment by vedantmgoyal2009** [comment]
You can check for both `GITHUB_TOKEN` and `GH_TOKEN`. The second one is also very commonly used.

**Comment by aaronparker** [comment]
Support for a token stored in `GITHUB_TOKEN` added in 83c605b495e60b3bc4acccb2878f6b1a6e05c56c. Tests OK.
