### ISSUE TITLE
[FEATURE] Add App: Amazon JDK 8/11 Corretto

### ISSUE THREAD

**Issue by BornToBeRoot** [aaronparker/evergreen#198]
New App: Amazon JDK 8 Corretto

Permanent Download URL:
https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html
https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/downloads-list.html

Releases:
https://github.com/corretto/corretto-8/releases
https://github.com/corretto/corretto-11/releases

**Comment by adotcoop** [comment]
Does these commands do what you require? 

`Get-EvergreenApp AmazonCorretto | Where-Object {$_.JDK -eq "8"}`

and

`Get-EvergreenApp AmazonCorretto | Where-Object {$_.JDK -eq "11"}`

Evergreen doesn't return the zip files for these as it was thought the installers would be more useful. They could be added back in, but would increase the time to return the objects from the script

JDK 15 and 16 are also available from the script if needed.
