### ISSUE TITLE
[BUG] AdoptOpenJDK8 wrong version? 

### ISSUE THREAD

**Issue by BornToBeRoot** [aaronparker/evergreen#199]
I think `Get-EvergreenApp AdoptOpenJDK8` returns the wrong version.

```
Version      : 0.26.0
Platform     : Windows
Architecture : x64
Type         : msi
Date         : 2019-01-11T17:06:45Z
Size         : 105721856
URI          : https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u292-b10_openj9-0.26.0/OpenJDK8U
               -jdk_x64_windows_openj9_8u292b10_openj9-0.26.0.msi
```

The version should be `jdk8u292-b10_openj9-0.26.0` or `jdk8u292-b10` 

https://github.com/AdoptOpenJDK/openjdk8-binaries/releases

**Comment by BornToBeRoot** [comment]
Also the `hotspot` binaries should be shown. Currently only the `openj9`.

**Comment by DanGough** [comment]
Also discussed here: https://github.com/aaronparker/evergreen/issues/126

It seems they haven’t organised all their release tagging in a consistent way which makes it harder to query. I do have this app planned for inclusion in Nevergreen so I can just pull the releases off of the home page until we can get this resolved.

**Comment by aaronparker** [comment]
I've just added Temurin binaries and they've got the same issue - they've patched the MSI of an earlier version and that shows as the latest release.

I've not installed the binaries to see whether there's an internal update mechanism that could be queried instead of the GitHub repo.

**Comment by aaronparker** [comment]
This may work but will require some effort to determine whether these are all of the parameters that `api.adoptium.net` will accept.

https://api.adoptium.net/v3/assets/latest/8/hotspot?release=latest&jvm_impl=hotspot&vendor=adoptium&
https://api.adoptium.net/v3/assets/latest/11/hotspot?release=latest&jvm_impl=hotspot&vendor=adoptium&
https://api.adoptium.net/v3/assets/latest/16/hotspot?release=latest&jvm_impl=hotspot&vendor=adoptium&

**Comment by aaronparker** [comment]
The source code for the API is here: https://github.com/adoptium/api.adoptium.net
Documentation is here: https://api.adoptium.net/q/swagger-ui/
