### ISSUE TITLE
Zoom currently failing

### ISSUE THREAD

**Issue by DanGough** [aaronparker/evergreen#200]
Zoom is not working right now because Zoom Rooms returns a 403 error which also stops all of the other results coming through.

**Comment by aaronparker** [comment]
Probably need to update `Get-Zoom` or `Resolve-SystemNetWebRequest` to not `Throw` when it encounters an error and instead `Write-Warning` so that something is returned

**Comment by aaronparker** [comment]
I've included an update in commit 1a836f43caf3903da10bc0b4e09430ed6f461c77 that returns a custom URI if the source is unavailable.

I also need to check the source to see whether it's been moved or temporarily unavailable.

**Comment by DanGough** [comment]
It’s probably just a temporary issue with their site - the main download page https://zoom.us/zoomrooms/software is still offering up the broken link https://zoom.us/client/latest/ZoomRooms.exe.

**Comment by aaronparker** [comment]
I think the approach to returning something rather than throwing might be a better approach overall. The function now uses `Write-Warning` instead of `Throw` and a link to the known issues page. The `-Verbose` option also provides you with some idea of what's going on. 

Returning a URI with a link to the docs page might give me the chance to explain how to troubleshooting issues.

**Comment by aaronparker** [comment]
The Zoom URLs have changed, I think with the introduction of 64-bit versions of their apps, so I'll need to find another way to determine the version numbers.

For example:

https://zoom.us/client/latest/ZoomInstaller.exe
https://zoom.us/client/5.7.1.543/ZoomInstaller.exe?archType=x64
https://zoom.us/client/5.7.1.543/ZoomInstaller.exe?archType=winarm64
https://zoom.us/client/latest/ZoomOutlookPluginSetup.msi
https://zoom.us/client/latest/ZoomNotesPluginSetup.msi
https://zoom.us/client/latest/ZoomInstallerFull.exe
https://zoom.us/client/5.7.1.543/ZoomInstallerFull.exe?archType=x64
https://zoom.us/client/5.7.1.543/ZoomInstallerFull.exe?archType=winarm64
https://zoom.us/client/latest/zoomrooms-5.7.0.144-x86.exe
https://zoom.us/client/latest/ZoomLyncPluginSetup.msi

**Comment by DanGough** [comment]
I've been using those URLs for some time, they all support the "zoom.us/client/latest" path, I then extract the version from the fully resolved URL that swaps 'latest' for the version. What has broken this is that now Zoom Rooms also has the version in the filename when it did not before, so you can no longer use a static URL!

I've updated my version to pull the links for rooms exe/msi straight off that page, and also added the ARM64 support for the main app: https://github.com/DanGough/Nevergreen/blob/main/Nevergreen/Apps/Get-Zoom.ps1

I've also just realised there are both ZoomInstaller and ZoomInstallerFull. ZoomInstaller exe is the regular download for normies, and ZoomInstallerFull exe is listed as 'Zoom Client Plugin for Sharing iPhone/iPad'. I assume it is the full client with that extra plugin.

For IT admins though, they only list the ZoomInstallerFull MSI, so I assume that is the most comprehensive one. I was using a mixture of both but now I'm strictly returning ZoomInstallerFull for both exe and MSI!

**Comment by aaronparker** [comment]
Work around added, in `2107.408`, but will need to update again with new sources listed above.

**Comment by LadtoHelp** [comment]
Just trying to get the url for the 64bit installers but evergreen is only selecting the 32bit. No option to select the 64bit versions.
