### ISSUE TITLE
[FEATURE] Postman

### ISSUE THREAD

**Issue by haavarstein** [aaronparker/evergreen#202]
I don't know if this is enough, but what I found.

https://dl.pstmn.io/changelog?channel=stable&platform=win64

**Comment by haavarstein** [comment]
https://github.com/lukesampson/scoop-extras/blob/master/bucket/postman.json

**Comment by adotcoop** [comment]
I quickly coded up something based on the json returned from the first link. The download uri doesn't contain the filename, but the json does, so we end up with this 

![image](https://user-images.githubusercontent.com/67840206/124609179-4ffe5d80-de67-11eb-8099-7707145425fd.png)

so Save-EvergreenApp works 

![image](https://user-images.githubusercontent.com/67840206/124629397-4f6ec280-de79-11eb-87c1-3601640ea6a6.png)

Does this look correct? (I know the date format needs fixing)

**Comment by aaronparker** [comment]
Looks good. Just make sure that `Version` is the first listed property and `URI` is the last listed version.

**Comment by aaronparker** [comment]
Added in `2107.408`
