### ISSUE TITLE
AppVentiX

### ISSUE THREAD

**Issue by bmitchell76** [aaronparker/evergreen#205]
Can AppVentiX be added?  I mentioned it to Bram Wolfs and he said he'd be willing to make changes on his side to accommodate.

**Comment by aaronparker** [comment]
As long as there's an update API or something to query, it could be added. Just need to determine whether AppVentiX queries something to tell you whether there's an update or not

**Comment by bramcw** [comment]
This is on the roadmap, in the mean time Dan Gough added an integration in his project for the current download method: https://github.com/DanGough/Nevergreen/blob/dev/Nevergreen/Apps/Get-AppVentix.ps1 would be great to integrate with Evergreen as well when available, thanks

**Comment by aaronparker** [comment]
@bramcw any update on this?

**Comment by bramcw** [comment]
Hi Aaron, sorry forgot to update this post. There is a dedicated download link which always points to the latest version: https://download.appventix.com/latest will this be enough to integrate with Evergreen? Thanks!

**Comment by aaronparker** [comment]
Thanks. Unfortunately the way that SharePoint/OneDrive appears to be redirecting to the file, I can't see details of where it's resolving to (to then determine the version number) without downloading the entire file which isn't ideal.

An evergreen URL though is great for anyone just looking to download the file.

**Comment by aaronparker** [comment]
Does the AppVentix console have a "check for updates" function?

**Comment by bramcw** [comment]
Makes sense, I will get back to you this week on this, thanks

**Comment by aaronparker** [comment]
Looks good. I'll see what I can put together
