### ISSUE TITLE
[FEATURE] Master Packager

### ISSUE THREAD

**Issue by haavarstein** [aaronparker/evergreen#206]
Didn't we add this before?

https://www.masterpackager.com/uploads/file_archive/version.txt

**Comment by aaronparker** [comment]
Not yet

**Comment by aaronparker** [comment]
Added in `2017.408`; however, it will need to be re-tested when there is a new release of Master Packager.

Also, only the Free version has been added

**Comment by DanGough** [comment]
Free and paid versions use the same installer btw, you just need to add a license key.

**Comment by aaronparker** [comment]
Ah, nice. Thanks
