### ISSUE TITLE
Unable to get the latest FSLogix release

### ISSUE THREAD

**Issue by kaspersmjohansen** [aaronparker/evergreen#210]
The Get-EvergreenApp -Name MicrosoftFSLogixApps throwns an error.

Screenshot attached!
![2eONIWECZY](https://user-images.githubusercontent.com/37331486/125431877-85ff9194-7b5b-4262-93e6-2f9654b1e5c3.jpg)

**Comment by aaronparker** [comment]
Update to the latest version

**Comment by kaspersmjohansen** [comment]
Thanks.
