### ISSUE TITLE
[New app]: Total Commander

### ISSUE THREAD

**Issue by rweijnen** [aaronparker/evergreen#229]
### What is the new application?

Total Commander, a very useful more admin focused file manager (although it can do much more than just files) and can be extended with plugins. 32-bit, 64-bit and combined 32+64 bit download is available. For most purposes the 32-bit version suffices (even on x64 os) and has the best compatibility with plugins.

Total Commander gets the version information via DNS lookup.
For example, the cmd.exe command
nslookup -type=TXT releaseversion.ghisler.com
returns
"10.10.0.0;1"

The first 10 is ignored, the second is the major version. The minor
version and release type are both zero. ;1 means "check every 1 day".

### Vendor site

https://www.ghisler.com/

### Have you reviewed the list of supported applications?

- [X] Support apps at: https://stealthpuppy.com/evergreen/apps/

**Comment by aaronparker** [comment]
`TXT` record - well that's new.

**Comment by rweijnen** [comment]
Quite clever actually, takes away a lot of load from the webserver...

**Comment by rweijnen** [comment]
`Resolve-DnsName -Name 'releaseversion.ghisler.com' -Type 'TXT'` or `Resolve-DnsName -Name 'releaseversion.ghisler.com' -Type 'TXT' | select -ExpandProperty Strings` ?

**Comment by aaronparker** [comment]
Not sure to be honest. Perhaps this is best:

`Resolve-DnsName -Name 'releaseversion.ghisler.com' -Type 'TXT' | select -ExpandProperty Strings`

**Comment by rweijnen** [comment]
Just parse that with a RegEx ? e.g. 
`$tcVersion = Resolve-DnsName -Name 'releaseversion.ghisler.com' -Type 'TXT' | select -ExpandProperty Strings`
`[Version]([RegEx]'(?<=^...).*(?=;)').Match($tcVersion).Groups.Value`

**Comment by aaronparker** [comment]
That's about the best you could do. The returned value via DNS is unlikely to be subject to too many parsing issues. You'd have to validate that is parses the same on Linux and optionally macOS as well.

**Comment by RoyEssers** [comment]
I just parsed https://www.ghisler.com/download.htm to get version and dl links, not very neat, but it does the job: `$Content = Invoke-WebRequest https://www.ghisler.com/download.htm
$Content.Links.href | where {$_ -like 'https*x32.exe' -or $_ -like 'https*x64.exe'} | foreach{
    $PSObject = [PSCustomObject] @{
        Version = $($_ -replace "[^0-9]" , '').Substring(0,$($_ -replace "[^0-9]" , '').Length-2)
        URI     = $_
        FileName = $($_ -split '/')[-1]
    }
    switch -wildcard ($_)
    {
        '*x32.exe' {$PSObject | Add-Member -Name 'Architecture' -Type NoteProperty -Value 'x86'}
        '*x64.exe' {$PSObject | Add-Member -Name 'Architecture' -Type NoteProperty -Value 'x64'}
    }
    Write-Output -InputObject $PSObject
}`
Did you find a better way?

**Comment by aaronparker** [comment]
@RoyEssers Evergreen actively avoids parsing HTML because it's too unpredictable.

@rweijnen `Resolve-DnsName` isn't available on macOS or Linux, so looking into `[System.Net.Dns]`

**Comment by aaronparker** [comment]
Added in `2110.467`
