### ISSUE TITLE
[New app]: Google Chrome Beta, Dev, Canary

### ISSUE THREAD

**Issue by vedantmgoyal2009** [aaronparker/evergreen#243]
### What is the new application?

Beta: https://www.google.com/intl/en_in/chrome/beta/
Dev: https://www.google.com/intl/en_in/chrome/dev/
Canary: https://www.google.com/intl/en_in/chrome/canary/

Edit: Modifying existing JSON and script may return beta, dev, canary editions.

### Vendor site

https://www.google.com/intl/en_in/chrome/

### Have you reviewed the list of supported applications?

- [X] Support apps at: https://stealthpuppy.com/evergreen/apps/

**Comment by aaronparker** [comment]
Updated `GoogleChrome` in fd8dbc81defb5b6ad1fef0a71ee0c2c679a0fc84 to add `Beta` and `Dev` channels. There doesn't appear to be an MSI for the `Canary` channel, so haven't added that.

**Comment by vedantmgoyal2009** [comment]
For canary, there's an `EXE`:
- `x64`: https://dl.google.com/tag/s/appguid%3D%7B4EA16AC7-FD5A-47C3-875B-DBF4A2008C20%7D%26usagestats%3D1%26ap%3Dx64-canary-statsdef_1/update2/installers/ChromeSetup.exe
- `x86`: https://dl.google.com/tag/s/appguid%3D%7B4EA16AC7-FD5A-47C3-875B-DBF4A2008C20%7D%26usagestats%3D1%26ap%3D-statsdef_1/update2/installers/ChromeSetup.exe
