### ISSUE TITLE
[New app]: 8x8 Work

### ISSUE THREAD

**Issue by vedantmgoyal2009** [aaronparker/evergreen#244]
### What is the new application?

Helpful Links
- https://support.8x8.com/cloud-phone-service/voice/work-desktop/download-8x8-work-for-desktop
- https://www.8x8.com/developer

### Vendor site

https://www.8x8.com/au/voip-business-phone-services/features/virtual-office-desktop

### Have you reviewed the list of supported applications?

- [X] Support apps at: https://stealthpuppy.com/evergreen/apps/

**Comment by aaronparker** [comment]
Unable to find an update feed for this so far. With the application installed, it's not talking to anything to search for an update (monitoring via Fiddler). I don't have a 8x8 login, so the application may act differently after sign-in.

If you use 8x8, try using Fiddler with the 8x8 Desktop exe installer to see what it might be talking to, to find updates.

**Comment by vedantmgoyal2009** [comment]
Found in https://github.com/DanGough/Nevergreen.
