### ISSUE TITLE
[New app]: Unity LTS

### ISSUE THREAD

**Issue by vedantmgoyal2009** [aaronparker/evergreen#245]
### What is the new application?

LTS releases feed: https://unity3d.com/unity/lts-releases.xml

I did not find any API/feed for normal releases, however, if you are able to find it, please add that also.

### Vendor site

https://unity3d.com/

### Have you reviewed the list of supported applications?

- [X] Support apps at: https://stealthpuppy.com/evergreen/apps/

**Comment by aaronparker** [comment]
Unfortunately that feed returns HTML that would need to be scraped.

Does the application have an in-built updater that talks to an API?

**Comment by vedantmgoyal2009** [comment]
* https://github.com/vedantmgoyal2009/vedantmgoyal2009/issues/868

**Comment by vedantmgoyal2009** [comment]
@aaronparker The above issue mentions a GraphQL API from where updates can be fetched. I think you have missed my comment, and today I was revisiting all my issues, so thought to remind you :)
