### ISSUE TITLE
[New app]: Microsoft Teams

### ISSUE THREAD

**Issue by vedantmgoyal2009** [aaronparker/evergreen#247]
### What is the new application?

This app already exists in the repository, just wanted to add some more editions.

Reference: https://github.com/ItzLevvie/MicrosoftTeams-msinternal

### Vendor site

https://www.microsoft.com/en-in/microsoft-teams/group-chat-software

### Have you reviewed the list of supported applications?

- [X] Support apps at: https://stealthpuppy.com/evergreen/apps/

**Comment by aaronparker** [comment]
Is there a name for each of the additional rings? The existing function exports `Preview` and `General`:

```
Version      Ring    Architecture URI
-------      ----    ------------ ---
1.4.00.31569 Preview arm64        https://statics.teams.cdn.office.net/production-windows-arm64/1.4.00.31569/Teams_windows_arm64.msi
1.4.00.31569 Preview x86          https://statics.teams.cdn.office.net/production-windows/1.4.00.31569/Teams_windows.msi
1.4.00.31569 Preview x64          https://statics.teams.cdn.office.net/production-windows-x64/1.4.00.31569/Teams_windows_x64.msi
1.4.00.29469 General arm64        https://statics.teams.cdn.office.net/production-windows-arm64/1.4.00.29469/Teams_windows_arm64.msi
1.4.00.29469 General x86          https://statics.teams.cdn.office.net/production-windows/1.4.00.29469/Teams_windows.msi
1.4.00.29469 General x64          https://statics.teams.cdn.office.net/production-windows-x64/1.4.00.29469/Teams_windows_x64.msi
```

**Comment by aaronparker** [comment]
It might also be useful to add ARM64 support and the additional file types identified in that repo.

**Comment by vedantmgoyal2009** [comment]
You can see the reply posted by Levvie here: https://github.com/vedantmgoyal2009/winget-pkgs-automation/issues/157
