### ISSUE TITLE
Get-MicrosoftSsms

### ISSUE THREAD

**Issue by haavarstein** [aaronparker/Evergreen#25]
Returns old 16 version

**Comment by aaronparker** [comment]
See the documentation on version number vs. build number here: [Download SQL Server Management Studio (SSMS)](https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15).

**Comment by aaronparker** [comment]
The updated version of the function uses the update API to check for the new version that returns the build number rather than the release version.

**Comment by haavarstein** [comment]
I'm aware of the version vs build number. Problem is that it installs Microsoft SQL Server 2016 RC1. Even looks like it adds SQL Server as well. SSMS-Setup-ENU file version 13.0.1250..29

**Comment by aaronparker** [comment]
Should be fixed in `1910.62`

**Comment by haavarstein** [comment]
Confirmed working.
