### ISSUE TITLE
[New app]: VisualCppRedistAIO

### ISSUE THREAD

**Issue by JonathanPitre** [aaronparker/evergreen#250]
### What is the new application?

AIO Repack for latest Microsoft Visual C++ Redistributable Runtimes, without the original setup bloat payload.

Built upon VBCRedist_AIO_x86_x64.exe by @ricktendo64

The process is handled by a windows command script, which runs hidden in the background by default.

Before installation, the script will check and remove existing non-compliant Visual C++ Runtimes, including the original EXE or MSI setups, or older MSI packages versions.

The uninstallation option/script will remove any detected VC++ runtimes (except UCRT).

### Vendor site

https://github.com/abbodi1406/vcredist

### Have you reviewed the list of supported applications?

- [X] Support apps at: https://stealthpuppy.com/evergreen/apps/

**Comment by durrante** [comment]
Good day, 

I cannot see this app in the supported list anymore, has it been removed?

**Comment by aaronparker** [comment]
VisualCppRedistAIO is repackaged by a third party and not by Microsoft, so it won't be supported by Evergreen. I want Evergreen to only pull from official vendor sources to ensure trust.
