### ISSUE TITLE
[New app]: Plex Apps

### ISSUE THREAD

**Issue by vedantmgoyal9** [aaronparker/evergreen#270]
### What is the new application?

* https://github.com/vedantmgoyal2009/winget-pkgs-automation/issues/129

You can add some packages from my repo.

### Vendor site

https://plex.tv

### Have you reviewed the list of supported applications?

- [X] Support apps at: https://stealthpuppy.com/evergreen/apps/

**Comment by aaronparker** [comment]
Evergreen's focus is primarily on enterprise applications, so assigning this a low priority

**Comment by aaronparker** [comment]
Download feed is here: https://plex.tv/api/downloads/7.json
