### ISSUE TITLE
[Bug]: 7zip does not report latest version

### ISSUE THREAD

**Issue by JonathanPitre** [aaronparker/evergreen#271]
### What happened?

Get-EvergreenApp 7zip does not report the latest version 21.05.

![image](https://user-images.githubusercontent.com/15003329/142931091-8434959d-bc35-4232-90ca-59e5e82f9c57.png)

See release notes history
**https://www.7-zip.org/history.txt**

See 21.05 release info
https://sourceforge.net/p/sevenzip/discussion/45797/thread/edcb38bbab/

Maybe it's because the MSI versions are not yet released ?

### Version

latest

### What PowerShell edition/s are you running Evergreen on?

Windows PowerShell

### Which operating system/s are you running Evergreen on?

Windows 10

### Have you reviewed the documentation?

- [X] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [X] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
Version Architecture Type URI                                                                          
------- ------------ ---- ---                                                                          
21.04   x64          msi  https://nchc.dl.sourceforge.net/project/sevenzip/7-Zip/21.04/7z2104-x64.msi  
21.04   x64          exe  https://nchc.dl.sourceforge.net/project/sevenzip/7-Zip/21.04/7z2104-x64.exe  
21.04   ARM64        exe  https://nchc.dl.sourceforge.net/project/sevenzip/7-Zip/21.04/7z2104-arm64.exe
21.04   ARM32        exe  https://nchc.dl.sourceforge.net/project/sevenzip/7-Zip/21.04/7z2104-arm.exe  
21.04   x86          msi  https://nchc.dl.sourceforge.net/project/sevenzip/7-Zip/21.04/7z2104.msi      
21.04   x86          exe  https://nchc.dl.sourceforge.net/project/sevenzip/7-Zip/21.04/7z2104.exe
```

**Comment by aaronparker** [comment]
It's because there's no `21.05` release available on the SourceForge repo nor is `21.05` listed in the release json: https://sourceforge.net/projects/sevenzip/best_release.json

`Get-EvergreenApp -Name 7Zip -Verbose` will show you what it's retrieving from the source.

**Comment by JonathanPitre** [comment]
Story checks out, we can close this one :P

**Comment by JonathanPitre** [comment]
Will be available once the json is updated
https://sourceforge.net/projects/sevenzip/best_release.json
