### ISSUE TITLE
[New app]: Crowdstrike Falcon Sensor

### ISSUE THREAD

**Issue by bmitchell76** [aaronparker/evergreen#277]
### What is the new application?

Crowdstrike Falcon Sensor next-gen AV EDR.  I'm uncertain if there is a public download

### Vendor site

https://www.crowdstrike.com/

### Have you reviewed the list of supported applications?

- [X] Supported apps at: https://stealthpuppy.com/evergreen/apps/

**Comment by aaronparker** [comment]
Can you use Fiddler or similar to see where the Sensor is looking for updates?

**Comment by bmitchell76** [comment]
I finally have access to the download; it does require a login, and I captured this in a Fiddler trace.  It doesn't appear to require authentication.  I dug in a little bit, but I'm not sure if it has what's needed to add to Evergreen. 

https://falcon.crowdstrike.com/content/i18n-v1/translations/falcon-hosts/index.json

**Comment by aaronparker** [comment]
Unfortunately that URL reports `Invoke-RestMethod: MissingKeyMissing Key-Pair-Id query parameter or cookie value`, so it could be requiring an authentication cookie or something else.

**Comment by bmitchell76** [comment]
Same for me; if I let the login timeout, I'll see if there is a way to pass our tenant ID and go from there.

**Comment by bmitchell76** [comment]
[Sensor download APIs _ Documentation _ Support _ Falcon.pdf](https://github.com/aaronparker/evergreen/files/7690248/Sensor.download.APIs._.Documentation._.Support._.Falcon.pdf)

**Comment by bmitchell76** [comment]
It looks like first I'd have to enroll in their OAuth2-Based APIs and not something I can share outside my organization.  I'll tinker with it and see how far I can get on my own.
