### ISSUE TITLE
[Bug]: Paint.NET has a new download URL

### ISSUE THREAD

**Issue by BornToBeRoot** [aaronparker/evergreen#283]
### What happened?

With version 4.3.4 Paint.NET has a new github repo for the downloads:

- exe (x86, x64, arm)
- msi (x86, x64, arm)
- portable (x86, x64, arm)

https://github.com/paintdotnet/release/releases

This is also the only way to get the MSI now (you can create it anymore from the "old" setup file)

### Version

4.3.4

### What PowerShell edition/s are you running Evergreen on?

Windows PowerShell

### Which operating system/s are you running Evergreen on?

Windows 10

### Have you reviewed the documentation?

- [X] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [X] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
-
```

**Comment by aaronparker** [comment]
`PaintDotNetOfflineInstaller` pulls from that repo. The seperate `PaintDotNet` uses the old mechanism.

**Comment by BornToBeRoot** [comment]
@aaronparker  thanks. I did not see that.

**Comment by BornToBeRoot** [comment]
@aaronparker the Type should be exe / msi. Otherwise you can't filter for the download link.


![image](https://user-images.githubusercontent.com/16019165/145190151-88c33f0b-c4f9-4fe5-abec-a2c9487f1379.png)

**Comment by aaronparker** [comment]
`Type` is as-designed at the moment. This is the file type of the file in the `URI` property.

You could use this:

```powershell
Get-EvergreenApp -Name "PaintDotNetOfflineInstaller" | Where-Object { $_.Uri -match "winmsi.x64" }
```

**Comment by BornToBeRoot** [comment]
OK. thanks again. I added this to my script :)
