### ISSUE TITLE
[Feature]: Additional download formats for Notepad++

### ISSUE THREAD

**Issue by ThiloLangbeinHUK** [aaronparker/evergreen#287]
### What is your feature request?

For NotepadPlusPlus please make other downloads (i. e. minimalistic/portable) available via Get-EvergreenApp 

### Have you tested against the current version?

- [X] Yes, I've updated Evergreen and tested against the current version.

### Have you reviewed the documentation?

- [X] Documentation at: https://stealthpuppy.com/evergreen/

**Comment by aaronparker** [comment]
What's the value in adding the other installer types?

**Comment by ThiloLangbeinHUK** [comment]
We want to automate download of NP++ for internal deployment.
For this we need the portable/minimalistic download packs.

**Comment by aaronparker** [comment]
What's the difference though between the full version and the portable/minimal? Particularly for an enterprise environment

**Comment by ThiloLangbeinHUK** [comment]
Thanks. :-)
