### ISSUE TITLE
CloudDriveMapper

### ISSUE THREAD

**Issue by tabularasa138** [aaronparker/evergreen#289]
### What is the new application?

Direct link to download page - https://resources.iamcloud.net/apps/cdm/clouddrivemapper.exe

CDM adds new versions regularly to keep up with the changing landscape of SharePoint.  

### Vendor site

https://www.iamcloud.com/

### Have you reviewed the list of supported applications?

- [X] Supported apps at: https://stealthpuppy.com/evergreen/apps/

**Comment by aaronparker** [comment]
Does the CloudDriveMapper perform an in app update check on the client?

**Comment by tabularasa138** [comment]
It does not appear to.

On Jan 5, 2022 9:44 PM, Aaron Parker ***@***.***> wrote:
CAUTION: This email originated from outside of VC3's email system. Maintain caution when opening external links/attachments



Does the CloudDriveMapper perform an in app update check on the client?

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Faaronparker%2Fevergreen%2Fissues%2F289%23issuecomment-1006217283&data=04%7C01%7Cryan.gallier%40vc3.com%7Cef0b5c0bf9d747e4d33a08d9d0b61aab%7Cc9060d2b86db4625a6cc04c3eef1cd05%7C0%7C0%7C637770302839982833%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=MjWVuUge9mU9YvXhIq4brCPzhbl7DUDJatnepbvagTc%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEONN2LQJN3MPOWBTKV3XHTUUTXYPANCNFSM5KA6ZP2Q&data=04%7C01%7Cryan.gallier%40vc3.com%7Cef0b5c0bf9d747e4d33a08d9d0b61aab%7Cc9060d2b86db4625a6cc04c3eef1cd05%7C0%7C0%7C637770302839982833%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=M6iBgH09JLndwrY7FGpY79qSTsNPkgqRjrTazsTHG6o%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cryan.gallier%40vc3.com%7Cef0b5c0bf9d747e4d33a08d9d0b61aab%7Cc9060d2b86db4625a6cc04c3eef1cd05%7C0%7C0%7C637770302839982833%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=RdsJVx%2B2hatz3wB4vvj6F5KgkAlk5e%2FDyhPO26qFi0M%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cryan.gallier%40vc3.com%7Cef0b5c0bf9d747e4d33a08d9d0b61aab%7Cc9060d2b86db4625a6cc04c3eef1cd05%7C0%7C0%7C637770302839982833%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FZfFvopz0z1VJ%2BgEw94uZDmhJzeiIAUzPTB7Quepjrw%3D&reserved=0>.
