### ISSUE TITLE
[New app]: Ivanti Workspace Control

### ISSUE THREAD

**Issue by hpmillaard** [aaronparker/evergreen#293]
### What is the new application?

Ivanti Workspace Control is used to configure user desktops.

Latest version can be found here:
https://forums.ivanti.com/s/article/Ivanti-Workspace-Control-revision-download-links

### Vendor site

https://www.ivanti.com/products/workspace-control

### Have you reviewed the list of supported applications?

- [X] Supported apps at: https://stealthpuppy.com/evergreen/apps/

**Comment by aaronparker** [comment]
Is there an location/REST API etc., that can be used to query for the latest version. These installers are behind a login

**Comment by hpmillaard** [comment]
I'm not aware of a location without login, but I've asked this question in the support forum.
