### ISSUE TITLE
[Bug]: Microsoft365Apps versions reported incorrectly

### ISSUE THREAD

**Issue by JonathanPitre** [aaronparker/evergreen#294]
### What happened?

Get-Evergreen365Apps reports the incorrect versions of 365 apps.

Here's the latest version, according to https://docs.microsoft.com/en-us/officeupdates/update-history-microsoft365-apps-by-date
![image](https://user-images.githubusercontent.com/15003329/149052170-d6f1280c-c197-405f-a90d-1e82449844f7.png)

and here's what's reported by Evergreen
![image](https://user-images.githubusercontent.com/15003329/149052327-8eb67a54-8b04-4a4d-abf0-b48e46c6719b.png)

However, the proper versions are being downloaded, the number displayed by the Evergreen command is just incorrect.

I understand the versions are grabbed from this URL:
https://mrodevicemgr.officeapps.live.com/mrodevicemgrsvc/api/v2/C2RReleaseData?audienceFFN=

I would suggest getting the versions from here instead, just like Winget does.
https://github.com/ItzLevvie/Office16/blob/master/defconfig

### Version

2112.512

### What PowerShell edition/s are you running Evergreen on?

Windows PowerShell

### Which operating system/s are you running Evergreen on?

Windows 10

### Have you reviewed the documentation?

- [X] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [X] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
Version : 16.0.14901.20000
Channel : BetaChannel
Name    : Beta
Date    : 1/12/2022
URI     : https://officecdn.microsoft.com/pr/wsus/setup.exe

Version : 16.0.14729.20194
Channel : CurrentPreview
Name    : Current Channel (Preview)
Date    : 1/10/2022
URI     : https://officecdn.microsoft.com/pr/wsus/setup.exe

Version : 16.0.14701.20262
Channel : Current
Name    : Current Channel
Date    : 1/11/2022
URI     : https://officecdn.microsoft.com/pr/wsus/setup.exe

Version : 16.0.14527.20364
Channel : MonthlyEnterprise
Name    : Monthly Enterprise
Date    : 1/11/2022
URI     : https://officecdn.microsoft.com/pr/wsus/setup.exe

Version : 16.0.14332.20176
Channel : PerpetualVL2021
Name    : Office LTSC 2021 Perpetual Enterprise
Date    : 1/11/2022
URI     : https://officecdn.microsoft.com/pr/wsus/setup.exe

Version : 16.0.14326.20702
Channel : SemiAnnualPreview
Name    : Semi-Annual Channel Preview
Date    : 1/11/2022
URI     : https://officecdn.microsoft.com/pr/wsus/setup.exe

Version : 16.0.13801.21092
Channel : SemiAnnual
Name    : Semi-Annual Channel
Date    : 1/11/2022
URI     : https://officecdn.microsoft.com/pr/wsus/setup.exe

Version : 16.0.10382.20010
Channel : PerpetualVL2019
Name    : Office 2029 Perpetual Enterprise
Date    : 1/11/2022
URI     : https://officecdn.microsoft.com/pr/wsus/setup.exe
```

**Comment by aaronparker** [comment]
The response form a request such as `https://mrodevicemgr.officeapps.live.com/mrodevicemgrsvc/api/v2/C2RReleaseData?audienceFFN=64256afe-f5d9-4f86-8936-8840a6a4f5be` returns something like this:

```json
{
  "FFN": "64256afe-f5d9-4f86-8936-8840a6a4f5be",
  "AvailableBuild": "16.0.14827.20122",
  "ThrottleLevel": 1000,
  "LkgBuild": "16.0.14827.20122",
  "ExpiredBuilds": [],
  "Type": "Default",
  "TimestampUtc": "01/19/2022 19:50",
  "Location": "SouthEastAsia",
  "CacheTtlInSec": 300.0
}
```

`Microsoft365Apps` uses the `LkgBuild` property by default to return the version value. Occasionally the `LkgBuild` and `AvailableBuild` values are different.

I'm not 100% sure os the logic behind the value that MS uses as the actual version number for a channel. See: https://github.com/aaronparker/evergreen/blob/8abb1ac17216f333800d3333a2137cac614b0a70/Evergreen/Apps/Get-Microsoft365Apps.ps1#L36

Evergreen will only use the official update API and won't use a GitHub repo, unless that repo is an official source.

**Comment by JonathanPitre** [comment]
I totally understand where your coming from but in that case the GitHub repo is coming from an official source, it's from a Microsoft employee that is responsible for WinGet.

**Comment by aaronparker** [comment]
The repo is owned by the employee, not Microsoft.

**Comment by DanGough** [comment]
Just snooped on https://config.office.com/deploymentsettings, the online tool used to generate Office config files, and found this alternative API, any good?

Invoke-RestMethod -Uri ‘https://clients.config.office.net/releases/v1.0/OfficeReleases’

**Comment by aaronparker** [comment]
Looks good. Nice find.
