### ISSUE TITLE
[New app]: Brave

### ISSUE THREAD

**Issue by hpmillaard** [aaronparker/evergreen#295]
### What is the new application?

Brave Browser
https://github.com/brave/brave-browser

### Vendor site

https://www.brave.com

### Have you reviewed the list of supported applications?

- [X] Supported apps at: https://stealthpuppy.com/evergreen/apps/

**Comment by aaronparker** [comment]
So far I've not been able to reverse engineer how Brave talks to the update server to find the available version.
