### ISSUE TITLE
[New app]: Opera [Stable, Beta, Developer, GX]

### ISSUE THREAD

**Issue by vedantmgoyal2009** [aaronparker/evergreen#299]
### What is the new application?

`https://download.opera.com/download/get/?partner=www&opsys=Windows&product=*&arch=*`

where parameters can be:
- `product = ['Opera', 'Opera+GX', 'Opera+beta', 'Opera+developer']`
- `arch = ['x64', 'i386']`

Also, replace `https://download[x].operacdn.com` with `https://get.geo.opera.com`

For example: 
https://download3.operacdn.com/pub/opera/desktop/83.0.4254.19/win/Opera_83.0.4254.19_Setup.exe to https://get.geo.opera.com/pub/opera/desktop/83.0.4254.19/win/Opera_83.0.4254.19_Setup.exe

If you can find a direct JSON API which I can't, please use that since it would be more reliable than this method.

### Vendor site

https://www.opera.com/

### Have you reviewed the list of supported applications?

- [X] Supported apps at: https://stealthpuppy.com/evergreen/apps/

**Comment by aaronparker** [comment]
If you use Fiddler to capture Opera checking for an update, it might provide something on their update API.

**Comment by vedantmgoyal2009** [comment]
@aaronparker are beta and developer channels added? I'm not on PC right now so can't verify it.

**Comment by aaronparker** [comment]
Not at the moment for `OperaGXBrowser` or `OperaBrowser` - would need to go back and work out the queries for those updates.

**Comment by vedantmgoyal2009** [comment]
@spectershell can you please help in finding APIs for Opera Browser Beta & Dev?

**Comment by vedantmgoyal2009** [comment]
@aaronparker please re-open this so that I remember to post updates, if I could find any.

**Comment by SpecterShell** [comment]
AutoUpdate API
```PowerShell
Invoke-RestMethod -Uri 'https://autoupdate.geo.opera.com/' -Method Post -Body @"
<?xml version="1.0"?>
<autoupdate schema-version="2.2" type="manual" origin="AUScheduledTask">
    <system>
        <platform>
            <opsys>Windows</opsys>
            <opsys-arch>x86_64</opsys-arch>
            <opsys-version>10</opsys-version>
            <arch>i386</arch>
            <package>EXE</package>
        </platform>
    </system>
    <product installer-settings-ro="1">
        <name>Opera</name>
        <version>91.0.4516.19</version>
    </product>
</autoupdate>
"@
```

Downloader (https://net.geo.opera.com/opera/stable/windows) API
https://autoupdate.geo.opera.com/v2/netinstaller/Stable/windows/x64

**Comment by SpecterShell** [comment]
For beta edition:

AutoUpdate API
```PowerShell
Invoke-RestMethod -Uri 'https://autoupdate.geo.opera.com/' -Method Post -Body @"
<?xml version="1.0"?>
<autoupdate schema-version="2.2">
    <system>
        <platform>
            <opsys>Windows</opsys>
            <opsys-arch>x86_64</opsys-arch>
            <opsys-version>10</opsys-version>
            <arch>x64</arch>
            <package>EXE</package>
        </platform>
    </system>
    <product>
        <name>Opera beta</name>
        <version>91.0.4516.09</version>
    </product>
</autoupdate>
"@
```

Downloader (https://net.geo.opera.com/opera/stable/windows) API
https://autoupdate.geo.opera.com/v2/netinstaller/Beta/windows/x64
