### ISSUE TITLE
[Bug]: OBSStudio returns correct version, but wrong Url

### ISSUE THREAD

**Issue by msfreaks** [aaronparker/evergreen#303]
### What happened?

Trying to get the updated version for OBSStudio:

Get-EvergreenApp -Name 'OBSStudio' | Where-Object { $_.Architecture -match 'x64' }

This returns:
Version Architecture URI
------- ------------ ---
27.2.0  x64          https://cdn-fastly.obsproject.com/downloads/OBS-Studio-27.2.0-Full-Installer-x64.exe

This Url throws a 404.
The actual download Url is https://cdn-fastly.obsproject.com/downloads/OBS-Studio-27.2-Full-Installer-x64.exe

### Version

2202.525

### What PowerShell edition/s are you running Evergreen on?

Windows PowerShell

### Which operating system/s are you running Evergreen on?

Windows 10, Windows Server 2016+

### Have you reviewed the documentation?

- [X] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [X] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
VERBOSE: Get-EvergreenApp: Function exists: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2202.525\Apps\Get-OBSStudio.ps1.
VERBOSE: Get-EvergreenApp: Dot sourcing: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2202.525\Apps\Get-OBSStudio.ps1.
VERBOSE: Get-FunctionResource: read application resource strings from [C:\Program Files\WindowsPowerShell\Modules\Evergreen\2202.525\Manifests\OBSStudio.json]
VERBOSE: Get-EvergreenApp: Calling: Get-OBSStudio.
VERBOSE: Invoke-RestMethodWrapper: Invoke-RestMethod parameter: [UseBasicParsing: True].
VERBOSE: Invoke-RestMethodWrapper: Invoke-RestMethod parameter: [MaximumRedirection: 1].
VERBOSE: Invoke-RestMethodWrapper: Invoke-RestMethod parameter: [DisableKeepAlive: True].
VERBOSE: Invoke-RestMethodWrapper: Invoke-RestMethod parameter: [UserAgent: Mozilla/5.0 (Windows NT; Windows NT 10.0; en-NL) AppleWebKit/534.6 (KHTML, like Gecko) Chrome/7.0.500.0 Safari/534.6].
VERBOSE: Invoke-RestMethodWrapper: Invoke-RestMethod parameter: [Method: Default].
VERBOSE: Invoke-RestMethodWrapper: Invoke-RestMethod parameter: [Uri: https://obsproject.com/update_studio/manifest.json].
VERBOSE: Invoke-RestMethodWrapper: Invoke-RestMethod parameter: [ContentType: application/octet-stream].
VERBOSE: GET with 0-byte payload
WARNING: Invoke-RestMethodWrapper: Error at URI: https://obsproject.com/update_studio/manifest.json.
WARNING: Invoke-RestMethodWrapper: Error encountered: The remote server returned an error: (404) Not Found..
WARNING: Invoke-RestMethodWrapper: For troubleshooting steps see: https://stealthpuppy.com/evergreen/troubleshoot/.
```

**Comment by aaronparker** [comment]
I can't get to `https://obsproject.com/update_studio/manifest.json` right now to validate.

Binaries are available on the GitHub repo, so the function could pull from there instead: `https://github.com/obsproject/obs-studio/releases`

**Comment by aaronparker** [comment]
OBSStudio `27.2.4` is released and the downloads are now working.

The function could be updated to skip the minor build number if it equals 0 which might work; however, going through the GitHub repo, they remove older binaries, so this is a guess.
