### ISSUE TITLE
[Bug]: SSMS returns old version

### ISSUE THREAD

**Issue by bmitchell76** [aaronparker/evergreen#305]
### What happened?

Version 18.11 (15.0.18404.0) was released but 15.18386.0 is still returned.

### Version

2202.525

### What PowerShell edition/s are you running Evergreen on?

Windows PowerShell

### Which operating system/s are you running Evergreen on?

Windows Server 2016+

### Have you reviewed the documentation?

- [X] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [X] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
PS C:\> Get-EvergreenApp MicrosoftSsms | Where-Object {$_.Language -eq "English"} -Verbose
WARNING: Get-MicrosoftSsms: Version returned from the update feed: 15.0.18386.0. See
https://stealthpuppy.com/evergreen/issues/ for more information.


Version  : 15.0.18386.0
Date     : 7/7/2021
Title    : Microsoft SQL Server Management Studio
Language : English
URI      : https://download.microsoft.com/download/3/f/d/3fd533f5-fdfc-407d-98a6-d5deb214d13b/SSMS-Setup-ENU.exe
```

**Comment by aaronparker** [comment]
Could you please run [Fiddler](https://www.telerik.com/fiddler/fiddler-classic) to see where the current release of SSMS is sourcing the update XML from when checking for an update, and compare to the XML that you'll see listed when running `Get-EvergreenApp -Name MicrosoftSsms -Verbose`

**Comment by bmitchell76** [comment]
I'm using the link from the documentation
https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15
linking to
https://aka.ms/ssmsfullsetup
resolving to
https://download.microsoft.com/download/a/b/9/ab98886d-bd05-4f28-9768-a8723538a67e/SSMS-Setup-ENU.exe

it looks like the existing Evergreen usings this XML
https://download.microsoft.com/download/1/e/c/1ec92162-142d-4fed-a575-6e2195b65a66/SSMS_PRODUCTRELEASESFEED.xml
