### ISSUE TITLE
[Bug]: VLC release versions not up to date

### ISSUE THREAD

**Issue by JamesKindon** [aaronparker/evergreen#313]
### What happened?

pulling back an older version of VLC - latest here https://www.videolan.org/vlc/download-windows.html

### Version

2112.504

### What PowerShell edition/s are you running Evergreen on?

Windows PowerShell

### Which operating system/s are you running Evergreen on?

Other

### Have you reviewed the documentation?

- [X] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [X] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
(Get-EvergreenApp -Name VideoLanVlcPlayer | Where-Object {$_.Architecture -eq "x64" -and $_.Type -eq "EXE"}).uri

https://mirror.aarnet.edu.au/pub/videolan/vlc/3.0.16/win64/vlc-3.0.16-win64.exe

https://get.videolan.org/vlc/3.0.17.4/win64/vlc-3.0.17.4-win64.exe <- latest
```

**Comment by aaronparker** [comment]
VLC Player itself is still saying 3.0.16 is the latest. This will be something on VLC's end. Also see #154

**Comment by aaronparker** [comment]
Updated the known issues with details: https://stealthpuppy.com/evergreen/issues/#videolanvlcplayer
