### ISSUE TITLE
[Bug]: New source for RStudio

### ISSUE THREAD

**Issue by vedantmgoyal2009** [aaronparker/evergreen#318]
### What happened?

Check here: https://dailies.rstudio.com/json-api/

### Version

2205.541

### What PowerShell edition/s are you running Evergreen on?

PowerShell Core, Windows PowerShell

### Which operating system/s are you running Evergreen on?

Windows 10

### Have you reviewed the documentation?

- [ ] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [ ] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
N/A
```

**Comment by aaronparker** [comment]
Looks to be an issue under PowerShell Core, but it's OK on Windows PowerShell. I'll see what's going on
