### ISSUE TITLE
[Bug]: Mozilla Firefox - Some URLs return 404

### ISSUE THREAD

**Issue by BornToBeRoot** [aaronparker/evergreen#325]
### What happened?

Cmdlet: `Get-EvergreenApp MozillaFirefox` 

This URLs return currently 404:

https://download.mozilla.org/?product=firefox-msi-latest-ssl&os=win64-aarch64&lang=en-US
https://download.mozilla.org/?product=firefox-msix-latest-ssl&os=win64-aarch64&lang=en-US
https://download.mozilla.org/?product=firefox-esr-msix-latest-ssl&os=win64&lang=en-US
https://download.mozilla.org/?product=firefox-esr-msix-latest-ssl&os=win&lang=en-US
https://download.mozilla.org/?product=firefox-esr-msi-latest-ssl&os=win64-aarch64&lang=en-US
https://download.mozilla.org/?product=firefox-esr-msix-latest-ssl&os=win64-aarch64&lang=en-US

I still get some results

![image](https://user-images.githubusercontent.com/16019165/167657390-220e9d0c-03fc-4483-a456-4b3314dd5427.png)

### Version

2205.549

### What PowerShell edition/s are you running Evergreen on?

PowerShell Core, Windows PowerShell

### Which operating system/s are you running Evergreen on?

Windows 10, Other

### Have you reviewed the documentation?

- [X] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [X] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
-/-
```

**Comment by aaronparker** [comment]
This behavious is documented in the known issues: https://stealthpuppy.com/evergreen/issues/#mozillafirefox. 

I've pushed an update to the docs to explain in more detail and provide a workaround.
