### ISSUE TITLE
[New app]: Docker

### ISSUE THREAD

**Issue by MadhuSunke417** [aaronparker/evergreen#332]
### What is the new application?

Docker Desktop for windows

### Vendor site

https://docs.docker.com/desktop/windows/install/

### Have you reviewed the list of supported applications?

- [ ] Supported apps at: https://stealthpuppy.com/evergreen/apps/

**Comment by DanGough** [comment]
FYI I was looking at adding this to Nevergreen, haven’t implemented it yet but have found the detection method… You’re welcome to beat me to it!

App.json in the main app folder points to https://desktop.docker.com/win/main/amd64/appcast.xml. You can Invoke-RestMethod on that and pull out the version and URL.

**Comment by MadhuSunke417** [comment]
`cls
$build = Invoke-RestMethod -UseBasicParsing https://desktop.docker.com/win/main/amd64/appcast.xml | select -ExpandProperty title
$build = (($build.Split(" ")[-1]).trimstart("(")).trimend(")")
$url   = "https://desktop.docker.com/win/main/amd64/BUILD/Docker%20Desktop%20Installer.exe"
$url   = $url -replace "BUILD",$build
$DockerInstaller = Join-Path $Env:Temp 'Docker Desktop Installer.exe'
Invoke-WebRequest -Uri $url -OutFile $DockerInstaller -UseBasicParsing`

**Comment by MadhuSunke417** [comment]
cls
$build = Invoke-RestMethod -UseBasicParsing https://desktop.docker.com/win/main/amd64/appcast.xml | select -ExpandProperty title
$build = (($build.Split(" ")[-1]).trimstart("(")).trimend(")")
$url   = "https://desktop.docker.com/win/main/amd64/BUILD/Docker%20Desktop%20Installer.exe"
$url   = $url -replace "BUILD",$build
$DockerInstaller = Join-Path $Env:Temp 'Docker Desktop Installer.exe'
Invoke-WebRequest -Uri $url -OutFile $DockerInstaller -UseBasicParsing

**Comment by aaronparker** [comment]
Does the version number need any more details than what's listed in the `shortVersionString` property?

```powershell
PS /Users/aaron/projects/evergreen> (irm -uri https://desktop.docker.com/win/main/amd64/appcast.xml).enclosure

url                : {https://desktop.docker.com/win/main/amd64/79419/DockerDesktop.msi,
                     https://desktop.docker.com/win/main/amd64/79419/Docker%20Desktop%20Installer.exe}
version            : 79419
shortVersionString : 4.8.2
length             : 505200584
type               : application/octet-stream
previousBuild      : 77678

PS /Users/aaron/projects/evergreen>
```

**Comment by aaronparker** [comment]
I'd also be included to return the msi file listed there rather than the exe file.

**Comment by aaronparker** [comment]
There's also these updaters returned, but is the MSI enough?

```powershell
PS /Users/aaron/projects/evergreen> (irm -uri https://desktop.docker.com/win/main/amd64/appcast.xml).deltas.enclosure

url                : https://desktop.docker.com/win/main/amd64/79419/Docker%20Desktop%20Updater%2078998.exe
version            : 79419
shortVersionString : 4.8.2
deltaFrom          : 78998
length             : 14031816
type               : application/octet-stream

url                : https://desktop.docker.com/win/main/amd64/79419/Docker%20Desktop%20Updater%2078933.exe
version            : 79419
shortVersionString : 4.8.2
deltaFrom          : 78933
length             : 13995464
type               : application/octet-stream

url                : https://desktop.docker.com/win/main/amd64/79419/Docker%20Desktop%20Updater%2077678.exe
version            : 79419
shortVersionString : 4.8.2
deltaFrom          : 77678
length             : 46390216
type               : application/octet-stream

url                : https://desktop.docker.com/win/main/amd64/79419/Docker%20Desktop%20Updater%2077141.exe
version            : 79419
shortVersionString : 4.8.2
deltaFrom          : 77141
length             : 46356424
type               : application/octet-stream

url                : https://desktop.docker.com/win/main/amd64/79419/Docker%20Desktop%20Updater%2076265.exe
version            : 79419
shortVersionString : 4.8.2
deltaFrom          : 76265
length             : 157534152
type               : application/octet-stream

url                : https://desktop.docker.com/win/main/amd64/79419/Docker%20Desktop%20Updater%2075818.exe
version            : 79419
shortVersionString : 4.8.2
deltaFrom          : 75818
length             : 158760392
type               : application/octet-stream

url                : https://desktop.docker.com/win/main/amd64/79419/Docker%20Desktop%20Updater%2074721.exe
version            : 79419
shortVersionString : 4.8.2
deltaFrom          : 74721
length             : 190734792
type               : application/octet-stream

url                : https://desktop.docker.com/win/main/amd64/79419/Docker%20Desktop%20Updater%2074594.exe
version            : 79419
shortVersionString : 4.8.2
deltaFrom          : 74594
length             : 190862280
type               : application/octet-stream
```

**Comment by MadhuSunke417** [comment]
This is cool @aaronparker . my code looks more confusing and Thx for tip to get URL easily.
