### ISSUE TITLE
[Bug]: SumatraPDF download URLs don't work for latest version (3.4.4)

### ISSUE THREAD

**Issue by blu3id** [aaronparker/evergreen#338]
### What happened?

The `https://kjkpubsf.sfo2.digitaloceanspaces.com` and `https://kjkpub.nyc3.digitaloceanspaces.com` download URLs no longer work.

On https://www.sumatrapdfreader.org/download-free-pdf-viewer the download root has changed to: 
x86: `https://www.sumatrapdfreader.org/dl/rel/#version/SumatraPDF-#version-install.exe`
x64: `https://www.sumatrapdfreader.org/dl/rel/#version/SumatraPDF-#version-64-install.exe`

### Version

2205.567

### What PowerShell edition/s are you running Evergreen on?

Windows PowerShell

### Which operating system/s are you running Evergreen on?

Windows 10

### Have you reviewed the documentation?

- [X] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [X] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
n/a
```

**Comment by blu3id** [comment]
n.b https://www.sumatrapdfreader.org/update-check-rel.txt appears to be running a phased roll out currently so occasionally returns latest version (3.4.4) but mostly returns 3.3.3

**Comment by aaronparker** [comment]
There's a fix in place for this for the latest release; however, this might need some review later if the vendor is chaning URLs around etc.
