### ISSUE TITLE
[New app]: Connection Experience Indicator

### ISSUE THREAD

**Issue by JonathanPitre** [aaronparker/evergreen#342]
### What is the new application?

Tool for RDS, AVD and Windows365 environments that notifies users about changes in the user experience.  It is called the Connection Experience Indicator. This tool does the following:

Support users by pointing out issues that affects the user experience
Reduce the number of help desk calls related to user experience issues
Show notifications about the latency to the virtual desktop. Notify when the latency is good and warn when latency is high or very high
Show notifications about the available bandwidth. Notify when the available bandwidth is good and warn when the available bandwidth is weak or poor
Integrated in the Windows 10 & 11 notification center
Integrated in the taskbar and when you click on the icon a small window will be shown that provides real-time information about the connection to the virtual desktop
Single exe (no installation required) can be easily started with login script or other mechanism
The tool can be configured with parameters so it can be adjusted to your environment (please find all settings below)
Log connection changes in event viewer so they can be used to analyze in, for example, Azure log analytics

### Vendor site

https://bramwolfs.com/2020/03/11/connection-experience-indicator-for-rds-wvd/

### Have you reviewed the list of supported applications?

- [X] Supported apps at: https://stealthpuppy.com/evergreen/apps/

**Comment by aaronparker** [comment]
The app doesn't have an in-built update mechanism that we can piggy back on, and the installer is hosted on a OneDrive link which doesn't expose anything about the application itself, thus we have noting to query for the version number.

**Comment by JonathanPitre** [comment]
let me reach out to Bram Wolfs about this

**Comment by JonathanPitre** [comment]
Bram will provide us a GitHub link shortly :D

**Comment by JonathanPitre** [comment]
Any update on this @bramcw ?

**Comment by bramcw** [comment]
Thanks for the follow up, the connection experience indicator is now available here:

https://github.com/RDAnalyzer/connection-experience-indicator/releases/latest/download/ExperienceIndicator.exe

The same procedure as RDA can be used.
