### ISSUE TITLE
[Change app]: Paint.net

### ISSUE THREAD

**Issue by j81blog** [aaronparker/evergreen#346]
### What is the new application?

Paint.net, the current returns a web installer. There is a msi available on github (i've seen the offline option, but this is maybe a better solution?)
[https://github.com/paintdotnet/release/releases](https://github.com/paintdotnet/release/releases)

### Vendor site

https://www.getpaint.net/

### Have you reviewed the list of supported applications?

- [ ] Supported apps at: https://stealthpuppy.com/evergreen/apps/

**Comment by aaronparker** [comment]
`PaintDotNetOfflineInstaller` already exists.

**Comment by j81blog** [comment]
That will do, thank you
