### ISSUE TITLE
[Bug]: Firefox Errors

### ISSUE THREAD

**Issue by cromaki** [aaronparker/evergreen#367]
### What happened?

![Bildschirmfoto 2022-08-08 um 14 10 03](https://user-images.githubusercontent.com/94054635/183417678-68e3a3b8-915c-43c6-91f8-1313ccffaa4a.png)
![Bildschirmfoto 2022-08-08 um 14 10 11](https://user-images.githubusercontent.com/94054635/183417694-78aa5eee-8171-4749-8fe3-de56c5481a1d.png)

### Version

2208.618

### What PowerShell edition/s are you running Evergreen on?

Windows PowerShell

### Which operating system/s are you running Evergreen on?

Windows Server 2016+

### Have you reviewed the documentation?

- [ ] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [ ] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
Get-EvergreenApp -name mozillafirefox
```

**Comment by aaronparker** [comment]
This is a known issue documented here: https://stealthpuppy.com/evergreen/issues/#errors-and-warnings
