### ISSUE TITLE
[Bug]: VMware Tools don't show the latest installer

### ISSUE THREAD

**Issue by Deyda** [aaronparker/evergreen#374]
### What happened?

The Latest is 12.1.0

https://kb.vmware.com/s/article/86165

### Version

2208.618

### What PowerShell edition/s are you running Evergreen on?

Windows PowerShell

### Which operating system/s are you running Evergreen on?

Windows 10

### Have you reviewed the documentation?

- [X] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [X] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
Get-EvergreenApp -Name vmwareTools

Version Architecture URI
------- ------------ ---
12.0.0  x64          https://packages.vmware.com/tools/releases/12.0.0/windows/x64/VMware-tools-12.0.0-19345655-x86_64.exe
12.0.0  x86          https://packages.vmware.com/tools/releases/12.0.0/windows/x86/VMware-tools-12.0.0-19345655-i386.exe
```

**Comment by aaronparker** [comment]
This is fixed in the latest release. Also see #336
