### ISSUE TITLE
[New app]: Chrome WebDriver, Firefox Gecko Driver

### ISSUE THREAD

**Issue by ThiloLangbeinHUK** [aaronparker/evergreen#375]
### What is the new application?

Chrome Webdriver
Firefox GeckoDriver

### Vendor site

https://chromedriver.chromium.org/downloads, https://github.com/mozilla/geckodriver/releases

### Have you reviewed the list of supported applications?

- [X] Supported apps at: https://stealthpuppy.com/evergreen/apps/

**Comment by ThiloLangbeinHUK** [comment]
👍

**Comment by ThiloL** [comment]
ChromiumChromeDriver seems to have an issue:
![image](https://user-images.githubusercontent.com/2923889/199497742-a031de06-3977-461b-a569-ffa564efda7b.png)

**Comment by aaronparker** [comment]
It's a version mismatch for the `beta` release and is dependent on Chromium matching or publishing the beta driver.

Right now, it's working because Chromium have update the beta channel:

```powershell
PS /Users/aaron/projects/evergreen> Get-EvergreenApp -Name ChromiumChromeDriver

Version       Channel Type URI
-------       ------- ---- ---
108.0.5359.22 beta    zip  https://chromedriver.storage.googleapis.com/108.0.5359.22/chromedriver_win32.zip
107.0.5304.62 stable  zip  https://chromedriver.storage.googleapis.com/107.0.5304.62/chromedriver_win32.zip
```
