### ISSUE TITLE
[Bug]: Zoom Rooms application only offered as 32bit (x86) .exe

### ISSUE THREAD

**Issue by AScott-WWF** [aaronparker/evergreen#377]
### What happened?

The `Get-EvergreenApp -Name Zoom` is only returning the 32bit .exe for the Zoom Rooms app, it does not return the downloads  in .msi format or for the x64 .exe
Using the URI supplied for the 32 bit .exe I have determined (for the current version - 5.11.3.1634) they are available for the following Architectures and Types via the subsequent URLs:
32bit .msi : https://cdn.zoom.us/prod/5.11.3.1634/zoomrooms-5.11.3.1634-x86.msi
64bit .exe : https://cdn.zoom.us/prod/5.11.3.1634/x64/zoomrooms-5.11.3.1634-x64.exe
64bit .msi : https://cdn.zoom.us/prod/5.11.3.1634/x64/zoomrooms-5.11.3.1634-x64.msi

I also note the Zoom Meetings Installer for x64 is also missing (N.B. Client not Admin / 'Full' version)
This I have discoivered, is available here:
https://cdn.zoom.us/prod/5.11.11.8425/x64/ZoomInstaller.exe

I am unsure if the Zoom API is not publishing these URLs or if the code that supplies these URLs needs to be updated?

### Version

2209.622

### What PowerShell edition/s are you running Evergreen on?

Windows PowerShell

### Which operating system/s are you running Evergreen on?

Windows 10

### Have you reviewed the documentation?

- [X] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [X] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
Get-EvergreenApp -Name Zoom | Select-Object Version, Platform, Architecture, URI

Version      Platform Architecture URI
-------      -------- ------------ ---
5.11.11.8425 Meetings x86          https://cdn.zoom.us/prod/5.11.11.8425/ZoomInstaller.exe
5.11.11.8425 Meetings x64          https://cdn.zoom.us/prod/5.11.11.8425/x64/ZoomInstallerFull.exe
5.11.11.8425 Meetings ARM64        https://cdn.zoom.us/prod/5.11.11.8425/arm64/ZoomInstallerFull.exe
5.11.11.8425 Meetings ARM64        https://cdn.zoom.us/prod/5.11.11.8425/arm64/ZoomInstallerFull.msi
5.11.11.8425 Meetings x86          https://cdn.zoom.us/prod/5.11.11.8425/ZoomInstallerFull.msi
5.11.11.8425 Meetings x64          https://cdn.zoom.us/prod/5.11.11.8425/x64/ZoomInstallerFull.msi
5.11.3.1634  Rooms    x86          https://cdn.zoom.us/prod/5.11.3.1634/zoomrooms-5.11.3.1634-x86.exe
5.11.3.564   Plugin   x86          https://cdn.zoom.us/prod/5.11.3.564/ZoomNotesPluginSetup.msi
5.11.3.563   Plugin   x86          https://cdn.zoom.us/prod/5.11.3.563/ZoomOutlookPluginSetup.msi
5.11.0.534   Plugin   x86          https://cdn.zoom.us/prod/5.11.0.534/ZoomLyncPluginSetup.msi
Latest       Citrix   x86          https://cdn.zoom.us/prod/vdi/ZoomCitrixHDXMediaPlugin.msi
Latest       VDI      x86          https://cdn.zoom.us/prod/vdi/ZoomInstallerVDI.msi
Latest       VMware   x86          https://cdn.zoom.us/prod/vdi/ZoomVmwareMediaPlugin.msi
```

**Comment by aaronparker** [comment]
Here's an update pushed to the development branch. What benefit would the `ZoomInstaller.exe` have that the `ZoomInstallerFull.exe` won't provide?

```powershell
Version      Platform Type Architecture URI
-------      -------- ---- ------------ ---
5.11.11.8425 Meetings exe  ARM64        https://cdn.zoom.us/prod/5.11.11.8425/arm64/ZoomInstallerFull.exe
5.11.11.8425 Meetings exe  x86          https://cdn.zoom.us/prod/5.11.11.8425/ZoomInstallerFull.exe
5.11.11.8425 Meetings msi  x86          https://cdn.zoom.us/prod/5.11.11.8425/ZoomInstallerFull.msi
5.11.11.8425 Meetings msi  x64          https://cdn.zoom.us/prod/5.11.11.8425/x64/ZoomInstallerFull.msi
5.11.11.8425 Meetings msi  ARM64        https://cdn.zoom.us/prod/5.11.11.8425/arm64/ZoomInstallerFull.msi
5.11.11.8425 Meetings exe  x64          https://cdn.zoom.us/prod/5.11.11.8425/x64/ZoomInstallerFull.exe
5.11.3.1634  Rooms    msi  x86          https://cdn.zoom.us/prod/5.11.3.1634/zoomrooms-5.11.3.1634-x86.msi
5.11.3.1634  Rooms    exe  x86          https://cdn.zoom.us/prod/5.11.3.1634/zoomrooms-5.11.3.1634-x86.exe
5.11.3.1634  Rooms    msi  x64          https://cdn.zoom.us/prod/5.11.3.1634/x64/zoomrooms-5.11.3.1634-x64.msi
5.11.3.1634  Rooms    exe  x64          https://cdn.zoom.us/prod/5.11.3.1634/x64/zoomrooms-5.11.3.1634-x64.exe
5.11.3.564   Notes    msi  x86          https://cdn.zoom.us/prod/5.11.3.564/ZoomNotesPluginAdminTool.msi
5.11.3.564   Notes    msi  x86          https://cdn.zoom.us/prod/5.11.3.564/ZoomNotesPluginSetup.msi
5.11.3.563   Outlook  msi  x86          https://cdn.zoom.us/prod/5.11.3.563/ZoomOutlookPluginSetup.msi
5.11.0.534   Lync     msi  x86          https://cdn.zoom.us/prod/5.11.0.534/ZoomLyncPluginSetup.msi
Latest       Citrix   msi  x86          https://cdn.zoom.us/prod/vdi/ZoomCitrixHDXMediaPlugin.msi
Latest       VDI      msi  x86          https://cdn.zoom.us/prod/vdi/ZoomInstallerVDI.msi
Latest       VMware   msi  x86          https://cdn.zoom.us/prod/vdi/ZoomVmwareMediaPlugin.msi
```

**Comment by AScott-WWF** [comment]
Fantastic.

With regards to the `ZoomInstaller.exe` vs `ZoomInstallerFull.exe` - IMHO not any benefit for widescale distribution as the `ZoomInstallerFull.exe` contains a wider set of features usually required for mass deployment, `ZoomInstaller.exe` appears to be a cut down end / guest users installation.

This Reddit discussion details some of the differences: [https://www.reddit.com/r/Zoom/comments/v4dnn5/whats_difference_between_zoominstallerfullexe_and/](https://www.reddit.com/r/Zoom/comments/v4dnn5/whats_difference_between_zoominstallerfullexe_and/)

> ZoomInstaller.exe is the minimum needed to get Zoom meetings working and is the default download if you try to join a meeting and don't have Zoom installed.
> It does not include ringtones and several other features which will be installed on demand.
> 
> ZoomInstallerFull.exe includes all files including rintones, airhost, av codecs etc.
