### ISSUE TITLE
[New app]: CrystalDiskMark

### ISSUE THREAD

**Issue by JonathanPitre** [aaronparker/evergreen#380]
### What is the new application?

CrystalDiskMark is a simple disk benchmark software.

### Vendor site

https://crystalmark.info/en/download/#CrystalDiskMark

### Have you reviewed the list of supported applications?

- [X] Supported apps at: https://stealthpuppy.com/evergreen/apps/

**Comment by aaronparker** [comment]
As far as I can tell there's no URL or API to find the latest version number.
