### ISSUE TITLE
[New app]: Oracle JDKs/JREs

### ISSUE THREAD

**Issue by vedantmgoyal2009** [aaronparker/evergreen#381]
### What is the new application?

https://www.oracle.com/java/technologies/jdk-script-friendly-urls/

### Vendor site

https://www.oracle.com/java

### Have you reviewed the list of supported applications?

- [X] Supported apps at: https://stealthpuppy.com/evergreen/apps/

**Comment by aaronparker** [comment]
It appears that the JREs no longer include an update component, so finding the version number 

Java 1.8 uses this, but I can't find anything similar for Java 17 or 18: https://javadl-esd-secure.oracle.com/update/1.8.0/map-m-1.8.0.xml

**Comment by vedantmgoyal2009** [comment]
https://www.oracle.com/java/technologies/jdk-script-friendly-urls/

**Comment by aaronparker** [comment]
The URLs are OK - there's nothing to return a version number (e.g. 18.0.2.1) though.

**Comment by vedantmgoyal2009** [comment]
We can scrape them from Download URLs.

**Comment by aaronparker** [comment]
The URL will only provide the major version number - e.g. https://download.oracle.com/java/18/latest/jdk-18_windows-x64_bin.msi. The current v18 release is `18.0.2.1` which that URL won't return.

There's nothing in the headers for the URL either. No way that I can see so far to return a version number like `18.0.2.1`.

**Comment by vedantmgoyal2009** [comment]
I'll talk to oracle support and see if they can give any API for our use.

**Comment by aaronparker** [comment]
Found this: https://www.java.com/releases/releases.json
