### ISSUE TITLE
[New app]: Adobe Connect

### ISSUE THREAD

**Issue by vedantmgoyal2009** [aaronparker/evergreen#382]
### What is the new application?

https://helpx.adobe.com/adobe-connect/connect-downloads-updates.html

### Vendor site

https://adobe.com/

### Have you reviewed the list of supported applications?

- [X] Supported apps at: https://stealthpuppy.com/evergreen/apps/

**Comment by aaronparker** [comment]
There doesn't appear to be any update URL to query to find the version number for this. The app also requires a sign-in, so difficult to take it further to see where the app looks for updates.

**Comment by vedantmgoyal2009** [comment]
There are permanent URLs which redirect to version-specific URLs. Once we get the version-specific URL, we can scrape the version number from it.

**Comment by aaronparker** [comment]
They resolve to something like https://download.adobe.com/pub/connect/updaters/meeting/11_0/ConnectApp11_2022_7_183.msi, so some RegEx required to get to `2022.7.183`

**Comment by vedantmgoyal2009** [comment]
Yeah, correct.
