### ISSUE TITLE
Get-NotepadPlusPlus returns old version

### ISSUE THREAD

**Issue by msfreaks** [aaronparker/Evergreen#39]
**Describe the bug**
Get-NotepadPlusPlus returns old version

**To Reproduce**
1. Get-NotepadPlusPlus
Returns:
Version Architecture URI
------- ------------ ---
7.8.1   x86          http://download.notepad-plus-plus.org/repository/7.x/7.8.1/npp.7.8.1.Installer.exe    
7.8.1   x64          http://download.notepad-plus-plus.org/repository/7.x/7.8.1/npp.7.8.1.Installer.x64.exe

While as of writing the newest version is 7.8.4

**Comment by aaronparker** [comment]
Will move this function to query the Notepad++ repo on GitHub so that we don't have an issue with the updater returning an old version.

**Comment by aaronparker** [comment]
Fixed in 0a5712cda343348d4c17d3a57c18fe9d466dbc68

**Comment by msfreaks** [comment]
Thanks!
