### ISSUE TITLE
Microsoft changed the FSLogix Apps download link, again.

### ISSUE THREAD

**Issue by aaronparker** [aaronparker/evergreen#403]
https://github.com/aaronparker/evergreen/blob/74214d5d90462d14e3bf750a7c3b68d240979c19/Evergreen/Manifests/MicrosoftFSLogixApps.json#L7

Install link has change to https://aka.ms/fslogix-latest, which points to a downloads page and breaks this app again.

**Comment by JonathanPitre** [comment]
They also changed their public preview link, I ended up writing some code to get it but since it's a preview version and we both know they'll change again next month I didn't bother you with it!

Seriously Microsoft stop breaking out automation!
