### ISSUE TITLE
[New app]: NPGSQL

### ISSUE THREAD

**Issue by j81blog** [aaronparker/evergreen#411]
### What is the new application?

Npgsql is the .NET data provider for PostgreSQL

https://github.com/npgsql/npgsql/releases
https://www.npgsql.org/doc/installation.html

### Vendor site

https://github.com/npgsql/npgsql/releases

### Have you reviewed the list of supported applications?

- [X] Supported apps at: https://stealthpuppy.com/evergreen/apps/

### Does the vendor require a sign-in?

No

**Comment by aaronparker** [comment]
There's doesn't appear to be an EXE/MSI installer for this - the install is via a NuGet package.
