### ISSUE TITLE
[Bug]: Get-MicrosoftWvdMultimediaRedirection: Failed to return a header from https://aka.ms/avdmmr/msi.

### ISSUE THREAD

**Issue by JonathanPitre** [aaronparker/evergreen#418]
### What happened?

The download link is still valid but the setup name changed to MsMmrHostMsi%Version%.msi.

### Version

2211.686

### What PowerShell edition/s are you running Evergreen on?

Windows PowerShell

### Which operating system/s are you running Evergreen on?

Windows 10

### Have you reviewed the documentation?

- [X] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [X] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
WARNING: Invoke-WebRequestWrapper: Error at URI: https://aka.ms/avdmmr/msi.
WARNING: Invoke-WebRequestWrapper: Error encountered: The remote server returned an error: (503) Server Unavailable..
WARNING: Invoke-WebRequestWrapper: For troubleshooting steps see: https://stealthpuppy.com/evergreen/troubleshoot/.
WARNING: Get-MicrosoftWvdMultimediaRedirection: Failed to return a header from https://aka.ms/avdmmr/msi.
```

**Comment by JonathanPitre** [comment]
Also it would be great to rename all "Wvd" apps to "Avd".

**Comment by aaronparker** [comment]
Microsoft has changed the installer filename making it hard to determine the version number. I've updated the function to return this

```powershell
WARNING: Get-MicrosoftWvdMultimediaRedirection: Unable to determine a version number from "inline; filename=MsMmrHostMsi101322.msi".

Version      : 101322
Architecture : x86
Date         : Thu, 13 Oct 2022 19:04:54 GMT
Size         : 970752
Filename     : MsMmrHostMsi101322.msi
URI          : https://aka.ms/avdmmr/msi
```

**Comment by aaronparker** [comment]
I'd prefer to leave the name as-is so as not to break people's scripts unnecessarily

**Comment by JonathanPitre** [comment]
fair enough
