### ISSUE TITLE
[Bug]: Remote Name could not be resolved

### ISSUE THREAD

**Issue by ritschido** [aaronparker/evergreen#420]
### What happened?

Hello,

since a few days all MDT / Evergreen packages fail. Allegedly the DNS name can not be resolved. Has anyone else observed the problem, we are now at a loss.

### Version

2211.686

### What PowerShell edition/s are you running Evergreen on?

Windows PowerShell

### Which operating system/s are you running Evergreen on?

Windows Server 2016+

### Have you reviewed the documentation?

- [X] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [X] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
PS>TerminatingError(Invoke-RestMethod): "Der Remotename konnte nicht aufgelöst werden: 'api.github.com'"
WARNUNG: Invoke-RestMethodWrapper: Error at URI: https://api.github.com/rate_limit.
WARNUNG: Invoke-RestMethodWrapper: Error encountered: Der Remotename konnte nicht aufgelöst werden: 'api.github.com'.
WARNUNG: Invoke-RestMethodWrapper: For troubleshooting steps see: https://stealthpuppy.com/evergreen/troubleshoot/.
Invoke-RestMethodWrapper : Invoke-RestMethodWrapper: Der Remotename konnte nicht aufgelöst werden: 'api.github.com'.
In C:\Program Files\WindowsPowerShell\Modules\Evergreen\2211.686\Private\Get-GitHubRepoRelease.ps1:58 Zeichen:23
+         $GitHubRate = Invoke-RestMethodWrapper @params
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-RestMethodWrapper
Invoke-RestMethodWrapper : Invoke-RestMethodWrapper: Der Remotename konnte nicht aufgelöst
werden: 'api.github.com'.
In C:\Program
Files\WindowsPowerShell\Modules\Evergreen\2211.686\Private\Get-GitHubRepoRelease.ps1:58 Zeichen:23
+         $GitHubRate = Invoke-RestMethodWrapper @params
```

**Comment by aaronparker** [comment]
Which app or apps are you querying for?

**Comment by ritschido** [comment]
Sorry for the late reply, the requests randomly fail. There are always the apps: 7Zip, QTranslate, VLC

**Comment by aaronparker** [comment]
QTranslate? This isn't an app that's supported by Evergreen.

**Comment by aaronparker** [comment]
Are running scripts with Evergreen behind a proxy server? Are you using anything like pi-hole that might block hosts? This sounds like a local network issue rather than something to do with Evergreen directly.

When an error or warning is thrown (if you don't see anything use the `-Verbose` switch), you should see which host it's having issues with. Double check that you can resolve those hosts either ping or in the browser.
