### ISSUE TITLE
[Bug]: Total Commander returns broken links

### ISSUE THREAD

**Issue by rweijnen** [aaronparker/evergreen#423]
### What happened?

Invoke-WebRequest -Uri (Get-EvergreenApp -Name 'GhislerTotalCommander' | where {$_.Architecture -eq 'x86'} | select -ExpandProperty Uri)

404 Not Found

Invoke-WebRequest -Uri (Get-EvergreenApp -Name 'GhislerTotalCommander' | where {$_.Architecture -eq 'x'64} | select -ExpandProperty Uri)

404 Not Found

### Version

2211.697

### What PowerShell edition/s are you running Evergreen on?

Windows PowerShell

### Which operating system/s are you running Evergreen on?

Windows Server 2016+

### Have you reviewed the documentation?

- [ ] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [X] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
Invoke-WebRequest -Uri (Get-EvergreenApp -Name 'GhislerTotalCommander' | where {$_.Architecture -eq 'x86'} | select -ExpandProperty Uri -Verbose) -Verbose
VERBOSE: GET https://totalcommander.ch/win/tcmd1010520x32.exe with 0-byte payload
Invoke-WebRequest : <HTML>
<HEAD>
<TITLE>404 Not Found</TITLE>
<BASE href="/error_docs/"><!--[if lte IE 6]></BASE><![endif]-->
</HEAD>
<BODY>
<H1>Not Found</H1>
The requested document was not found on this server.
<P>
<HR>
<ADDRESS>
Web Server at totalcommander.ch
</ADDRESS>
</BODY>
</HTML>
```

**Comment by aaronparker** [comment]
This uses a DNS TXT lookup, and the record value doesn't match the filename.

```log
id 64732, opcode QUERY, rcode NOERROR, flags QR RD RA
;QUESTION
releaseversion.ghisler.com. IN TXT
;ANSWER
releaseversion.ghisler.com. 714 IN TXT "10.10.52.0;1"
;AUTHORITY
;ADDITIONAL
```

**Comment by rweijnen** [comment]
From the author:

```
The TXT record does not report the file name, it reports the version
like an IP address with the following meaning:
"10.10.52.0;1"
10 always 10, to use the private address range 10.x.x.x
10 major version
52 minor version
0 flags: 0=nothing, 1=a, 2=b or 0x81=beta 1, 0x82=beta 2 etc;0x80+101=RC1 etc, 0x80+121=aRC1..aRC6
;1 re-check every 1 day
```
