### ISSUE TITLE
[Bug]: Weird issue with Adobe Updates

### ISSUE THREAD

**Issue by BronsonMagnan** [aaronparker/evergreen#425]
### What happened?

`PS W:\Evergreen> Find-EvergreenApp -Name AdobeAcrobat | ? name -eq "AdobeAcrobat" | Get-EvergreenApp | ? Type -eq Update | ? architecture -eq x64 | ? product -eq "Acrobat" 

Version      : 22.003.20281
Type         : Update
Product      : Acrobat
Track        : DC
Language     : Neutral
Architecture : x64
URI          : https://ardownload2.adobe.com/pub/adobe/acrobat/win/AcrobatDC/2200320281/AcrobatDCx64Upd2200320281.msp `

[https://www.adobe.com/devnet-docs/acrobatetk/tools/ReleaseNotesDC/continuous/dccontinuousnov2022.html#dccontinuousnovtwentytwentytwo](Actual update page)

The actual windows update is 22.003.20282
20281 is the Mac OS update

Not quite sure why this is happening.

### Version

Current

### What PowerShell edition/s are you running Evergreen on?

Windows PowerShell

### Which operating system/s are you running Evergreen on?

Windows Server 2016+

### Have you reviewed the documentation?

- [X] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [X] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
`PS W:\Evergreen> Find-EvergreenApp -Name AdobeAcrobat | ? name -eq "AdobeAcrobat" | Get-EvergreenApp | ? Type -eq Update | ? architecture -eq x64 | ? product -eq "Acrobat" 


Version      : 22.003.20281
Type         : Update
Product      : Acrobat
Track        : DC
Language     : Neutral
Architecture : x64
URI          : https://ardownload2.adobe.com/pub/adobe/acrobat/win/AcrobatDC/2200320281/AcrobatDCx64Upd2200320281.msp`
```

**Comment by aaronparker** [comment]
See the known issue here: https://stealthpuppy.com/evergreen/issues/#adobeacrobat. Use `AdobeAcrobatDC` instead. `AdobeAcrobat` has been left in the module to cover the previous versions.
