### ISSUE TITLE
[Bug]: MicrosoftEdgeWebview2Runtime - version issue?

### ISSUE THREAD

**Issue by jamies151** [aaronparker/evergreen#426]
### What happened?

The version of the MicrosoftEdgeWebview2Runtime that evergreen returns is 108.0.1462.42.
This is actually the latest version of the MS Edge web browser.

The latest version of the Webview2 runtime is 107.0.1418.62.

### Version

2211.697

### What PowerShell edition/s are you running Evergreen on?

Windows PowerShell

### Which operating system/s are you running Evergreen on?

Windows 10

### Have you reviewed the documentation?

- [X] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [X] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
PS C:\WINDOWS\system32> get-evergreenapp -name MicrosoftEdgeWebView2Runtime | Where-Object { $_.architecture -eq "x64"}

Version       Channel Architecture URI                                                                                                                                                        
-------       ------- ------------ ---                                                                                                                                                        
108.0.1462.42 Stable  x64          https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/2e074d72-684e-49e9-9c23-7ced6291e94f/MicrosoftEdgeWebView2RuntimeInstallerX64.exe
```

**Comment by aaronparker** [comment]
Microsoft has updated the source and the versions match now.

**Comment by DW-42** [comment]
IMHO, this issue can be closed. I have not been able to replicate the issue and consistently get the expected version.
