### ISSUE TITLE
[Bug]: FileZilla won't download

### ISSUE THREAD

**Issue by johneijg** [aaronparker/evergreen#437]
### What happened?

When executing the following command;
Get-EvergreenApp -Name FileZilla | Save-EvergreenApp -Path C:\Temp

The following error is returned;
Save-EvergreenApp : Download failed: https://download.filezilla-project.org/client/FileZilla_3.62.2_win64-setup.exe
At line:1 char:36
+ Get-EvergreenApp -Name FileZilla | Save-EvergreenApp -Path C:\Temp
+                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Save-EvergreenApp
 
Save-EvergreenApp : Error: The remote server returned an error: (403) Forbidden.
At line:1 char:36
+ Get-EvergreenApp -Name FileZilla | Save-EvergreenApp -Path C:\Temp
+                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Save-EvergreenApp

### Version

2212.704

### What PowerShell edition/s are you running Evergreen on?

Windows PowerShell

### Which operating system/s are you running Evergreen on?

Windows 10

### Have you reviewed the documentation?

- [X] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [X] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
PS C:\WINDOWS\system32> Get-EvergreenApp -Name FileZilla -Verbose
VERBOSE: Function path: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2210.676\Apps\Get-FileZilla.ps1
VERBOSE: Function exists: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2210.676\Apps\Get-FileZilla.ps1.
VERBOSE: Dot sourcing: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2210.676\Apps\Get-FileZilla.ps1.
VERBOSE: Get-FunctionResource: read application resource strings from [C:\Program Files\WindowsPowerShell\Modules\Evergreen\2210.676\Manifests\FileZilla.json]
VERBOSE: Calling: Get-FileZilla.
VERBOSE: Invoke-WebRequestWrapper: Creating class TrustAllCertsPolicy.
VERBOSE: Invoke-WebRequestWrapper: Using temp file C:\Users\nljei\AppData\Local\Temp\tmp7CD9.tmp.
VERBOSE: Invoke-WebRequestWrapper: Invoke-WebRequest parameter: [UserAgent: FileZilla/3.47.2.1].
VERBOSE: Invoke-WebRequestWrapper: Invoke-WebRequest parameter: [UseBasicParsing: True].
VERBOSE: Invoke-WebRequestWrapper: Invoke-WebRequest parameter: [Method: Default].
VERBOSE: Invoke-WebRequestWrapper: Invoke-WebRequest parameter: [Uri: https://update.filezilla-project.org/update.php?initial=0&manual=1&osarch=64&osversion=10.0&package=1&platform=x86_64-w64-mingw32&updated=0&version=3.47.2.1].
VERBOSE: Invoke-WebRequestWrapper: Invoke-WebRequest parameter: [PassThru: True].
VERBOSE: Invoke-WebRequestWrapper: Invoke-WebRequest parameter: [OutFile: C:\Users\nljei\AppData\Local\Temp\tmp7CD9.tmp].
VERBOSE: GET with 0-byte payload
VERBOSE: received -1-byte response of content type text/plain;charset=UTF-8
VERBOSE: Invoke-WebRequestWrapper: Response: [200].
VERBOSE: Invoke-WebRequestWrapper: Content type: [text/plain;charset=UTF-8].
VERBOSE: Invoke-WebRequestWrapper: Returning content of length: [260].
VERBOSE: Performing the operation "Return output" on target "C:\Program Files\WindowsPowerShell\Modules\Evergreen\2210.676\Apps\Get-FileZilla.ps1".
VERBOSE: Output result from: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2210.676\Apps\Get-FileZilla.ps1.
```

**Comment by aaronparker** [comment]
Cross reference with #436

**Comment by aaronparker** [comment]
`-UserAgent` parameter added to `Save-EvergreenApp` with a default user agent. This works for downloading FileZilla
