### ISSUE TITLE
[Bug]: OBSStudio returns incorrect download URI for OBS releases with patch versions of 0

### ISSUE THREAD

**Issue by blu3id** [aaronparker/evergreen#445]
### What happened?

The download URI returned for the current release of OBS is incorrect because OBS only use `major.minor` version numbers (e.g 29.0) on binary releases when the patch version is equal to 0.

Evergreen returns a URI of: `https://cdn-fastly.obsproject.com/downloads/OBS-Studio-29.0.0-Full-Installer-x86.exe` but checking on the OBS website the correct URI is: `https://cdn-fastly.obsproject.com/downloads/OBS-Studio-29.0-Full-Installer-x64.exe`

While this is an edge case I don't think this is unique to this release as if you review the assets on previous release e.g https://github.com/obsproject/obs-studio/releases/tag/28.1.0 the binaries follow a similar pattern of omitting the patch version using only `major.minor`

### Version

2301.717

### What PowerShell edition/s are you running Evergreen on?

Windows PowerShell

### Which operating system/s are you running Evergreen on?

Windows 10

### Have you reviewed the documentation?

- [X] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [X] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
n/a
```

**Comment by aaronparker** [comment]
Looking good; however, the x86 version link looks to be unavailable:

```powershell
PS /Users/aaron/projects/evergreen> Get-EvergreenApp -Name "OBSStudio"

Version Architecture URI
------- ------------ ---
29.0    x64          https://cdn-fastly.obsproject.com/downloads/OBS-Studio-29.0-Full-Installer-x64.exe
29.0    x86          https://cdn-fastly.obsproject.com/downloads/OBS-Studio-29.0-Full-Installer-x86.exe

PS /Users/aaron/projects/evergreen> Get-EvergreenApp -Name "OBSStudio" | Test-EvergreenApp

Result URI
------ ---
  True https://cdn-fastly.obsproject.com/downloads/OBS-Studio-29.0-Full-Installer-x64.exe
 False https://cdn-fastly.obsproject.com/downloads/OBS-Studio-29.0-Full-Installer-x86.exe
```

**Comment by aaronparker** [comment]
Looks like the `x86` installer is no longer available, so we could remove that.

**Comment by blu3id** [comment]
Good spot missed that. Have added further PR removing architecture from manifest as the "least restrictive" option making it easy to add back if x86 becomes available again or if (more likely) another architecture is added e.g ARM. Downside is leaves currently unneeded ForEach loop in Get-OBSStudio.ps1
