### ISSUE TITLE
[Bug]: MicrosoftOutlook

### ISSUE THREAD

**Issue by TRiebesel** [aaronparker/evergreen#465]
### What happened?

Hello, when i do a Invoke-RestMethod -Uri "https://evergreen-api.stealthpuppy.com/apps" to the webapi I got a wrong Application and Link for Microsoft Outlook. The Application is "Microsoft Teams" and the Link is "https://www.microsoft.com/teams"

Thanks
Tobias

### Version

WebApi

### What PowerShell edition/s are you running Evergreen on?

Windows PowerShell

### Which operating system/s are you running Evergreen on?

Windows 10

### Have you reviewed the documentation?

- [X] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [X] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
Invoke-RestMethod -Uri "https://evergreen-api.stealthpuppy.com/apps"
MicrosoftOutlook                      Microsoft Teams                                                   https://www.microsoft.com/teams
MicrosoftPowerShell                   Microsoft PowerShell                                              https://docs.microsoft.com/powershell/
MicrosoftPowerToys                    Microsoft PowerToys                                               https://github.com/microsoft/PowerToys/
MicrosoftSsms                         Microsoft SQL Server Management Studio                            https://go.microsoft.com/fwlink/?LinkId=531355
MicrosoftTeams                        Microsoft Teams                                                   https://www.microsoft.com/teams
MicrosoftTerminal                     Microsoft Terminal                                                https://github.com/microsoft/terminal/
```

**Comment by aaronparker** [comment]
Incorrect information in the manifest https://github.com/aaronparker/evergreen/blob/main/Evergreen/Manifests/MicrosoftOutlook.json. I'll have to update the manifest - the API will be updated when the module is updated with a new release
