### ISSUE TITLE
[Feature]: Add Teams 2.0 release

### ISSUE THREAD

**Issue by JonathanPitre** [aaronparker/evergreen#477]
### What is your feature request?

Add Teams 2.0 (msix) to Get-MicrosoftTeams command.

The build number and download URL can be obtained here.
https://github.com/ItzLevvie/MicrosoftTeams-msinternal/blob/master/defconfig2

![image](https://user-images.githubusercontent.com/15003329/228288805-b79a88a7-1b4b-4f36-9a12-155f97a6167f.png)

### Have you tested against the current version?

- [X] Yes, I've updated Evergreen and tested against the current version.

### Have you reviewed the documentation?

- [X] Documentation at: https://stealthpuppy.com/evergreen/

**Comment by ItzLevvie** [comment]
Teams 2.0 is the consumer / personal version.
Teams 2.1 is the enterprise / work version.

Details on how to fetch these builds — without needing to parse the defconfig2 file — can be done through a GET request to the Microsoft Teams Flighting API such as https://config.teams.microsoft.com/config/v1/MicrosoftTeams/1415_1.0.0.0?environment=prod&audienceGroup=general&teamsRing=general&agent=TeamsBuilds

This API will include the build version and build URL and various architectures such as x64, x86, & arm64.

An example of how to use the API has been provided at https://github.com/ItzLevvie/MicrosoftTeams-msinternal#how-to-use-the-api

**Comment by aaronparker** [comment]
@ItzLevvie thank-you

**Comment by aaronparker** [comment]
Added in [v2304.791](https://github.com/aaronparker/evergreen/tree/v2304.791)
