### ISSUE TITLE
[New app]: Google Drive File Stream

### ISSUE THREAD

**Issue by derik0709** [aaronparker/evergreen#480]
### What is the new application?

This is an enterprise application to sync files stored on Google Drive to a users device. They have a static URL for downloading. 

https://dl.google.com/drive-file-stream/GoogleDriveFSSetup.exe

### Vendor site

https://support.google.com/drive/answer/7329379?sjid=11325934326792069646-NA

### Have you reviewed the list of supported applications?

- [X] Supported apps at: https://stealthpuppy.com/evergreen/apps/

### Does the vendor require a sign-in?

No

**Comment by DanGough** [comment]
FYI here's how I implemented it in Nevergreen, using Fiddler to capture the auto updater traffic:

`$Response = (Invoke-RestMethod -Uri 'https://update.googleapis.com/service/update2' -Method Post -DisableKeepAlive -Body '<?xml version="1.0" encoding="UTF-8"?><request protocol="3.0" updaterversion="1.3.36.82"><app appid="{6BBAE539-2232-434A-A4E5-9A33560C6283}"><updatecheck/></app></request>').response

$Version = $Response.app.updatecheck.manifest.version

$URL = @($Response.app.updatecheck.urls.url.codebase)[-1] + $Response.app.updatecheck.manifest.packages.package.name

$SHA256 = $Response.app.updatecheck.manifest.packages.package.hash_sha256`

**Comment by aaronparker** [comment]
Adding some working code here for later:

```powershell
# Google
$params = @{
    Uri              = 'https://update.googleapis.com/service/update2'
    Method           = "Post"
    DisableKeepAlive = $true
    Body             = '<?xml version="1.0" encoding="UTF-8"?><request protocol="3.0" updaterversion="1.3.36.82"><app appid="{6BBAE539-2232-434A-A4E5-9A33560C6283}"><updatecheck/></app></request>'
}
Invoke-RestMethod @params
$Version = $Response.response.app.updatecheck.manifest.version
$URL = @($Response.response.app.updatecheck.urls.url.codebase)[-1] + $Response.app.updatecheck.manifest.packages.package.name
$SHA256 = $Response.response.app.updatecheck.manifest.packages.package.hash_sha256
```
