### ISSUE TITLE
[Feature]: MS OneDrive

### ISSUE THREAD

**Issue by Mohrpheus78** [aaronparker/evergreen#481]
### What is your feature request?

Evergreen returns the version for OneDrive in another format as the version after the app is installed. It's difficult to compare the two version formats while checking if a new version has to be installed. 
Evergreen: 23.71.402.1
OneDrive app: 23.071.0402.0001
Can you please use the same format?

### Have you tested against the current version?

- [X] Yes, I've updated Evergreen and tested against the current version.

### Have you reviewed the documentation?

- [x] Documentation at: https://stealthpuppy.com/evergreen/

**Comment by aaronparker** [comment]
I don't think Evergreen has ever returned a version number for OneDrive. The version number returned by Evergreen is what comes out of the OneDrive update API.

```powershell
PS E:\> Get-EvergreenApp -Name MicrosoftOneDrive | Where-Object { $_.Architecture -eq "AMD64" -and $_.Ring -eq "Production" } | Select-Object -First 1


Version      : 23.071.0402.0001
Architecture : AMD64
Ring         : Production
Sha256       : 1G+8wt3QwG4It2pq2NmuScwxPg1SW6ZAWtDO15ag/rs=
Type         : exe
URI          : https://oneclient.sfx.ms/Win/Installers/23.071.0402.0001/amd64/OneDriveSetup.exe
```

**Comment by aaronparker** [comment]
> I don't think Evergreen has ever returned a version number for OneDrive in that format. The version number returned by Evergreen is what comes out of the OneDrive update API.
> 
> ```powershell
> PS E:\> Get-EvergreenApp -Name MicrosoftOneDrive | Where-Object { $_.Architecture -eq "AMD64" -and $_.Ring -eq "Production" } | Select-Object -First 1
> 
> 
> Version      : 23.071.0402.0001
> Architecture : AMD64
> Ring         : Production
> Sha256       : 1G+8wt3QwG4It2pq2NmuScwxPg1SW6ZAWtDO15ag/rs=
> Type         : exe
> URI          : https://oneclient.sfx.ms/Win/Installers/23.071.0402.0001/amd64/OneDriveSetup.exe
> ```
