### ISSUE TITLE
Oracle Java JDK 17

### ISSUE THREAD

**Issue by bmitchell76** [aaronparker/evergreen#482]
### What is the new application?

https://www.oracle.com/java/technologies/downloads/#java17

### Vendor site

https://www.oracle.com/java/technologies/downloads/#java17

### Have you reviewed the list of supported applications?

- [X] Supported apps at: https://stealthpuppy.com/evergreen/apps/

### Does the vendor require a sign-in?

No

**Comment by aaronparker** [comment]
I can't find an automatic update feed for Java 20+ (or anything after Java 8)

**Comment by bmitchell76** [comment]
Unfortunately, I'm seeing the same, better suited for Nevergreen.
