### ISSUE TITLE
[New app]: MySQL products (Server, Workbench, Connector, etc.)

### ISSUE THREAD

**Issue by BornToBeRoot** [aaronparker/evergreen#499]
### What is the new application?

For e.g. the Workbench:

The download links looks like this:
https://dev.mysql.com/get/Downloads/MySQLGUITools/mysql-workbench-community-8.0.33-winx64.msi

Maybe we can match the Tags from the repo:
https://github.com/mysql/mysql-workbench/releases/tag/8.0.33

### Vendor site

https://github.com/mysql

### Have you reviewed the list of supported applications?

- [X] Supported apps at: https://stealthpuppy.com/evergreen/apps/

### Does the vendor require a sign-in?

No

**Comment by aaronparker** [comment]
I've added `mySQLWorkbench`; however, it's going to be a challenge to download the file as attempting to download without a referral from the mysql site, results in an invalid HTTP response
