### ISSUE TITLE
[New app]: Adobe Digital Editions

### ISSUE THREAD

**Issue by alexandret72** [aaronparker/evergreen#504]
### What is the new application?

Adobe Digital Editions (abbreviated ADE) is an e-book reader software program from Adobe Systems. It is used for acquiring, managing, and reading e-books, digital newspapers, and other digital publications. 

### Vendor site

https://www.adobe.com/solutions/ebook/digital-editions/release-notes.html

### Have you reviewed the list of supported applications?

- [X] Supported apps at: https://stealthpuppy.com/evergreen/apps/

### Does the vendor require a sign-in?

No

**Comment by aaronparker** [comment]
There's no method to dynamically determine the application version, so it's not suitable for Evergreen. If you want to use Digital Editions in Evergreen, you an use code similar to the following:

```powershell
[PSCustomObject]@{
        Version = "4.5.11"
        URI = "https://adedownload.adobe.com/pub/adobe/digitaleditions/ADE_4.5_Installer.exe"
} | Save-EvergreenApp -Path "E:\Temp"
```
