### ISSUE TITLE
function Get-MicrosoftEdge no longer returns x64 versions

### ISSUE THREAD

**Issue by msfreaks** [aaronparker/Evergreen#51]
**Describe the bug**
The latest version for function Get-MicrosoftEdge no longer returns x64 versions

**To Reproduce**
Get-MicrosoftEdge | Where-Object {$_.Release -like "enterprise" -and $_.Channel -like "stable"}

**Expected behavior**
Return x86 and x64 objects

**Screenshots**
![image](https://user-images.githubusercontent.com/17710654/81060829-90fd8980-8ed3-11ea-8881-29127af202bd.png)

**Desktop (please complete the following information):**
 - OS: 2019LTSC_CORE
 - Module Version: 2005.176.0

**Additional context**
The x86 version that is return seems to be a very old version as well:
Version      : 79.0.309.65
Platform     : Windows
Channel      : Stable
Release      : Enterprise
Architecture : x86
Date         : 2020-01-13T22:11:00
Hash         : 8A97FF8F247354A6B62CF0FE0347EBA296B08836F0C6D07000F40A956889158C
URI          : http://dl.delivery.mp.microsoft.com/filestreamingservice/files/f9658d03-0e86-45c3-9259-8c5d3795f41d/MicrosoftEdgeEnterpriseX86.msi

**Comment by msfreaks** [comment]
Please ignore

Was probably running an older version in my container.
![image](https://user-images.githubusercontent.com/17710654/81064161-79c19a80-8ed9-11ea-90a0-dfdd7a4045bc.png)

**Comment by aaronparker** [comment]
Yeah, found an issue and had to fix 24 hours later. Latest version returns the right releases.
