### ISSUE TITLE
[Bug]: Error 403 while get Information CitrixVMTools

### ISSUE THREAD

**Issue by ritschi86** [aaronparker/evergreen#512]
### What happened?

`PS C:\Users\+++> gea CitrixVMTools
WARNUNG: Invoke-RestMethodWrapper: Error at URI: https://pvupdates.vmd.citrix.com/updates.json.
WARNUNG: Invoke-RestMethodWrapper: Error encountered: Der Remoteserver hat einen Fehler zurückgegeben: (403)
Unzulässig..
WARNUNG: Invoke-RestMethodWrapper: For troubleshooting steps see: https://stealthpuppy.com/evergreen/troubleshoot/.
gea : Internal application function: C:\Program
Files\WindowsPowerShell\Modules\Evergreen\2305.801\Apps\Get-CitrixVMTOols.ps1, failed with error: Der Remoteserver hat
einen Fehler zurückgegeben: (403) Unzulässig.
In Zeile:1 Zeichen:1
+ gea CitrixVMTOols
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-EvergreenApp

Application function Get-CitrixVMTOols ran, but we failed to capture any output.
Run 'Get-EvergreenApp -Name CitrixVMTOols -Verbose' to review additional details.
In C:\Program Files\WindowsPowerShell\Modules\Evergreen\2305.801\Public\Get-EvergreenApp.ps1:97 Zeichen:21
+                     throw [System.NullReferenceException]::New($Msg)
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], NullReferenceException
    + FullyQualifiedErrorId : Application function Get-CitrixVMTOols ran, but we failed to capture any output.
Run 'Get-EvergreenApp -Name CitrixVMTOols -Verbose' to review additional details.`

### Version

2305.801

### What PowerShell edition/s are you running Evergreen on?

Windows PowerShell

### Which operating system/s are you running Evergreen on?

Windows 10

### Have you reviewed the documentation?

- [X] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [X] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
gea CitrixVMTOols -Verbose
AUSFÜHRLICH: Function path: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2305.801\Apps\Get-CitrixVMTOols.ps1
AUSFÜHRLICH: Function exists: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2305.801\Apps\Get-CitrixVMTOols.ps1.
AUSFÜHRLICH: Dot sourcing: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2305.801\Apps\Get-CitrixVMTOols.ps1.
AUSFÜHRLICH: Get-FunctionResource: read application resource strings from [C:\Program
Files\WindowsPowerShell\Modules\Evergreen\2305.801\Manifests\CitrixVMTOols.json]
AUSFÜHRLICH: Calling: Get-CitrixVMTOols.
AUSFÜHRLICH: Invoke-RestMethodWrapper: Creating class TrustAllCertsPolicy.
AUSFÜHRLICH: Invoke-RestMethodWrapper: Settings Net.SecurityProtocolType to Tls12.
AUSFÜHRLICH: Invoke-RestMethodWrapper: Invoke-RestMethod parameter: UseBasicParsing: True.
AUSFÜHRLICH: Invoke-RestMethodWrapper: Invoke-RestMethod parameter: MaximumRedirection: 2.
AUSFÜHRLICH: Invoke-RestMethodWrapper: Invoke-RestMethod parameter: DisableKeepAlive: True.
AUSFÜHRLICH: Invoke-RestMethodWrapper: Invoke-RestMethod parameter: UserAgent: Mozilla/5.0 (Windows NT; Windows NT
10.0; de-DE) AppleWebKit/534.6 (KHTML, like Gecko) Chrome/7.0.500.0 Safari/534.6.
AUSFÜHRLICH: Invoke-RestMethodWrapper: Invoke-RestMethod parameter: Method: Default.
AUSFÜHRLICH: Invoke-RestMethodWrapper: Invoke-RestMethod parameter: Uri: https://pvupdates.vmd.citrix.com/updates.json.
AUSFÜHRLICH: Invoke-RestMethodWrapper: Invoke-RestMethod parameter: ContentType: application/json; charset=utf-8.
AUSFÜHRLICH: GET https://pvupdates.vmd.citrix.com/updates.json with 0-byte payload
WARNUNG: Invoke-RestMethodWrapper: Error at URI: https://pvupdates.vmd.citrix.com/updates.json.
WARNUNG: Invoke-RestMethodWrapper: Error encountered: Der Remoteserver hat einen Fehler zurückgegeben: (403)
Unzulässig..
WARNUNG: Invoke-RestMethodWrapper: For troubleshooting steps see: https://stealthpuppy.com/evergreen/troubleshoot/.
gea : Internal application function: C:\Program
Files\WindowsPowerShell\Modules\Evergreen\2305.801\Apps\Get-CitrixVMTOols.ps1, failed with error: Der Remoteserver hat
einen Fehler zurückgegeben: (403) Unzulässig.
In Zeile:1 Zeichen:1
+ gea CitrixVMTOols -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-EvergreenApp

AUSFÜHRLICH: Ausführen des Vorgangs "Return output" für das Ziel "C:\Program
Files\WindowsPowerShell\Modules\Evergreen\2305.801\Apps\Get-CitrixVMTOols.ps1".
Application function Get-CitrixVMTOols ran, but we failed to capture any output.
Run 'Get-EvergreenApp -Name CitrixVMTOols -Verbose' to review additional details.
In C:\Program Files\WindowsPowerShell\Modules\Evergreen\2305.801\Public\Get-EvergreenApp.ps1:97 Zeichen:21
+                     throw [System.NullReferenceException]::New($Msg)
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], NullReferenceException
    + FullyQualifiedErrorId : Application function Get-CitrixVMTOols ran, but we failed to capture any output.
Run 'Get-EvergreenApp -Name CitrixVMTOols -Verbose' to review additional details.
```

**Comment by lwalthert** [comment]
I have the same issue the cause seems to be that these downloads were moved behind an authentication wall by the software vendor.

**Comment by aaronparker** [comment]
I'll have to remove `CitrixVMTools` from Evergreen
