### ISSUE TITLE
[New app]: Microsoft Dependency Agent

### ISSUE THREAD

**Issue by BronsonMagnan** [aaronparker/evergreen#525]
### What is the new application?

https://learn.microsoft.com/en-us/azure/azure-monitor/vm/vminsights-dependency-agent-maintenance#upgrade-windows-agent

The Dependency Agent sends heartbeat data to the "InsightsMetrics" table. This behavior is different from Azure Monitor Agent, which sends agent health data to the "Heartbeat" table.

### Vendor site

https://aka.ms/dependencyagentwindows

### Have you reviewed the list of supported applications?

- [X] Supported apps at: https://stealthpuppy.com/evergreen/apps/

### Does the vendor require a sign-in?

No

**Comment by aaronparker** [comment]
The download doesn't provide version number information, and the URL is evergreen.
