### ISSUE TITLE
[New app]: Microsoft Monitoring Agent (Legacy Agent)

### ISSUE THREAD

**Issue by BronsonMagnan** [aaronparker/evergreen#526]
### What is the new application?

There is only a year left in production, but there are millions of people running SCOM still, so I don't know how they are going to handle that.
This is a must for getting Defender EDR setup on a server OS remote desktop host.
Windows 64-bit agent: https://go.microsoft.com/fwlink/?LinkId=828603
Windows 32-bit agent: https://go.microsoft.com/fwlink/?LinkId=828604

### Vendor site

https://go.microsoft.com/fwlink/?LinkId=828603

### Have you reviewed the list of supported applications?

- [X] Supported apps at: https://stealthpuppy.com/evergreen/apps/

### Does the vendor require a sign-in?

No

**Comment by aaronparker** [comment]
The download doesn't provide version number information, and updates are via Windows Update. I think the download URLs are evergreen URLs anyway
