### ISSUE TITLE
[Bug]: Filezilla returns 403 Forbidden

### ISSUE THREAD

**Issue by SeleniumSulfide** [aaronparker/evergreen#527]
### What happened?

When trying to Invoke-WebRequest on the URI supplied for FileZilla I receive 403 Forbidden

### Version

2307.810

### What PowerShell edition/s are you running Evergreen on?

Windows PowerShell

### Which operating system/s are you running Evergreen on?

Windows 10

### Have you reviewed the documentation?

- [ ] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [ ] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
Invoke-WebRequest : 
403 Forbidden
Forbidden
You don't have permission to access this resource.
At line:1 char:2
+ (Invoke-WebRequest -UseBasicParsing -URI $URI)
+  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

That is all the output I get after I receive the URI to download
```

**Comment by DanGough** [comment]
This happens all the time with various download URLs, so it’s not really an Evergreen bug. Try adding -UserAgent to the command followed by the user agent string for a typical browser (you can look them up) and that solves it most of the time.

I’m thinking of putting together a module for downloading files, since Invoke-WebRequest fails often, doesn’t auto detect the filename or preserve the modified date, etc!

**Comment by aaronparker** [comment]
This will have been an issue with the source site (i.e. Filezilla). It's working now, so Filezilla may have made a temporary change on their end.

Please ensure you've followed the troubleshooting article here: https://stealthpuppy.com/evergreen/troubleshoot/.

**Comment by DanGough** [comment]
This has reared its ugly head again! I copied the browser request to Powershell via browser dev tools and trimmed the headers down until I found what it needed - adding the ‘accept’ header in conjunction with the user agent let me download it.

I’ll add support for this in my PsDownload module.

```
$session = New-Object Microsoft.PowerShell.Commands.WebRequestSession
$session.UserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0"
Invoke-WebRequest -UseBasicParsing -Uri "https://download.filezilla-project.org/client/FileZilla_3.66.4_win64-setup.exe" `
-WebSession $session `
-Headers @{ "accept"="text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"
}
```
