### ISSUE TITLE
[Feature]: Deprecation warning for OmahaProxy, alternative might be needed?

### ISSUE THREAD

**Issue by Hrxn** [aaronparker/evergreen#546]
### What is your feature request?

Not sure when/if/how this will be a problem for Chrome?

https://github.com/aaronparker/evergreen/blob/fc1b6843929398dc8f06383d90eacdb319c3c0ae/Evergreen/Manifests/GoogleChrome.json#L1-L7

This is basically the same what I've been doing in my own scripts:

```PowerShell
$response = irm 'https://omahaproxy.appspot.com/all.json'
$versstr  = (($response | where {$_.os -eq 'win64'}).versions | where {$_.channel -eq 'stable'}).current_version
```

Problem is, there has been this warning at the top of the OmahaProxy page for quite some time now:
> OmahaProxy will be turned down on April 14, 2023. Use [ChromiumDash](https://chromiumdash.appspot.com/).

I mean, it's still up and running, but who knows?

I couldn't find any JSON endpoint on that ChromiumDash page yet, and I've also tried to ask this question in `chromium-discuss` but for reasons I do not understand my question has not appeared there yet...

An alternative might be needed, I think.

I've only found this [ChromeForTesting](https://github.com/GoogleChromeLabs/chrome-for-testing) project, and they provide JSON API info, but, in the current case, the version number for latest windows stable is not entirely correct..

### Have you tested against the current version?

- [ ] Yes, I've updated Evergreen and tested against the current version.

### Have you reviewed the documentation?

- [X] Documentation at: https://stealthpuppy.com/evergreen/

**Comment by aaronparker** [comment]
We've used the Chrome for Testing feed for `GoogleChromeDriver` #537

**Comment by aaronparker** [comment]
ChromiumDash has this to query releases which might work:

https://chromiumdash.appspot.com/fetch_releases?channel=Stable&platform=Windows

**Comment by Hrxn** [comment]
You're right, good find.

That seems like the right URL for this.

As I see it, returns value in a JSON array, latest being in first position, so the correct version number would simply be `$response[0].version`?

**Comment by aaronparker** [comment]
Correct
