### ISSUE TITLE
Get-NotepadPlusPlus has non consistent output (2005.176)

### ISSUE THREAD

**Issue by j81blog** [aaronparker/Evergreen#55]
Get-NotepadPlusPlus has non consistent output, the Architecture is missing for x86/exe

Version      : 7.8.6
Platform     : Windows
Architecture : x64
Date         : 2020-04-21T16:14:58Z
Size         : 4666076
URI          : https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.6/npp.7.8.6.bin.x64.zip

Version      : 7.8.6
Architecture : x86
Date         : 2020-04-21T16:14:58Z
Size         : 4194290
URI          : https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.6/npp.7.8.6.bin.zip

Version      : 7.8.6
Platform     : Windows
Date         : 2020-04-21T16:14:58Z
Size         : 3760568
URI          : https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.6/npp.7.8.6.Installer.exe

Version      : 7.8.6
Platform     : Windows
Architecture : x64
Date         : 2020-04-21T16:14:58Z
Size         : 4040456
URI          : https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v7.8.6/npp.7.8.6.Installer.x64.
               exe

Windows 10 1909
PSVersion - 5.1.18362.752
PSEdition - Desktop
BuildVersion - 10.0.18362.752
CLRVersion - 4.0.30319.42000
WSManStackVersion - 3.0
PSRemotingProtocolVersion - 2.3
SerializationVersion - 1.1.0.1

**Comment by aaronparker** [comment]
I get Architecture output for x86 on PowerShell Core and Windows PowerShell here. Perhaps it's something to do with the query to GitHub.

Does it consistently output like this?
What version of Evergreen are you using?

**Comment by j81blog** [comment]
I rebooted my machine and retested this one, and indeed now it gave the correct response. Not sure what went wrong. Sorry for this one.
