### ISSUE TITLE
get-googlechrome - not show 32bit in stable at the moment

### ISSUE THREAD

**Issue by pc-dok** [aaronparker/evergreen#550]
### What happened?

i can not get a chrome 32bit download link. so something looks that it changed. can you look why 32bit chrome stable is not showing any msi files?

regards
franco

### Version

newest

### What PowerShell edition/s are you running Evergreen on?

Windows PowerShell

### Which operating system/s are you running Evergreen on?

Windows Server 2016+

### Have you reviewed the documentation?

- [ ] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [ ] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
$Evergreen = Get-EvergreenApp -Name GoogleChrome | Where-Object { $_.Architecture -eq "x86" -and $_.Channel.ToLower() -eq "stable" }
```

**Comment by aaronparker** [comment]
I've pushed a recent update to change the version update source that Chrome uses, but have made an assumption that the 32-bit version would not be required. I can update the function to put the x86 releases back

In the mean time use this URL: https://dl.google.com/dl/chrome/install/beta/googlechromebetastandaloneenterprise.msi

Can I ask what's making you stick with the 32-bit version?

**Comment by pc-dok** [comment]
ok, sorry for that. as we use chrome as a published application we will always use 32bit because it needs much less memory as the 64bit version :). thank you for all the effort!

**Comment by aaronparker** [comment]
OK, makes sense. I've pushed an update to the development branch, so this will be fixed in the next version.

**Comment by pc-dok** [comment]
perfect, than i will edit my script to the old using command, at the moment i take the direct link. thanks!
