### ISSUE TITLE
[Bug]: Get-EvergreenApp OracleJava17 returns version 17.0.17 but downloaded .exe is 17.0.8

### ISSUE THREAD

**Issue by foxxcomm** [aaronparker/evergreen#558]
### What happened?

Evergreen shows version 17.0.17 of .exe installer but Oracle download site and actual .EXE file which evergreen downloads is version 17.0.8:

https://www.oracle.com/java/technologies/downloads/#jdk17-windows

### Version

2309.859

### What PowerShell edition/s are you running Evergreen on?

Windows PowerShell

### Which operating system/s are you running Evergreen on?

Windows Server 2016+

### Have you reviewed the documentation?

- [ ] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [ ] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
PS> Get-EvergreenApp OracleJava17

Version Sha256                                                           Type URI
------- ------                                                           ---- ---
17.0.17 f167123b123be215ba658ad7b7917a764ce9c4605909b48bc70651d949478a9e msi  https://download.oracle.com/java/17/latest/jdk-17_windows-x64_bin.msi
17.0.17 7adb58c306d41df54d2ca74e4489d4ade75b4dfb87dc5d5b0d3f21c53ca088fd exe  https://download.oracle.com/java/17/latest/jdk-17_windows-x64_bin.exe
17.0.17 98385c1fd4db7ad3fd7ca2f33a1fadae0b15486cfde699138d47002d7068084a zip  https://download.oracle.com/java/17/latest/jdk-17_windows-x64_bin.zip
```

**Comment by aaronparker** [comment]
This is an issue with the update feed (https://www.java.com/releases/releases.json), and a mismatch what Oracle is providing for downloads. The update feed only includes `17.0.17`, while Oracle must be providing `17.0.18` in the download.

**Comment by aaronparker** [comment]
Actually, the feed does have a `status` property on the versions, so functions could be updated to not include versions that don't have a `status` property with a value of `delivered`.

**Comment by foxxcomm** [comment]
Aaron -- Thanks for the quick fix! Closing.
