### ISSUE TITLE
Should Get-VMwareTools return the very latest version?

### ISSUE THREAD

**Issue by aaronparker** [aaronparker/Evergreen#56]
The VMware Tools mapping file [https://packages.vmware.com/tools/versions](https://packages.vmware.com/tools/versions) lists versions that are not included in an ESXi build. Should `Get-VMwareTools` return very latest version (`11.1.0` in the example below) or the latest version that is bundled with an ESXi build (`11.0.5` in the example)?

```
Client Server      Version Build
------ ------      ------- -----
11296  esx/0.0     11.1.0  
11270  esx/0.0     11.0.6  
11269  esx/6.7p02  11.0.5  16075168
```

**Comment by j81blog** [comment]
Or add a property "Included" with true/false that whoever wants to download VMware tools can choose. Sometimes you may want a newer release if this solves an issue.
And/or maybe introduce a Property "-All" for all Get-<EvergreenName> cmdlets to list all available versions/architecture/etc available, not only latest version.
