### ISSUE TITLE
[New app]: Plenom Busylight for MS Teams

### ISSUE THREAD

**Issue by tschuegy** [aaronparker/evergreen#565]
### What is the new application?

kuando Busylight is a presence, call alert, and notification system designed to eliminate distractions while keeping you updated on calls, events, and emails. The simple but effective productivity device displays your presence status in real-time while the built-in speaker signals incoming or missed calls making it a natural addition to Microsoft Teams on Windows.

Example files:
Apps\Get-PlenomBusylightForMSTeams.ps1
Manifests\PlenomBusylightForMSTeams.json

[PlenomBusylightForMSTeams.zip](https://github.com/aaronparker/evergreen/files/12838803/PlenomBusylightForMSTeams.zip)

### Vendor site

https://www.plenom.com/works-with/microsoft-teams/

### Have you reviewed the list of supported applications?

- [X] Supported apps at: https://stealthpuppy.com/evergreen/apps/

### Does the vendor require a sign-in?

No

**Comment by aaronparker** [comment]
Thanks for the code. I can add these; however, do you want to create a PR so that you're credited as a contributor?

**Comment by tschuegy** [comment]
No, thank you. It's OK for me.
________________________________
Von: Aaron Parker ***@***.***>
Gesendet: Sonntag, 8. Oktober 2023 10:27
An: aaronparker/evergreen ***@***.***>
Cc: tschuegy ***@***.***>; Author ***@***.***>
Betreff: Re: [aaronparker/evergreen] [New app]: Plenom Busylight for MS Teams (Issue #565)


Thanks for the code. I can add these; however, do you want to create a PR so that you're credited as a contributor?

**Comment by aaronparker** [comment]
This app doesn't provide any URL or API to query to find the latest versions
