### ISSUE TITLE
[New app]: Nitro PDF Pro

### ISSUE THREAD

**Issue by VITGEnkah** [aaronparker/evergreen#571]
### What is the new application?

PDF reader / editer. 

### Vendor site

https://www.gonitro.com//installers/business/v14/msi/download

### Have you reviewed the list of supported applications?

- [X] Supported apps at: https://stealthpuppy.com/evergreen/apps/

### Does the vendor require a sign-in?

No

**Comment by aaronparker** [comment]
I can't find a built in updater for Nitro Pro (looks like it was removed a few versions back) or an update feed on the Nitro web site, so there are no good methods to find the latest version.
