### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by sultanberisa** [aaronparker/evergreen#576]
### What happened?

  I am attempting to get download URL's for MacOS and not windows and the different arches (as in ARM and Intel). Is it possible? If so what's the most efficient way of doing so? I do see the MacOS entries in Evergreen.json on PSGallery forexample.

I thought maybe these commandlets would help, but I am not able to invoke any of the Get-* commandlets:

PS C:\Users\jztfl> Get-AdobeBrackets
Get-AdobeBrackets : The term 'Get-AdobeBrackets' is not recognized as the name of a cmdlet, function, script file, or o
perable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try aga
in.
At line:1 char:1
+ Get-AdobeBrackets
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-AdobeBrackets:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\jztfl> Get-CitrixWorkspaceApp
Get-CitrixWorkspaceApp : The term 'Get-CitrixWorkspaceApp' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct a
nd try again.
At line:1 char:1
+ Get-CitrixWorkspaceApp
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-CitrixWorkspaceApp:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\jztfl> Get-AdobeAcrobatReaderDC
Get-AdobeAcrobatReaderDC : The term 'Get-AdobeAcrobatReaderDC' is not recognized as the name of a cmdlet, function, scr
ipt file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is corre
ct and try again.
At line:1 char:1
+ Get-AdobeAcrobatReaderDC
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-AdobeAcrobatReaderDC:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
    
    Any other commandlets work fine. Is this something that is no longer possible?
    
  

### Version

2309.840

### What PowerShell edition/s are you running Evergreen on?

Windows PowerShell

### Which operating system/s are you running Evergreen on?

Windows 10+

### Have you reviewed the documentation?

- [X] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [X] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
PS C:\Users\jztfl> Get-EvergreenApp AdobeAcrobatReaderDC


Version      : 23.006.20360
Language     : Spanish
Architecture : x86
Name         : Reader 2023.006.20360 Spanish for Windows
URI          : https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/2300620360/AcroRdrDC2300620360_es_ES.exe

Version      : 23.006.20360
Language     : French
Architecture : x86
Name         : Reader 2023.006.20360 French for Windows
URI          : https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/2300620360/AcroRdrDC2300620360_fr_FR.exe
```

**Comment by sultanberisa** [comment]
Any ideas here on how to leverage evergreen for macos applications?

**Comment by aaronparker** [comment]
Evergreen hasn't been written to support macOS; however, the approaches used in many of the application functions can be modified to return the macOS installers, but this would require changing quite a bit of the code. You can fork the project and make changes
