### ISSUE TITLE
[New app]: Parallels RAS Client

### ISSUE THREAD

**Issue by danido95** [aaronparker/evergreen#577]
### What is the new application?

Parallels Remote Application Server Client for connecting to RDS Environments managed via RAS.
Probably the Version could be fetched via the Changlog file https://kb.parallels.com/en/129018

### Vendor site

https://www.parallels.com/products/ras/download/links/

### Does the vendor require a sign-in to download the app?

No

### Does the application include an updater?

Yes

### Have you reviewed the list of supported applications?

- [X] Supported apps at: https://stealthpuppy.com/evergreen/apps/

**Comment by aaronparker** [comment]
Client update feed is listed here: `http://download.parallels.com/ras/RASClient.xml`, so Evergreen will be able to use that.
