### ISSUE TITLE
Get-MicrosoftTeams displays slightly wrong formatted version number

### ISSUE THREAD

**Issue by xenadmin** [aaronparker/evergreen#58]
**Describe the bug**
The version number from the PowerShell Module shows for example: `1.3.00.12058`
Where appwiz.cpl and the MSI itself report: `1.3.0.12058`

**To Reproduce**
1. `(Get-MicrosoftTeams | Where-Object {$_.Architecture -eq "x64"}).Version`

**Expected behavior**
The command should report `1.3.0.12058` IMHO

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
 - OS: Windows Server 2016 Datacenter de-DE
```
PS C:\Users\xenadmin\Downloads> gcm *ever*
CommandType     Name                                               Version    Source                                                                                                                                   
-----------     ----                                               -------    ------                                                                                                                                   
Function        Export-EvergreenFunctionStrings                    2005.176   Evergreen                                                                                                                                
Function        Export-EvergreenResourceStrings                    2005.176   Evergreen
```

**Additional context**
Nothing.

**Comment by aaronparker** [comment]
Unfortunately this is the version format that comes from the update query at [https://teams.microsoft.com/package/desktopclient/update/1.2.00.32462/windows/x64?ring=general](https://teams.microsoft.com/package/desktopclient/update/1.2.00.32462/windows/x64?ring=general). I'm not sure why the version numbers would be different.

**Comment by DanGough** [comment]
@xenadmin you can work around this in your own code by casting to System.Version then converting back to a string, e.g:

```powershell
[string][version]'1.3.00.12058'
1.3.0.12058

([version]'1.3.00.12058').ToString()
1.3.0.12058
```

Careful applying it all values though, it'll fall over if the original string isn't a valid version, e.g. it contains letters.
