### ISSUE TITLE
[Feature]: Microsoft.NET 8.0 LTS Released

### ISSUE THREAD

**Issue by chezzer64** [aaronparker/evergreen#583]
### What is your feature request?

Microsoft released .NET 8.0.0 on Nov 14th 2023, as the new LTS. This means that Evergreen no longer lists the previous .NET 6.0 LTS downloads. Given that .NET 6.0 is still in active support until Nov 2024, it be useful for Evergreen to still offer .NET 6.0 downloads as an option? 
This could be implemented quite simply by updating the Microsoft.NET json manifest to add "6.0" to the list of existing Channels i.e. Get.Update.Channels like this:

```
    "Get": {
        "Update": {
            "Uri": "https://dotnetcli.blob.core.windows.net/dotnet/Runtime/#channel/latest.version",
            "ReplaceText": "#channel",
            "Channels": [
                "STS",
                "LTS",
                "6.0"
            ]

```

I also notice Microsoft have marked the 'Current' channel as deprecated, replacing it with 'STS' (Standard Term Support release) - so have amended that in the above also.

I've tested the above json manifest amendments locally and they produce the desired results.

Thanks.
 

### Have you tested against the current version?

- [X] Yes, I've updated Evergreen and tested against the current version.

### Have you reviewed the documentation?

- [X] Documentation at: https://stealthpuppy.com/evergreen/

**Comment by AScott-WWF** [comment]
Yep us too - we still need to deploy the latest 6.x releases
