### ISSUE TITLE
Get-CitrixWorkspaceApp does not return the latest Citrix HDX RealTime Media Engine

### ISSUE THREAD

**Issue by JonathanPitre** [aaronparker/Evergreen#59]
**Describe the bug**
Get-CitrixWorkspaceApp does not return the latest HDX RealTime Media Engine.

I would to love automate the install of the latest one (2.9).

Cheers!

**Comment by aaronparker** [comment]
I know but that's what's in the update feed. I haven't found a feed that includes the latest version yet.

**Comment by JonathanPitre** [comment]
It's not possible using the rss feed ?

https://www.citrix.com/content/citrix/en_us/downloads/workspace-app.rss

**Comment by aaronparker** [comment]
`Get-CitrixWorkspaceAppFeed` already exists.

It's not as clean as the Workspace app update feed that `Get-CitrixWorkspaceApp` uses: [https://downloadplugins.citrix.com/ReceiverUpdates/Prod/catalog_win.xml](https://downloadplugins.citrix.com/ReceiverUpdates/Prod/catalog_win.xml).

If we can find a better version of that feed, it should supply the correct version info.

**Comment by JonathanPitre** [comment]
I heard RTME wont be updated no more and 2.9 would be the latest so I guess it could be hardcoded as well.

```
$download = Invoke-WebRequest -UseBasicParsing -Uri ("https://www.citrix.com/downloads/workspace-app/additional-client-software/hdx-realtime-media-engine-latest.html") -SessionVariable websession
$href = $download.Links|Where-Object {$_.rel -like "*HDX_RealTime_Media_Engine_2.9_for_Windows.msi*"}
$url = "https:" + $href.rel
Invoke-WebRequest -Uri $url -OutFile $env:TEMP\HDX_RealTime_Media_Engine_2.9_for_Windows.msi
```

**Comment by aaronparker** [comment]
Added a note to the known issues: [https://stealthpuppy.com/Evergreen/knownissues.html](https://stealthpuppy.com/Evergreen/knownissues.html)
