### ISSUE TITLE
[Bug]: Beyond Compare not currently returning any results

### ISSUE THREAD

**Issue by AScott-WWF** [aaronparker/evergreen#590]
### What happened?

It appears that `Get-EvergreenApp ScooterBeyondCompare` is currently not returning any results.
It looks like the webpage (called from the Manifests\ScooterBeyondCompare.json file) may have changed slightly
I found that by modifying the URI in the ScooterBeyondCompare.json from:
https://www.scootersoftware.com/checkupdates.php?product=bc4&minor=3&maint=2&auth=30.15&build=24472&edition=prodebug&cpuarch=x86_64&platform=win32&lang=silent
to:
https://www.scootersoftware.com/checkupdates.php?product=bc4&minor=3&maint=2&auth=30.15&build=24472&edition=prodebug&cpuarch=x86_64&platform=win32
In a Firefox browser I can now get the page to return results again
Maybe there is now no longer a need to supply the `&lang=silent` info?
Sadly Evergreen still returns a 0-byte payload, so maybe the website is now expecting a different User Agent? (currently defined in the ScooterBeyondCompare.json file)

### Version

2312.878

### What PowerShell edition/s are you running Evergreen on?

PowerShell Core, Windows PowerShell

### Which operating system/s are you running Evergreen on?

Windows 10+

### Have you reviewed the documentation?

- [X] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [X] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
Get-EvergreenApp -Name ScooterBeyondCompare -Verbose
VERBOSE: Function path: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2312.878\Apps\Get-ScooterBeyondCompare.ps1
VERBOSE: Function exists: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2312.878\Apps\Get-ScooterBeyondCompare.ps1.
VERBOSE: Dot sourcing: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2312.878\Apps\Get-ScooterBeyondCompare.ps1.
VERBOSE: Get-FunctionResource: read application resource strings from [C:\Program Files\WindowsPowerShell\Modules\Evergreen\2312.878\Manifests\ScooterBeyondCompare.json]
VERBOSE: Calling: Get-ScooterBeyondCompare.
VERBOSE: Invoke-EvergreenRestMethod: Invoke-RestMethod parameter: DisableKeepAlive: True.
VERBOSE: Invoke-EvergreenRestMethod: Invoke-RestMethod parameter: UseBasicParsing: True.
VERBOSE: Invoke-EvergreenRestMethod: Invoke-RestMethod parameter: Uri: https://www.scootersoftware.com/checkupdates.php?product=bc4&minor=3&maint=2&auth=30.15&build=24472&edition=prodebug&cpuarch=x86_64&platform=win32&lang=silent.
VERBOSE: Invoke-EvergreenRestMethod: Invoke-RestMethod parameter: Method: Default.
VERBOSE: Invoke-EvergreenRestMethod: Invoke-RestMethod parameter: UserAgent: BeyondCompare/4.3 (Windows NT 10.0; Win64; x64).
VERBOSE: Invoke-EvergreenRestMethod: Invoke-RestMethod parameter: MaximumRedirection: 2.
VERBOSE: Invoke-EvergreenRestMethod: Invoke-RestMethod parameter: ContentType: application/json; charset=utf-8.
VERBOSE: Requested HTTP/1.1 GET with 0-byte payload
VERBOSE: Received HTTP/1.1 423-byte response of content type text/html
VERBOSE: Content encoding: utf-8
```

**Comment by aaronparker** [comment]
This looks to be working now.

**Comment by AScott-WWF** [comment]
Yes I believe so too - I'll put it down to the url not responding correctly

**Comment by DanGough** [comment]
Experiencing the same on 2312.878, the 2nd URL in the OP is returning a result whereas the 1st one returns an empty page.

**Comment by AScott-WWF** [comment]
It does look like this is broken, It may be because the Check for updates page (https://www.scootersoftware.com/checkupdates.php) doesn't appear to serve the XmlNode: "//Update" any more or maybe it doesn't like the URL being passed to it via the Evergreen Manifest.
I have opened the URL from the Manifest (https://www.scootersoftware.com/checkupdates.php?product=bc4&minor=3&maint=2&auth=30.15&build=24472&edition=prodebug&cpuarch=x86_64&platform=win32&lang=silent) in a Firefox browser which doesn't appear to work (It does however return a 200 status message (So reports "OK), but returns a blank web page), But If I change the Manifest URL by removing the "&lang=silent" from the end of the url (so it becomes: https://www.scootersoftware.com/checkupdates.php?product=bc4&minor=3&maint=2&auth=30.15&build=24472&edition=prodebug&cpuarch=x86_64&platform=win32) this does work in a browser, but looking at the code of what is returned - I can not see any XMLNodes - Which the Manifest is expecting.

It does look as though the web page may be falling foul of some modern web standards so this could be part of the reason it's not working?
![image](https://github.com/aaronparker/evergreen/assets/113043470/3472d674-74e0-40d4-8583-0b5c42df4d6e)

I guess someone with the right skills, a copy of WireShark installed and a semi-recent Beyond Compare installed, could capture traffic while performing a "Help | Check for Updates" in Beyond Compare to see if the URL has changed when performing this?
