### ISSUE TITLE
[New App]: BankID

### ISSUE THREAD

**Issue by jms-du-se** [aaronparker/Evergreen#603]
### What is the new application?

BankID is Sweden's most common e-ID.

Version control is done using XML against vks.bankid.com (https://www.bankid.com/en/foretag/enterprise/automatic-version-control)

User-agent needs to be: BankIDSecurityProgram

Installer URL can be found here:  https://www.bankid.com/en/foretag/enterprise

Example request:
```
<?xml version="1.0" encoding="utf-8"?>
<autoUpdateRequest><requestVersion>1.1</requestVersion><requestSequenceNr>1</requestSequenceNr><uhi>g+o9gYX4DcDZkQexT49puYWbWpO4</uhi><version>7.14.102.4</version></autoUpdateRequest>
```

Example response:
```
<?xml version="1.0" encoding="UTF-8"?>
<autoUpdateResponse><responseVersion>1.2</responseVersion><responseSequence>2</responseSequence><action>OK</action><bbdt>Njk2MzI0ODgtYWI4NC00ZGEyLWE=</bbdt><value>1705235039</value><time>1702643039</time><nptDelta>1296000</nptDelta></autoUpdateResponse>
```

I am not sure if the BankID application generates some unique content in the request that is being verified by the version controll server. If that's the case it will probably be difficult to get the latest version. 

But I hope this can be done anyway.

### Vendor site

https://www.bankid.com

### Does the vendor require a sign-in to download the app?

No

### Does the application include an updater?

Yes

### Have you reviewed the list of supported applications?

- [X] Supported apps at: https://stealthpuppy.com/evergreen/apps/

**Comment by aaronparker** [comment]
I'm getting hit with a Captcha response when querying the XML. Highly likely to be because I'm outside Sweden, so creating a function for this could be challenging

**Comment by jms-du-se** [comment]
Hi Aaron, wouldn't that be strange? Swedish citizens should be able to run the version check even when they are abroad.
Did you set the User-Agent to: BankIDSecurityProgram

**Comment by aaronparker** [comment]
Got this working with:

```powershell
$params = @{
    Uri              = "https://vks.bankid.com"
    UserAgent        = "BankIDSecurityProgram"
    ContentType      = "application/xml; charset=utf-8"
    Body             = '<?xml version="1.0" encoding="utf-8"?><autoUpdateRequest><requestVersion>1.1</requestVersion><requestSequenceNr>1</requestSequenceNr><uhi>g+o9gYX4DcDZkQexT49puYWbWpO4</uhi><version>7.14.102.4</version></autoUpdateRequest>'
    #Headers          = @{ "Accept-Language" = "sv-se" }
    #TransferEncoding = "gzip"
    Method           = "POST"
    UseBasicParsing  = $true
    Verbose          = $true
}
iwr @params
```

**Comment by aaronparker** [comment]
However, there's not much I can do with the response to turn it into an evergreen download URL. If we were to post the request with version `7.14.102.4` and get back `7.15.102.0`, for example, that could be turned into a URL.

**Comment by jms-du-se** [comment]
Hi!

Great that you got the version info working.

Regarding the downloaInstall package (bankid.com)<https://www.bankid.com/en/foretag/enterprise/install-package>d URL, the following info comes from: https://www.bankid.com/en/foretag/enterprise/install-package


The .exe file (which is auto-updating) is always downloaded from: https://install.bankid.com/api/file-download/Win
The file is downloaded via a redirect and is called BankID_installation_x_y_z.exe (x_y_z is replaced with the current version).

The MSI file, resided in a zip file, is downloaded here: https://cdn.bankid.com/bisp/win/BankID_installation_x_y_z.zip (x_y_z is replaced with the current version).


With this info, it should be possible to generate the download links, or am I wrong?

Best regards,
Jasper
________________________________
Från: Aaron Parker ***@***.***>
Skickat: den 27 mars 2024 13:25
Till: aaronparker/evergreen ***@***.***>
Kopia: Jasper Metselaar (HDa) ***@***.***>; Author ***@***.***>
Ämne: Re: [aaronparker/evergreen] [New App]: BankID (Issue #603)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

However, there's not much I can do with the response to turn it into an evergreen download URL. If we were to post the request with version 7.14.102.4 and get back 7.15.102.0, for example, that could be turned into a URL.

**Comment by aaronparker** [comment]
The XML in the response data doesn't provide any version data that relates to the download URLs, e.g. `https://cdn.bankid.com/bisp/win/BankID_installation_7_14_2.exe`, `https://cdn.bankid.com/bisp/win/BankID_installation_7_14_2.zip`
