### ISSUE TITLE
[Bug]: R Studio does not report the latest version

### ISSUE THREAD

**Issue by jms-du-se** [aaronparker/evergreen#605]
### What happened?

R Studio does not report the latest version (2023.12.0+369). It looks like the file that is used to find the updates, isn't being updated  (anymore) [https://www.rstudio.com/wp-content/downloads.json](https://www.rstudio.com/wp-content/downloads.json).

The check for updates function in the app is using a different way (connecting to : http://127.0.0.1:48073), which is probably more complicated to debug.

### Version

2312.878

### What PowerShell edition/s are you running Evergreen on?

Windows PowerShell

### Which operating system/s are you running Evergreen on?

Windows 10+

### Have you reviewed the documentation?

- [X] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [X] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
VERBOSE: Function path: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2312.878\Apps\Get-rstudio.ps1
VERBOSE: Function exists: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2312.878\Apps\Get-rstudio.ps1.
VERBOSE: Dot sourcing: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2312.878\Apps\Get-rstudio.ps1.
VERBOSE: Get-FunctionResource: read application resource strings from [C:\Program
Files\WindowsPowerShell\Modules\Evergreen\2312.878\Manifests\rstudio.json]
VERBOSE: Calling: Get-rstudio.
VERBOSE: Invoke-EvergreenRestMethod: Invoke-RestMethod parameter: UseBasicParsing: True.
VERBOSE: Invoke-EvergreenRestMethod: Invoke-RestMethod parameter: MaximumRedirection: 2.
VERBOSE: Invoke-EvergreenRestMethod: Invoke-RestMethod parameter: DisableKeepAlive: True.
VERBOSE: Invoke-EvergreenRestMethod: Invoke-RestMethod parameter: UserAgent: Mozilla/5.0 (Windows NT; Windows NT 10.0;
sv-SE) AppleWebKit/534.6 (KHTML, like Gecko) Chrome/7.0.500.0 Safari/534.6.
VERBOSE: Invoke-EvergreenRestMethod: Invoke-RestMethod parameter: Method: Default.
VERBOSE: Invoke-EvergreenRestMethod: Invoke-RestMethod parameter: Uri:
https://www.rstudio.com/wp-content/downloads.json.
VERBOSE: Invoke-EvergreenRestMethod: Invoke-RestMethod parameter: ContentType: application/json; charset=utf-8.
VERBOSE: GET with 0-byte payload
VERBOSE: received 133558-byte response of content type application/json
VERBOSE: Get-FileType: found extension: [exe]
VERBOSE: Get-FileType: found extension: [exe]


Version     : 2023.09.1+494.pro2
ProductName : RStudio Pro 2023.09.1+494.pro2 - Windows 10/11 (64-bit)
Pro         : True
Date        : 2023-10-17
Size        : 218296432
Sha256      : e31071866ed2d2d082641b7660fcce3685d439b1be7914b7794555cad56dd022
Type        : exe
URI         : https://download1.rstudio.org/electron/windows/RStudio-pro-2023.09.1-494.pro2.exe

Version     : 2023.09.1+494
ProductName : RStudio 2023.09.1+494 - Windows 10/11 (64-bit)
Pro         : False
Date        : 2023-10-17
Size        : 214341200
Sha256      : fe62b78446fb91d905ec28d1f017aff8aaaf0bbb40a79b0b5043adf60ae910e1
Type        : exe
URI         : https://download1.rstudio.org/electron/windows/RStudio-2023.09.1-494.exe
```

**Comment by aaronparker** [comment]
The new version makes a call like this: `https://www.rstudio.org/links/check_for_update?version=2023.12.0&os=win&format=kvp`

Which returns content like this from which the version number can be extracted: `update-version=2023.12.0%2B369&update-url=https%3A%2F%2Fwww.rstudio.com%2Fproducts%2Frstudio%2Fdownload%2F&update-message=RStudio%202023.12.0%2B369%20is%20now%20available%20%28you%27re%20using%202023.11.0%29&update-urgent=0`

Found in the source code here: https://github.com/rstudio/rstudio/blob/6f7af1eab02568be3de327190a96fc5dba2dc247/src/cpp/session/modules/SessionUpdates.R
