### ISSUE TITLE
[New app]: Qgis

### ISSUE THREAD

**Issue by jms-du-se** [aaronparker/evergreen#619]
### What is the new application?

Free and Open Source Geographic Information System. [Qgis website](https://qgis.org/en/site/)

Version information for the Current release: https://[version.qgis.org/version.txt](https://version.qgis.org/version.txt)
Unknown how the latest LTS release is discovered, since the version check points att the same URL as above.

Download folder containing all downloads: https://download.qgis.org/downloads/?C=M;O=D

### Vendor site

https://qgis.org/en/site/

### Does the vendor require a sign-in to download the app?

No

### Does the application include an updater?

No

### Have you reviewed the list of supported applications?

- [X] Supported apps at: https://stealthpuppy.com/evergreen/apps/

**Comment by AScott-WWF** [comment]
I too could be keen on the addition of this however there are two branches
Current (which you have alluded to)
LTS

As we use the LTS version (installed using the OSGeo4W installer), I wrote a web scrape to check the page for a later 'LTS' version.
```
$DownloadsUrl = "https://www.qgis.org/en/site/forusers/download.html"
# Now determine the Version of the latest available version of the installer:
$PageContent = (Invoke-WebRequest -UseBasicParsing -Uri $DownloadsUrl).Links
# Obtain Url to the latest .msi, from link below 'Looking for the most stable version? Get QGIS x.xx LTR' text on webpage, and Version number is obtained easiest from the filename within the $SourceUrl
[version]$LatestVersion = ((($PageContent | Where-Object {$_.OuterHtml -like '<a class="reference secondary-download-link" href="https://qgis.org/downloads/QGIS-OSGeo4W-*.msi">*Looking for the most stable version? Get QGIS * LTR*</a>'}).href).split("-")[2]).Trim()
Write-Output "Latest version of QGIS LTR is:    $($LatestVersion)"
```
It would be nice however if there was an EverGreen function to do this (rather then relying on a webscrape that could break at any time QGIS change the web site)

**Comment by jms-du-se** [comment]
Yes, there should be a Evergreen function for this.
Somehow the latest LTS version is detected during the version check, even though this check uses the same version.txt file

**Comment by aaronparker** [comment]
`version.txt` is returning as HTML for me. Is that's what's intended?

The version number can also be gathered from here: https://github.com/qgis/QGIS

**Comment by jms-du-se** [comment]
Hi Aaron,

The version.txt includes html that's being displayed in the update notification window.

I searched their GitHub site before, but didn't find a way to identify the latest LTS release.
The latest regular release isn't a problem.

/Jasper

**Comment by SpecterShell** [comment]
https://github.com/qgis/QGIS-Website/blob/master/scripts/mkversion.py

**Comment by aaronparker** [comment]
@SpecterShell thanks, that script is writing https://version.qgis.org/version.json which looks like it will do the trick.
