### ISSUE TITLE
[New app]: Adobe Digital Editons

### ISSUE THREAD

**Issue by jms-du-se** [aaronparker/evergreen#621]
### What is the new application?

Reader for E-books.

The app contains a Auto Update function, using ADEAutoUpdater_450.exe

The AutoUpdater seems to use the following parameters.

"ADEAutoUpdater_450.exe" -checkForUpdate https://adedownload.adobe.com/pub/adobe/digitaleditions/sha2/adeupdaterconfig.cfg 4.5.12.112 en_US

Unfortunately I haven't been able to see the network traffic (Uri), but it is connecting to adedownload.adobe.com

### Vendor site

https://www.adobe.com/solutions/ebook/digital-editions.html

### Does the vendor require a sign-in to download the app?

No

### Does the application include an updater?

Yes

### Have you reviewed the list of supported applications?

- [X] Supported apps at: https://stealthpuppy.com/evergreen/apps/

**Comment by aaronparker** [comment]
The following info is returned from https://adedownload.adobe.com/pub/adobe/digitaleditions/sha2/adeupdaterconfig.cfg, which includes the Version number and installer download

```json
{
"Version":"4.5.7.179634",
"EnableAutoUpdate":"1",
"DefaultTimer":"604800",
"DownloadPath":"http://download.adobe.com/pub/adobe/digitaleditions/ADE_4.5_Installer.exe",
"SecuredDownloadPath":"https://adedownload.adobe.com/pub/adobe/digitaleditions/ADE_4.5_Installer.exe",
"DownloadPageURL":"http://www.adobe.com/solutions/ebook/digital-editions/download.html",
"FeaturePoints":
	{
		"en_US":
		{
			"1":"Security bug fixes."
		},
		"de_DE":
		{
			"1":"Behebung von Sicherheitsproblemen."
		},
		"ja_JP":
		{
			"1":"セキュリティバグ修正。"
		},
		"ko_KR":
		{
			"1":"보안 버그 수정."
		},
		"es_ES":
		{
			"1":"Correcciones de errores de seguridad"
		},
		"fr_FR":
		{
			"1":"Corrections des bogues de sécurité"
		},
		"nl_NL":
		{
			"1":"Opgeloste beveiligingsproblemen"
		},
		"pt_BR":
		{
			"1":"Correções de erros de segurança"
		},
		"it_IT":
		{
			"1":"Risoluzione di bug di sicurezza."
		},
		"zh_CN":
		{
			"1":"安全性问题修复。"
		},
		"zh_TW":
		{
			"1":"安全性修正。"
		}
	}
}
```

**Comment by jms-du-se** [comment]
Great find!
I'll see if I can add the app later and create a pr.

/Jasper

**Comment by jms-du-se** [comment]
This is more complicated than I thought.
The remote server is responding with the "wrong" content type (application/octet-stream) and I don't really know how to convert this.
I also tried to solve this using EvergreenInvoke-Webrequest, but converting to UTF-8 resulted in encoding issues with BOM.

Any tips or guidance is appreciated. 😊

**Comment by jms-du-se** [comment]
Yes, removing the BOM data was the main problem, but I found a solution.
Will create a PR now. :)

**Comment by jms-du-se** [comment]
Sorry to bother you again. It seems that the version number in the file https://adedownload.adobe.com/pub/adobe/digitaleditions/sha2/adeupdaterconfig.cfg is not the latest.

The latest version is 4.5.12.112 and not 4.5.7.179634. Not sure how to resolve this.

Please remove the PR for now.
