### ISSUE TITLE
[Feature]: MicrosoftTeamsPreview shouldn't be preview anymore :-)

### ISSUE THREAD

**Issue by ThiloL** [aaronparker/evergreen#625]
### What is your feature request?

Maybe it shoud be a flavour (MSIX) in regular Teams app.

### Have you tested against the current version?

- [X] Yes, I've updated Evergreen and tested against the current version.

### Have you reviewed the documentation?

- [X] Documentation at: https://stealthpuppy.com/evergreen/

**Comment by aaronparker** [comment]
The old Teams will be retired in June, so I'd suggest that we don't rename the Evergreen apps until then. 

I don't want to rename now to `MicrosoftTeams2`, and then `MicrosoftTeams` after June.

**Comment by ThiloL** [comment]
If you put it as a new Ring in the **MicrosoftTeams** app?
![image](https://github.com/aaronparker/evergreen/assets/2923889/929b995c-1250-491c-9b8c-fb0fa1ba3d37)

**Comment by aaronparker** [comment]
I've pushed a change to `development` that renames:
* `MicrosoftTeams` to `MicrosoftClassic`
* `MicrosoftTeamsPreview` to `MicrosoftTeams`
* Updates the app name for each production

This is a breaking change, so people will need to update scripts, but this should only require a single change to these functions.

**Comment by ThiloL** [comment]
👍
