### ISSUE TITLE
[Feature]: New Microsoft Teams Bootstrapper download

### ISSUE THREAD

**Issue by ES-PSH** [aaronparker/evergreen#630]
### What is your feature request?

I would like to download the teamsbootstrapper.exe for the new Microsoft Teams instalation.

See: https://learn.microsoft.com/en-us/microsoftteams/new-teams-bulk-install-client#option-1b-download-and-install-new-teams-using-an-offline-installer

### Have you tested against the current version?

- [X] Yes, I've updated Evergreen and tested against the current version.

### Have you reviewed the documentation?

- [X] Documentation at: https://stealthpuppy.com/evergreen/

**Comment by aaronparker** [comment]
There isn't a method to determine the version number of the boot strapper EXE.

You can manually construct an object to pass to `Save-EvergreenApp` like this:

```PowerShell
# Download the Bootstrapper EXE
$App = [PSCustomObject]@{
    Version = "2.0.0"
    URI     = "https://statics.teams.cdn.office.net/production-teamsprovision/lkg/teamsbootstrapper.exe"
}
$TeamsExe = Save-EvergreenApp -InputObject $App -CustomPath $Path -WarningAction "SilentlyContinue"

# Download Teams v2 MSIX installer
$App = [PSCustomObject]@{
    Version = "2.0.0"
    URI     = "https://statics.teams.cdn.office.net/production-windows-x64/enterprise/webview2/lkg/MSTeams-x64.msix"
}
$TeamsMsi = Save-EvergreenApp -InputObject $App -CustomPath $Path -WarningAction "SilentlyContinue"
```
