### ISSUE TITLE
[Feature]: Microsoft ODBC Driver mulitple languages and Additional 'Base Version' attribute

### ISSUE THREAD

**Issue by AScott-WWF** [aaronparker/evergreen#685]
### What is your feature request?

Currently the Microsoft ODBC Driver download is only offered without a defined language (so will by default download the English (United States) version) and only for the latest v18 build (or Base Version 18).
There can also often be a need to deploy the earlier generation v17 (Base Version 17) driver, which Microsoft still updates from time to time (usually to fix security vulnerabilities).
Both of these versions are offered via the same Microsoft Learn webpage:
https://learn.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-ver16

Fortunately setting the correct url per language is as simple as appending the &clcid=<language_id> to the end of the URL (for either Base Version).
| Language | Language Id |
| --- | --- |
| Chinese (Simplified) | 0x804 |
| Chinese (Traditional) | 0x404 |
| English (United States) | 0x409 |
| French |  0x40c |
| German |  0x407 |
| Italian |  0x410 |
| Japanese |  0x411 |
| Korean |  0x412 |
| Portugese (Brazil) |  0x416 |
| Russian |  0x419 |
| Spanish |  0x40a |

N.B These Lanuguage Id's appear to be consistent across all Microsoft downloads - which might be useful

e.g. to obtain the Spanish download URL for the x64 v18.3.3.1, the full URL would be:
https://go.microsoft.com/fwlink/?linkid=2266640&clcid=0x40a

This would allow Evergreen to serve the correct language specific download for the Microsoft ODBC Driver

As Evergreen is not offering the latest version of Base Version 17 downloads, I wonder if the function could be extended to include them too?

The current downloads for each Base version are as follows
| Base Version | (Current Latest Version) | Architecture | URL (excluding Language Id) |
| --- | --- | --- | --- |
| 17 | (17.10.6) | x64 | https://go.microsoft.com/fwlink/?linkid=2266337 |
| 17 | (17.10.6) | x86 | https://go.microsoft.com/fwlink/?linkid=2266446 |
| 18 | (18.3.3.1) | x64 | https://go.microsoft.com/fwlink/?linkid=2266640 |
| 18 | (18.3.3.1) | x86 | https://go.microsoft.com/fwlink/?linkid=2266742 |
| 18 | (18.3.3.1) | ARM64 | https://go.microsoft.com/fwlink/?linkid=2266837 |

What I am asking is two things:
- Add the alternative languages (much like is currently done for Microsoft SSMS `gea MicrosoftSSMS -Verbose`)
- Add a new attribute for the Base version

This will allow users of Evergreen to filter the results on both their chosen Language and the specific version they require.

N.B. I have created a second Feature Request for Microsoft OLE DB Driver https://github.com/aaronparker/evergreen/issues/686 as this has the same requirement and the functionaility would be almost identical.

Verbose Output for Get-EvergreenApp MicrosoftODBCDriverForSQLServer:
```
VERBOSE: Function path: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2405.1013\Apps\Get-MicrosoftODBCDriverForSQLServer.ps1
VERBOSE: Function exists: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2405.1013\Apps\Get-MicrosoftODBCDriverForSQLServer.ps1.
VERBOSE: Dot sourcing: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2405.1013\Apps\Get-MicrosoftODBCDriverForSQLServer.ps1.
VERBOSE: Get-FunctionResource: read application resource strings from [C:\Program Files\WindowsPowerShell\Modules\Evergreen\2405.1013\Manifests\MicrosoftODBCDriverForSQLServer.json]
VERBOSE: Calling: Get-MicrosoftODBCDriverForSQLServer.
VERBOSE: Resolve-SystemNetWebRequest: Attempting to resolve: https://go.microsoft.com/fwlink/?linkid=2249006.
VERBOSE: Resolve-SystemNetWebRequest: Resolved to: [https://download.microsoft.com/download/4/f/e/4fed6f4b-dc42-4255-b4b4-70f8e2a35a63/en-US/18.3.2.1/x64/msodbcsql.msi].
VERBOSE: Get-FileType: found extension: [msi]
VERBOSE: Resolve-SystemNetWebRequest: Attempting to resolve: https://go.microsoft.com/fwlink/?linkid=2249005.
VERBOSE: Resolve-SystemNetWebRequest: Resolved to: [https://download.microsoft.com/download/4/f/e/4fed6f4b-dc42-4255-b4b4-70f8e2a35a63/en-US/18.3.2.1/x86/msodbcsql.msi].
VERBOSE: Get-FileType: found extension: [msi]
VERBOSE: Resolve-SystemNetWebRequest: Attempting to resolve: https://go.microsoft.com/fwlink/?linkid=2248720.
VERBOSE: Resolve-SystemNetWebRequest: Resolved to: [https://download.microsoft.com/download/4/f/e/4fed6f4b-dc42-4255-b4b4-70f8e2a35a63/en-US/18.3.2.1/arm64/msodbcsql.msi].
VERBOSE: Get-FileType: found extension: [msi]

Version      : 18.3.2.1
Date         : 06/10/2023 16:53:08
Size         : 4751360
Architecture : x64
Type         : msi
URI          : https://download.microsoft.com/download/4/f/e/4fed6f4b-dc42-4255-b4b4-70f8e2a35a63/en-US/18.3.2.1/x64/msodbcsql.msi

Version      : 18.3.2.1
Date         : 06/10/2023 16:53:09
Size         : 2621440
Architecture : x86
Type         : msi
URI          : https://download.microsoft.com/download/4/f/e/4fed6f4b-dc42-4255-b4b4-70f8e2a35a63/en-US/18.3.2.1/x86/msodbcsql.msi

Version      : 18.3.2.1
Date         : 06/10/2023 16:53:02
Size         : 3190784
Architecture : ARM64
Type         : msi
URI          : https://download.microsoft.com/download/4/f/e/4fed6f4b-dc42-4255-b4b4-70f8e2a35a63/en-US/18.3.2.1/arm64/msodbcsql.msi

```

### Have you tested against the current version?

- [X] Yes, I've updated Evergreen and tested against the current version.

### Have you reviewed the documentation?

- [X] Documentation at: https://stealthpuppy.com/evergreen/

**Comment by aaronparker** [comment]
I've added `MicrosoftODBCDriverForSQLServer17` to return the v17 driver. When v19 comes out, then we can create a `MicrosoftODBCDriverForSQLServer18`, leaving `MicrosoftODBCDriverForSQLServer` to alway return the latest version.
