### ISSUE TITLE
[Feature]: Microsoft OLE DB Driver mulitple languages and Additional 'Base Version' attribute

### ISSUE THREAD

**Issue by AScott-WWF** [aaronparker/evergreen#686]
### What is your feature request?

Similar to https://github.com/aaronparker/evergreen/issues/685
Currently the Microsoft OLE DB Driver download is only offered without a defined language (so will by default download the English (United States) version) and only for the latest v19 build (or Base Version 19).
There can also often be a need to deploy the earlier generation v18 (Base Version 18) driver, which Microsoft still updates from time to time (usually to fix security vulnerabilities).
Base version 19 builds are offered via this Microsoft Learn webpage:
https://learn.microsoft.com/en-us/sql/connect/oledb/download-oledb-driver-for-sql-server?view=sql-server-ver16
Earlier versions (Including the latest Base version 18) are offered via this Microsoft Learn webpage:
https://learn.microsoft.com/en-us/sql/connect/oledb/release-notes-for-oledb-driver-for-sql-server?view=sql-server-ver16#previous-releases

Fortunately setting the correct url per language is as simple as appending the &clcid=<language_id> to the end of the URL (for either Base Version).
| Language | Language Id |
| --- | --- |
| Chinese (Simplified) | 0x804 |
| Chinese (Traditional) | 0x404 |
| English (United States) | 0x409 |
| French |  0x40c |
| German |  0x407 |
| Italian |  0x410 |
| Japanese |  0x411 |
| Korean |  0x412 |
| Portugese (Brazil) |  0x416 |
| Russian |  0x419 |
| Spanish |  0x40a |

N.B These Lanuguage Id's appear to be consistent across all Microsoft downloads - which might be useful

e.g. to obtain the Spanish download URL for the x64 v19.3.3, the full URL would be:
https://go.microsoft.com/fwlink/?linkid=2266674&clcid=0x40a

This would allow Evergreen to serve the correct language specific download for the Microsoft OLE DB Driver

As Evergreen is not offering the latest version of Base Version 18 downloads, I wonder if the function could be extended to include them too?

The current downloads for each Base version are as follows
| Base Version | (Current Latest Version) | Architecture | URL (excluding Language Id) |
| --- | --- | --- | --- |
| 18 | (18.7.2) | x64 | https://go.microsoft.com/fwlink/?linkid=2266757 |
| 18 | (18.7.2) | x86 | https://go.microsoft.com/fwlink/?linkid=2266858 |
| 19 | (19.3.3) | x64 | https://go.microsoft.com/fwlink/?linkid=2266674 |
| 19 | (19.3.3) | x86 | https://go.microsoft.com/fwlink/?linkid=2266883 |
| 19 | (19.3.3) | ARM64 | https://go.microsoft.com/fwlink/?linkid=2266884 |

What I am asking is two things:
- Add the alternative languages (much like is currently done for Microsoft SSMS `gea MicrosoftSSMS -Verbose`)
- Add a new attribute for the Base version

This will allow users of Evergreen to filter the results on both their chosen Language and the specific version they require.

Verbose Output for Get-EvergreenApp MicrosoftOLEDBDriverForSQLServer:
```
Get-EvergreenApp MicrosoftOLEDBDriverForSQLServer -Verbose
VERBOSE: Function path: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2405.1013\Apps\Get-MicrosoftOLEDBDriverForSQLServer.ps1
VERBOSE: Function exists: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2405.1013\Apps\Get-MicrosoftOLEDBDriverForSQLServer.ps1.
VERBOSE: Dot sourcing: C:\Program Files\WindowsPowerShell\Modules\Evergreen\2405.1013\Apps\Get-MicrosoftOLEDBDriverForSQLServer.ps1.
VERBOSE: Get-FunctionResource: read application resource strings from [C:\Program Files\WindowsPowerShell\Modules\Evergreen\2405.1013\Manifests\MicrosoftOLEDBDriverForSQLServer.json]
VERBOSE: Calling: Get-MicrosoftOLEDBDriverForSQLServer.
VERBOSE: Resolve-SystemNetWebRequest: Attempting to resolve: https://go.microsoft.com/fwlink/?linkid=2248728.
VERBOSE: Resolve-SystemNetWebRequest: Resolved to: [https://download.microsoft.com/download/f/1/3/f13ce329-0835-44e7-b110-44decd29b0ad/en-US/19.3.2.0/x64/msoledbsql.msi].
VERBOSE: Get-FileType: found extension: [msi]
VERBOSE: Resolve-SystemNetWebRequest: Attempting to resolve: https://go.microsoft.com/fwlink/?linkid=2249102.
VERBOSE: Resolve-SystemNetWebRequest: Resolved to: [https://download.microsoft.com/download/f/1/3/f13ce329-0835-44e7-b110-44decd29b0ad/en-US/19.3.2.0/x86/msoledbsql.msi].
VERBOSE: Get-FileType: found extension: [msi]
VERBOSE: Resolve-SystemNetWebRequest: Attempting to resolve: https://go.microsoft.com/fwlink/?linkid=2249103.
VERBOSE: Resolve-SystemNetWebRequest: Resolved to: [https://download.microsoft.com/download/f/1/3/f13ce329-0835-44e7-b110-44decd29b0ad/en-US/19.3.2.0/arm64/msoledbsql.msi].
VERBOSE: Get-FileType: found extension: [msi]

Version      : 19.3.2.0
Date         : 06/10/2023 16:53:18
Size         : 4894720
Architecture : x64
Type         : msi
URI          : https://download.microsoft.com/download/f/1/3/f13ce329-0835-44e7-b110-44decd29b0ad/en-US/19.3.2.0/x64/msoledbsql.msi

Version      : 19.3.2.0
Date         : 06/10/2023 16:53:18
Size         : 2805760
Architecture : x86
Type         : msi
URI          : https://download.microsoft.com/download/f/1/3/f13ce329-0835-44e7-b110-44decd29b0ad/en-US/19.3.2.0/x86/msoledbsql.msi

Version      : 19.3.2.0
Date         : 06/10/2023 16:53:15
Size         : 2981888
Architecture : ARM64
Type         : msi
URI          : https://download.microsoft.com/download/f/1/3/f13ce329-0835-44e7-b110-44decd29b0ad/en-US/19.3.2.0/arm64/msoledbsql.msi

```

### Have you tested against the current version?

- [X] Yes, I've updated Evergreen and tested against the current version.

### Have you reviewed the documentation?

- [X] Documentation at: https://stealthpuppy.com/evergreen/

**Comment by aaronparker** [comment]
I've added `Get-MicrosoftOLEDBDriverForSQLServer18` to return the v17 driver. When v20 comes out, then we can create a `MicrosoftODBCDriverForSQLServer19`, leaving `Get-MicrosoftOLEDBDriverForSQLServer` to alway return the latest version.
