### ISSUE TITLE
[Bug]: Get-EvergreenApp for AzureCLI does not return 64 bit installer

### ISSUE THREAD

**Issue by BronsonMagnan** [aaronparker/evergreen#691]
### What happened?

Get-EvergreenApp for AzureCLI does not return 64 bit installer, only the 32 bit installer is returned
The latest x64 installer is here: https://aka.ms/installazurecliwindowsx64
https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-windows?tabs=azure-cli#latest-version

### Version

2405.1054

### What PowerShell edition/s are you running Evergreen on?

Windows PowerShell

### Which operating system/s are you running Evergreen on?

Windows Server 2016+

### Have you reviewed the documentation?

- [X] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [X] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
PS C:\Setup> Find-EvergreenApp -Name AzureCLi | Get-EvergreenApp


Version       : 2.61.0
Platform      : Windows
Architecture  : x86
Type          : msi
InstallerType : Default
Date          : 2024-05-16T03:38:31Z
Size          : 70651904
URI           : https://github.com/Azure/azure-cli/releases/download/azure-cli-2.61.0/azure-cli-2.61.0.msi
```

**Comment by aaronparker** [comment]
The GitHub repo appears to only host the 32-bit installer. The app could be updated to return the version number from there and then resolve those evergreen URLs for each installer.

**Comment by BronsonMagnan** [comment]
https://azcliprod.blob.core.windows.net/msi/azure-cli-2.61.0-x64.msi
