### ISSUE TITLE
[Bug]: MicrosoftAzureDataStudio - No update feed found for win32-x64 and insider

### ISSUE THREAD

**Issue by steveturnbull** [aaronparker/evergreen#699]
### What happened?

Get-evergreenapp -name MicrosoftAzureDataStudio is responding with no update feed found.

Was working ok earlier in the week, so most likely MS changed something or there is a new feed location for the files and evergreen may need update.

### Version

2405.1076

### What PowerShell edition/s are you running Evergreen on?

Windows PowerShell

### Which operating system/s are you running Evergreen on?

Windows 10+

### Have you reviewed the documentation?

- [ ] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [ ] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
WARNING: Run 'Get-EvergreenApp -Name "MicrosoftAzureDataStudio" -Verbose' to review additional details for
troubleshooting.
Get-MicrosoftAzureDataStudio: No update feed found for win32-x64 and Insider.
At C:\Program Files\WindowsPowerShell\Modules\Evergreen\2405.1076\Apps\Get-MicrosoftAzureDataStudio.ps1:47 char:21
+ ...             throw "$($MyInvocation.MyCommand): No update feed found f ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Get-MicrosoftAz...64 and Insider.:String) [], RuntimeException
    + FullyQualifiedErrorId : Get-MicrosoftAzureDataStudio: No update feed found for win32-x64 and Insider.
```

**Comment by steveturnbull** [comment]
https://azuredatastudio-update.azurewebsites.net/api/update

Cannot GET /api/update

**Comment by aaronparker** [comment]
This was an issue with the vendor source update file which they've fixed
