### ISSUE TITLE
Get-AdobeAcrobatReaderDC

### ISSUE THREAD

**Issue by haavarstein** [aaronparker/Evergreen#7]
Missing -Type -Platform -Language

**Comment by aaronparker** [comment]
Filter the output with `Where-Object`. I've removed parameters from most functions to simplify the code.

**Comment by aaronparker** [comment]
Here's what you'd have to do to get Windows, English downloads for Reader:

`Get-AdobeAcrobatReaderDC | Where-Object { $_.Platform -eq "Windows" -and ($_.Language -eq "English" -or $_.Language -eq "Neutral" -or $_.Language -eq "Multi") }`

It's quite a bit of filtering, though what this does is put the task of filtering on the user and simplifies our code. I don't really know the right approach. I like the idea of simplicity as much as we can.

**Comment by aaronparker** [comment]
Perhaps if we had a wrapper function: e.g., `Get-Evergreen -Application "AdobeReaderDC"` that could have automatic filtering or parameters applied.
