### ISSUE TITLE
[Bug]: The Download size for 7zip is incorrect 

### ISSUE THREAD

**Issue by j81blog** [aaronparker/evergreen#701]
### What happened?

`Get-EvergreenApp -Name 7zip | Where-Object{$_.Architecture -eq 'x64' -and $_.Type -like 'msi' } | Save-
EvergreenApp -CustomPath C:\temp`

If I use the same URI to dowmload the file I get the sourcefourge "info" page with a counter. Then I'm being presented with the download and get the right file with right size. Lookls like downloadg via PowerShell doesn't work anymore.

### Version

2405.1076

### What PowerShell edition/s are you running Evergreen on?

PowerShell Core, Windows PowerShell

### Which operating system/s are you running Evergreen on?

Windows 10+, Windows Server 2016+

### Have you reviewed the documentation?

- [X] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [X] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
VERBOSE: Path exists: C:\Temp.
VERBOSE: URL: https://altushost-swe.dl.sourceforge.net/project/sevenzip/7-Zip/24.06/7z2406-x64.msi.
VERBOSE: Performing the operation "Download" on target
"https://altushost-swe.dl.sourceforge.net/project/sevenzip/7-Zip/24.06/7z2406-x64.msi".
VERBOSE: GET https://altushost-swe.dl.sourceforge.net/project/sevenzip/7-Zip/24.06/7z2406-x64.msi with 0-byte payload
VERBOSE: received -1-byte response of content type text/html; charset=utf-8
VERBOSE: Successfully downloaded:
C:\Temp\7z2406-x64.msi.


    Directory: C:\Temp


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        14-6-2024     13:28         112468 7z2406-x64.msi
VERBOSE: Complete.
VERBOSE: Performing the operation "Save-EvergreenApp" on target "Remove variables".
```

**Comment by aaronparker** [comment]
See #692  and #677

**Comment by Cyanic-Cloud** [comment]
Had the same issue, I had to edit the download uri slightly to Invoke-WebRequest -Uri $($DownloadURI + "?viasf=1")
I had to add an if statement.
If $DownloadURI -like "sourceforge.net do the above url edit.

Having visited the sourceforge.net using the new uri https://deac-riga.dl.sourceforge.net/project/sevenzip/7-Zip/24.06/7z2406-x64.msi it does a redirect to https://deac-riga.dl.sourceforge.net/project/sevenzip/7-Zip/24.06/7z2406-x64.msi?viasf=1 which then downloads the full file as normal.

This overall issue will affect all applications sourced from sourceforge.net as I had the same issue with WINSCP

Has anyone found a better a solution, if so please let me know

**Comment by aaronparker** [comment]
Closing duplicate. Use: https://github.com/aaronparker/evergreen/issues/677
