### ISSUE TITLE
Get-MozillaFirefox

### ISSUE THREAD

**Issue by haavarstein** [aaronparker/Evergreen#71]
Get-MozillaFirefox reports Version, Architecture, Language etc but cannot we use Get-MozillaFirefox -Architecture x64

Would also be nice, if possible to show ESR or Regular

**Comment by aaronparker** [comment]
`Get-MozillaFirefox` has `-Platform` that does the same thing as `-Architecture`.

**Comment by aaronparker** [comment]
ESR added in `2006.207`
