### ISSUE TITLE
[New app]: JGraph DrawIO Desktop

### ISSUE THREAD

**Issue by AScott-WWF** [aaronparker/evergreen#714]
### What is the new application?

Draw IO Desktop. (https://www.drawio.com/), as their releases are published on Github, I have created a Get-JGraphDrawIO.ps1 and JGraphDrawIO.json file to retrive the latest release for each supported architecture on Windows

Get-JGraphDrawIO.ps1:
```
Function Get-JGraphDrawIO {
    <#
        .SYNOPSIS
            Returns the latest JGraph DrawIO Desktop version number and download.

        .NOTES
            Author: Adrian Scott
    #>
    [OutputType([System.Management.Automation.PSObject])]
    [Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSUseSingularNouns", "", Justification="Product name is a plural")]
    [CmdletBinding(SupportsShouldProcess = $False)]
    param (
        [Parameter(Mandatory = $False, Position = 0)]
        [ValidateNotNull()]
        [System.Management.Automation.PSObject]
        $res = (Get-FunctionResource -AppName ("$($MyInvocation.MyCommand)".Split("-"))[1])
    )

    # Pass the repo releases API URL and return a formatted object
    $params = @{
        Uri          = $res.Get.Uri
        MatchVersion = $res.Get.MatchVersion
        Filter       = $res.Get.MatchFileTypes
    }
    $object = Get-GitHubRepoRelease @params
    Write-Output -InputObject $object
}

```

JGraphDrawIO.json:
```
{
	"Name": "JGraph DrawIO",
	"Source": "https://www.drawio.com/",
	"Get": {
		"Uri": "https://api.github.com/repos/jgraph/drawio-desktop/releases/latest",
		"MatchVersion": "(\\d+(\\.\\d+){1,4}).*",
		"MatchFileTypes": "\\.exe$|\\.msi$|\\.zip$"
	},
	"Install": {
		"Setup": "draw.io*.msi",
		"Preinstall": "",
		"Physical": {
			"Arguments": "/quiet /norestart",
			"PostInstall": [
			]
		},
		"Virtual": {
			"Arguments": "/quiet /norestart",
			"PostInstall": [
			]
		}
	}
}

```

### Vendor site

https://www.drawio.com/

### Does the vendor require a sign-in to download the app?

No

### Does the application include an updater?

Yes

### Have you reviewed the list of supported applications?

- [X] Supported apps at: https://stealthpuppy.com/evergreen/apps/

**Comment by aaronparker** [comment]
This app is already in Evergreen as `diagrams.net`. Should the current app be renamed?

**Comment by AScott-WWF** [comment]
Ah! I hadn't noticed that.
It appears that diagrams.net is not a name they appear to publicise on their site, they have links tothe online version (on diagrams.net), but the remaining urls (linked from the https://www.drawio.com/ homepage), redirect to JGraphs GitHub page.

Looking at their About Us page (https://www.drawio.com/about), IMHO I'd lean towards renaming the current app to rebrand it either "Draw.IO" or "JGraph Draw.IO"
