### ISSUE TITLE
[Bug]: Egnyte Old version

### ISSUE THREAD

**Issue by cfanta** [aaronparker/evergreen#729]
### What happened?

Egnyte Desktop App appears to be an old version
Showing 3.10.2.45 in evergreen
3.18.0 seems to be the latest version
https://egnyte-cdn.egnyte.com/egnytedrive/win/en-us/3.18.0/EgnyteDesktopApp_3.18.0_146.msi

Is there anyway to have this updated? or should it be removed from the supported list?

### Version

2312.878

### What PowerShell edition/s are you running Evergreen on?

Windows PowerShell

### Which operating system/s are you running Evergreen on?

Windows Server 2016+

### Have you reviewed the documentation?

- [ ] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [ ] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
N/a
```

**Comment by aaronparker** [comment]
The update source Evergreen is using is: `https://egnyte-cdn.egnyte.com/egnytedrive/win/en-us/subscribe`. The URL for the latest versions must have changed

**Comment by SpecterShell** [comment]
https://egnyte-cdn.egnyte.com/egnytedrive/win/en-us/versions/default.xml
