### ISSUE TITLE
Zoom Bug

### ISSUE THREAD

**Issue by xtian08** [aaronparker/Evergreen#73]
**Describe the bug**

Error:

Cannot index into a null array.
At C:\Users\xtian\Documents\WindowsPowerShell\Modules\evergreen\Public\Get-Zoom.ps1:34 char:9
+         $Url = [RegEx]::Match($redirectUrl, $res.Get.MatchUrl).Captur ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

**To Reproduce**
Run Get-Zoom

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, Windows Server 2019]
 - Module Version [e.g. 2004.126]

**Additional context**

**Comment by msfreaks** [comment]
Getting the same errors here. 2006.212
