### ISSUE TITLE
[New app]: PostgreSQL Global Development Group psqlodbc

### ISSUE THREAD

**Issue by bmitchell76** [aaronparker/evergreen#747]
### What is the new application?

PostgreSQL Global Development Group psqlodbc driver

### Vendor site

https://www.postgresql.org/ftp/odbc/releases/

### Does the vendor require a sign-in to download the app?

No

### Does the application include an updater?

No

### Have you reviewed the list of supported applications?

- [X] Supported apps at: https://stealthpuppy.com/evergreen/apps/

**Comment by aaronparker** [comment]
I can't find a source to use to query for updates

**Comment by AScott-WWF** [comment]
This looks like a task for Nevergreen...
@bmitchell76 if you use the Nevergreen PowerShell module, you could save the script I have just posted here (https://github.com/DanGough/Nevergreen/issues/121) into your .\Modules\Nevergreen\<version>\Apps\ folder as `Get-PostgreSQL.ps1` - until this script gets included into a future Nevergreen release.

**Comment by bmitchell76** [comment]
Thanks @AScott-WWF, I'll check it out.
