### ISSUE TITLE
Get-OpenJDK returns only debug version and only a zip

### ISSUE THREAD

**Issue by j81blog** [aaronparker/evergreen#76]
**Describe the bug**
Get-OpenJDK returns the debug build
https://github.com/ojdkbuild/ojdkbuild/releases/download/java-1.8.0-openjdk-debug-1.8.0.265-1.b01/java-1.8.0-openjdk-debug-1.8.0.265-1.b01.ojdkbuild.windows.x86_64.zip

**To Reproduce**
1. Run get-openjdk

**Expected behavior**
Would expect 2 results:
https://github.com/ojdkbuild/ojdkbuild/releases/download/java-1.8.0-openjdk-1.8.0.265-1.b01/java-1.8.0-openjdk-1.8.0.265-1.b01.ojdkbuild.windows.x86_64.zip
https://github.com/ojdkbuild/ojdkbuild/releases/download/java-1.8.0-openjdk-1.8.0.265-1.b01/java-1.8.0-openjdk-1.8.0.265-1.b01.ojdkbuild.windows.x86_64.msi

Eventually also the other versions like
https://github.com/ojdkbuild/ojdkbuild/releases/download/java-11-openjdk-11.0.8.10-1/java-11-openjdk-11.0.8.10-1.windows.ojdkbuild.x86_64.zip
https://github.com/ojdkbuild/ojdkbuild/releases/download/java-11-openjdk-11.0.8.10-1/java-11-openjdk-11.0.8.10-1.windows.ojdkbuild.x86_64.msi

etc.
**Screenshots**

```PowerShell
Version      : 1.8.0.265-1.b01
Platform     : Windows
Architecture : x64
Date         : 2020-08-31T18:50:56Z
Size         : 81832394
URI          : https://github.com/ojdkbuild/ojdkbuild/releases/download/java-1.8.0-openjdk-debug-1.8.0.265-1.b01/java-1
               .8.0-openjdk-debug-1.8.0.265-1.b01.ojdkbuild.windows.x86_64.zip

```

**Desktop (please complete the following information):**
 - OS: Windows 10 & Windows Server 2016
 - Module Version 2010.219

**Comment by j81blog** [comment]
Perhaps using the "https://api.github.com/repos/ojdkbuild/ojdkbuild/releases" url as base instead of the currently configured "https://api.github.com/repos/ojdkbuild/ojdkbuild/releases/latest" then there will be the possibliity to also show the msi and other builds

**Comment by aaronparker** [comment]
If I do this for OpenJDK, it will return 102 releases (right now) that will have to be filtered from output returned by `Get-OpenJDK`

**Comment by j81blog** [comment]
Maybe this helps you?

```PowerShell
$Packages = Invoke-RestMethod -Uri https://api.github.com/repos/ojdkbuild/ojdkbuild/releases
$regex = [regex]"java-(?'Edition'1\.8\.0|[0-9]*)-openjdk-(?'Debug'debug)?-?(?'Version'[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*)-(?'Release'[0-9]*)\.?b?(?'Build'[0-9]*)?-?(?'Architecture'x[0-9]{2})?"
$result = $Packages |  select tag_name | Select-String -Pattern $regex
$JavaReleases = $result.Matches | ForEach-Object { 
    if ([String]::IsNullOrEmpty($($_.Groups['Debug'].value))) {
        $name = $_.Groups[0].value
        $Version = [Version]($_.Groups['Version'].value)
        $Release = $(try { [convert]::ToInt32($_.Groups['Release'].value) } catch {-1} )
        $Build = $(try { [convert]::ToInt32($_.Groups['Build'].value) } catch {-1} )
        $Architecture = $(if ([String]::IsNullOrEmpty($($_.Groups['Architecture'].value))) {"x64"} else {"x86"})
        $Packages | Where-Object {$_.tag_name -eq $name} | Select-Object -ExpandProperty assets | ForEach-Object {
            if ($_.browser_download_url -like '*.zip' -or $_.browser_download_url -like '*.msi') {
                [PSCustomObject]@{
                    tag_name = $name
                    Version = $Version
                    Release = $Release
                    Build = $Build
                    Date = [datetime]$_.created_at
                    Architecture = $Architecture
                    URI = $_.browser_download_url
                }
            }
        }
    }
}| Sort-Object -Property {$_.Version},{$_.Build},{$_.Release} -Descending


#Java 1.8
$Items = $JavaReleases | Where-Object {$_.Version -like "1.8.0*" } | Select-Object Version, Architecture, URI
$LatestVersion = $Items.Version | Select-Object -Unique -First 1
$Items | Where-Object {$_.Version -eq $LatestVersion}

#Java 11 (also 13, 14 or 15)
$Items = $JavaReleases | Where-Object {$_.Version.Major -eq 11 } | Select-Object Version, Architecture, URI
$LatestVersion = $Items.Version | Select-Object -Unique -First 1
$Items | Where-Object {$_.Version -eq $LatestVersion}
```

**Comment by aaronparker** [comment]
Updated in `2012.225`. Additional filtering using the approach above will be added to a future update

**Comment by aaronparker** [comment]
See changes introduced in AdoptOpenJDK official builds for 8, 11, and 16 added in c8524ed81a2dbe6c5340f8f2896f4884ee642eba. These changes are in the currently released version.
