### ISSUE TITLE
Get-ShareX returns HTTP status 403

### ISSUE THREAD

**Issue by kaspersmjohansen** [aaronparker/Evergreen#77]
Get-ShareX returns HTTP status 403 when trying to download the non-portable edition of ShareX

Using this syntax should produce the error:
$Evergreen = Get-ShareX | Where-Object {$_.URI -notlike "*portable*"} | Sort-Object -Property Version -Descending | Select-Object -First 1
$URL = $Evergreen.uri

Start-BitsTransfer -Source $URL

Tested on Windows Server 2019
![EvergreenIssue](https://user-images.githubusercontent.com/37331486/96227083-d6020d80-0f93-11eb-932c-eb30e8621bac.jpg)

**Comment by aaronparker** [comment]
`Get-ShareX` is returning this right now [https://github.com/ShareX/ShareX/releases/download/v13.2.1/ShareX-13.2.1-setup.exe](https://github.com/ShareX/ShareX/releases/download/v13.2.1/ShareX-13.2.1-setup.exe). Download works OK for me.

**Comment by kaspersmjohansen** [comment]
Hi Aaron

You are correct. The Get-ShareX function works, it's the Start-BitsTransfer command that gives the error, I'll dig into why that happens. Thanks.

**Comment by aaronparker** [comment]
I use this primarily now over `Start-BitsTransfer`

```
$ProgressPreference = "SilentlyContinue"
Invoke-WebRequest -Uri $Uri -OutFile ...(etc.)
```
