### ISSUE TITLE
[Bug]: Citrix Workspace not returning latest

### ISSUE THREAD

**Issue by DanGough** [aaronparker/evergreen#772]
### What happened?

Looks like the feed you are using (https://downloadplugins.citrix.com/ReceiverUpdates/Prod/catalog_win.xml) is only returning 24.5.11.31, whereas the latest is 24.5.12.42.

https://www.citrix.com/downloads/workspace-app/windows/workspace-app-for-windows-latest.html

RSS feed: https://www.citrix.com/content/citrix/en_us/downloads/workspace-app.rss

Unfortunately there are no direct download links in the RSS and the URLs from the download page have an expiry time.

### Version

2411.1604

### What PowerShell edition/s are you running Evergreen on?

PowerShell Core

### Which operating system/s are you running Evergreen on?

Windows 10+

### Have you reviewed the documentation?

- [X] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [X] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
Get-EvergreenApp -Name 'CitrixWorkspaceApp' -Verbose

VERBOSE: Function path: C:\Users\DanGough\OneDrive - Patch My PC\Documents\PowerShell\Modules\Evergreen\2411.1604\Apps\Get-CitrixWorkspaceApp.ps1
VERBOSE: Function exists: C:\Users\DanGough\OneDrive - Patch My PC\Documents\PowerShell\Modules\Evergreen\2411.1604\Apps\Get-CitrixWorkspaceApp.ps1.
VERBOSE: Dot sourcing: C:\Users\DanGough\OneDrive - Patch My PC\Documents\PowerShell\Modules\Evergreen\2411.1604\Apps\Get-CitrixWorkspaceApp.ps1.
VERBOSE: Get-FunctionResource: read application resource strings from [C:\Users\DanGough\OneDrive - Patch My PC\Documents\PowerShell\Modules\Evergreen\2411.1604\Manifests\CitrixWorkspaceApp.json]
VERBOSE: Calling: Get-CitrixWorkspaceApp.
VERBOSE: Invoke-EvergreenRestMethod: Invoke-RestMethod parameter: UserAgent: CitrixReceiver/19.7.0.15 WinOS/10.0.18362.
VERBOSE: Invoke-EvergreenRestMethod: Invoke-RestMethod parameter: ContentType: application/json; charset=utf-8.
VERBOSE: Invoke-EvergreenRestMethod: Invoke-RestMethod parameter: Uri: https://downloadplugins.citrix.com/ReceiverUpdates/Prod/catalog_win.xml.
VERBOSE: Invoke-EvergreenRestMethod: Invoke-RestMethod parameter: UseBasicParsing: True.
VERBOSE: Invoke-EvergreenRestMethod: Invoke-RestMethod parameter: MaximumRedirection: 2.
VERBOSE: Invoke-EvergreenRestMethod: Invoke-RestMethod parameter: Method: Default.
VERBOSE: Invoke-EvergreenRestMethod: Invoke-RestMethod parameter: DisableKeepAlive: True.
VERBOSE: Requested HTTP/1.1 GET with 0-byte payload
VERBOSE: Received HTTP/1.1 response of content type text/xml of unknown size
VERBOSE: Content encoding: utf-8
VERBOSE: ConvertTo-DateTime: Converting: [2024-10-06].
VERBOSE: ConvertTo-DateTime: Attempting to convert date format to: en-GB.
VERBOSE: ConvertTo-DateTime: Returning date: [06/10/2024].
VERBOSE: ConvertTo-DateTime: Converting: [2024-10-04].
VERBOSE: ConvertTo-DateTime: Attempting to convert date format to: en-GB.
VERBOSE: ConvertTo-DateTime: Returning date: [04/10/2024].

Version : 24.5.11.31
Stream  : Current
Date    : 06/10/2024
Size    : 411087144
Hash    : 6ef90c5e3a45abe7eb28374c91ecce4dfe8ea61aadbae0149285027d833b1561
URI     : https://downloadplugins.citrix.com/ReceiverUpdates/Prod/Receiver/Win/CitrixWorkspaceApp24.5.11.31.exe

Version : 24.2.1001.2
Stream  : LTSR
Date    : 04/10/2024
Size    : 403830056
Hash    : 5dacd80b012223fb21ae30afcdf21e591b2038a1a79483b19a040e7639149976
URI     : https://downloadplugins.citrix.com/ReceiverUpdates/Prod/Receiver/Win/CitrixWorkspaceApp24.2.1001.2.exe
```

**Comment by aaronparker** [comment]
It's probably Citrix throttling updates. Typically this would show up with a version number of `0.0.0.0`; however, they may have changed their approach.

**Comment by aaronparker** [comment]
The feed URL is correct, it's Citrix throttling updates:

![image](https://github.com/user-attachments/assets/7338417f-45c6-4d7c-9d7e-ba88063fa652)

**Comment by oed-pelza** [comment]
Is the url really the current url? The url still response with 24.5.11.31 and a another new version 24.9.0.201 is already released...

**Comment by aaronparker** [comment]
Yes, see the known issues here: https://stealthpuppy.com/evergreen/issues/#out-of-date-update-feed

Add these existing issues on the same topic:
* https://github.com/aaronparker/evergreen/issues/578
* https://github.com/aaronparker/evergreen/issues/298
