### ISSUE TITLE
[Bug]: BitWarden Desktop won't install correcly

### ISSUE THREAD

**Issue by j81blog** [aaronparker/evergreen#776]
### What happened?

Download is correct only the install parameter is missing a parameter, needed for the latest version(s)
Currently only "/S" is used, "/allusers" must (now) also be added to install for all users.

[desktop-apps](https://bitwarden.com/help/configure-clients-selfhost/#desktop-apps)

### Version

2409.1419

### What PowerShell edition/s are you running Evergreen on?

Windows PowerShell

### Which operating system/s are you running Evergreen on?

Windows 10+

### Have you reviewed the documentation?

- [X] Troubleshooting at: https://stealthpuppy.com/evergreen/troubleshoot/
- [X] Known issues at: https://stealthpuppy.com/evergreen/issues/

### Verbose output

```shell
PS C:\> (Export-EvergreenManifest -Name BitwardenDesktop -Verbose).Install.Virtual
VERBOSE: Get-FunctionResource: read application resource strings from [C:\Users\John\OneDrive -
JOBICO\Documents\WindowsPowerShell\Modules\evergreen\2409.1419\Manifests\BitwardenDesktop.json]

Name                           Value
----                           -----
Arguments                      /S
PostInstall
```

**Comment by aaronparker** [comment]
Those install switches included in the manifest aren't really intended as a fully supported feature. I was looking at including those but that's not really what Evergreen is focused on. Create a script that includes the correct install switches and doesn't use those included in the manifest

**Comment by j81blog** [comment]
I already fixed it at my side in the script indeed, just wanted to pass the information.
