### ISSUE TITLE
Filezilla

### ISSUE THREAD

**Issue by fabekoma** [aaronparker/Evergreen#79]
Hi, thx for this amazing work, howerver i have a problem with Get-Filezilla, the URI returns https://dl4.cdn.filezilla-project.org/FileZilla_3.51.0_win64-setup.exe but this url is redirected by Filezilla themselves to https://filezilla-project.org/
Can you please have a look ?
Best regards.

**Comment by aaronparker** [comment]
FileZilla keep changing their update URL, I'll have to find the new one.

**Comment by aaronparker** [comment]
This is fixed in Evergreen `2010.219`.
