### ISSUE TITLE
SQL SSMS is reporting the wrong version

### ISSUE THREAD

**Issue by zoomwaffle** [aaronparker/Evergreen#82]
**Describe the bug**
SSMS shows the wrong version.

As of writing this, the current version is 15.0.18358.0, SSMS v18.7.1 and the evergreen code is showing an earlier version.

**To Reproduce**
PS C:\> Get-MicrosoftSsms

Version      Date                         Title                                  URI
-------      ----                         -----                                  ---
15.0.18330.0 2020-04-03T06:23:20.6085577Z Microsoft SQL Server Management Studio https://download.microsoft.com/download/2/d/1/2d12f6a1-e28f-42d1-9617-ac036857c5be/SSMS-Setup-ENU.exe

Compared to this:

https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver15

**Expected behavior**
It should return the correct/latest version.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows Server 2016
 - Module Version 2010.219

**Additional context**

**Comment by aaronparker** [comment]
This is the application's internal version returned by the SSMS updater API, so Evergreen can only deal with the data returned by that API. See #25

**Comment by aaronparker** [comment]
MS keeps changing where the SSMS update feed is, so this will need to be fixed.

**Comment by aaronparker** [comment]
Update to `Get-MicrosoftSsms` in 96687753bc75763ce5ecb31c3b3e0094c3c80ce6. The update feed doesn't return the latest version, so unfortunately there's little I can do. It's currently returning `15.0.18358.0`. 

`Get-MicrosoftSsms` has been updated with a better method of retrieving the update feed and returns additional languages (other than just English).

**Comment by aaronparker** [comment]
Added a note to the known issues: [https://stealthpuppy.com/Evergreen/knownissues.html](https://stealthpuppy.com/Evergreen/knownissues.html)
