### ISSUE TITLE
Firefox ESR MSI Support

### ISSUE THREAD

**Issue by zoomwaffle** [aaronparker/Evergreen#83]
**Is your feature request related to a problem? Please describe.**

Current ESR returned by Evergreen is the EXE only. 

**Describe the solution you'd like**

Return both EXE & MSI versions, and allow it to be filtered.

**Describe alternatives you've considered**
This ugly code to change EXE to MSI as the names are predictable!

$ff = Get-MozillaFirefox | where {$_.Architecture -eq "x64" -and $_.Version -match "esr"}
foreach ($x in $ff) {
  $x.uri = $x.uri.replace(".exe", ".msi")
}

**Additional context**

**Comment by aaronparker** [comment]
Updated in commit 51921d1a38765a0cdb3df3c0dec07efe58d8e79e

**Comment by aaronparker** [comment]
Added to `2012.225`
