### ISSUE TITLE
Italian language in AdobeAcrobatReaderDC.json

### ISSUE THREAD

**Issue by nafusu** [aaronparker/Evergreen#84]
Fantastic project! I want to implement it in my work routine but the lack of the Italian language prevents me from having the updated script. 
Please add Italian
`"Italian",` in to AdobeAcrobatReaderDC.json

thx

**Comment by j81blog** [comment]
Why not use the MUI version?

**Comment by aaronparker** [comment]
I've added Italian and a few other languages to the development branch; however, these don't return the latest version of Reader DC, so @j81blog 's approach to use the MUI language pack might be better

**Comment by aaronparker** [comment]
Added to `2012.225`
