### ISSUE TITLE
Get-MozillaFirefox changed "Platform" to "Architecture" and only returns en-US

### ISSUE THREAD

**Issue by xenadmin** [aaronparker/Evergreen#88]
**Describe the bug**
Get-MozillaFirefox changed "Platform" to "Architecture" and only returns en-US

**To Reproduce**
1. Update-Module -Name Evergreen -Force to latest version
2. Get-MozillaFirefox
3. Results are all en-US
4. Instead of Platform you now have to filter for Architecture

**Expected behavior**
No changes in wording, although I can fix this.
But I need a de-DE Client, like before. 

**Screenshots**
![grafik](https://user-images.githubusercontent.com/12057348/101611490-df46ae00-3a09-11eb-889b-5e3d7666962c.png)

**Desktop (please complete the following information):**
 - OS: [Windows Server 2016]
 - Module Version

```
PS U:\> Get-Module Evergreen

ModuleType Version    Name
---------- -------    ----
Script     2012.225   Evergreen
```

**Additional context**
-

**Comment by aaronparker** [comment]
I should have listed this in the changelog - I've removed `-Architecture` - filter the output for `Architecture` instead. The `-Language` parameter still exists - specify the language you need.

**Comment by xenadmin** [comment]
Ok, gotcha. Works now. 

Old:
`Get-MozillaFirefox -Platform win64 -Language de | Where-Object -Property Version -NotLike "*esr*"`

New:
`Get-MozillaFirefox -Language de | Where-Object { $_.Architecture -Like "x64" -and $_.Channel -like "LATEST_FIREFOX_VERSION" -and $_.Type -like "exe" }`

I confused myself, that `de` only appears, if I add it. My fault. 
I will push the updated line to my Git scripts repo, then it will fix itself.

**Comment by aaronparker** [comment]
I'll fix the changelog.
