### ISSUE TITLE
2012.225 Firefox ESR is giving the wrong files

### ISSUE THREAD

**Issue by zoomwaffle** [aaronparker/Evergreen#91]
**Describe the bug**

Getting the ESR release of Firefox shows the non-ESR version to me

**To Reproduce**

PS C:\> Get-MozillaFirefox | where {$_.Architecture -eq "x64" -and $_.Channel -eq "FIREFOX_ESR" -and $_.type -eq "msi" }
 
 
Version      : 78.5.0esr
Architecture : x64
Channel      : FIREFOX_ESR
Language     : en-US
Type         : msi
Filename     : Firefox Setup 83.0.msi
URI          : https://download-installer.cdn.mozilla.net/pub/firefox/releases/83.0/win64/en-US/Firefox%20Setup%2083.0.msi

**Expected behavior**

Return the ESR version.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows Server 2016
 - Module Version: 2012.225

**Comment by aaronparker** [comment]
Fixed in ff6e2fdb7e6fff9b49083a5ad46b8a442490a495
