### ISSUE TITLE
PowerBI Desktop evergreen option in SoftwareUpdater script?

### ISSUE THREAD

**Issue by andygresbach** [aaronparker/evergreen#92]
**Is your feature request related to a problem? Please describe.**
We are trying to find an efficient way to update PowerBI desktop in our environment via Evergreen if possible

**Describe the solution you'd like**
We have been working with the Software Updater script that yourself and Morpheus78 (and others i'm sure) have collaborated on which works fantastic.  We are hoping it is possible to add PowerBI Desktop to the options here to help update/deploy to desktops that have that application as well

**Describe alternatives you've considered**
We have somewhat been able to do this w/ chocolatey however it requires removing the traditional install first and letting it install via that method.   We also are able to use a PDQ Deploy script to first silently uninstall old version then install the new (requires a manual download of each new version however).  

**Additional context**
The best that I can find PowerBI uses this URL to download the latest version if it helps:  https://www.microsoft.com/en-us/download/confirmation.aspx?id=58494

**Comment by aaronparker** [comment]
The challenge I have with Power BI is finding the URL/API etc. that it uses to find new versions of itself. So far I've not found it.

With Evergreen we want to avoid screen scraping to reduce the chance of errors and pages changing etc.

**Comment by aaronparker** [comment]
This is as close as I've found so far, but it's not suitable: [https://download.microsoft.com/download/9/B/A/9BAEFFEF-1A68-4102-8CDF-5D28BFFE6A61/PBIDesignerConfig.json](https://download.microsoft.com/download/9/B/A/9BAEFFEF-1A68-4102-8CDF-5D28BFFE6A61/PBIDesignerConfig.json)

**Comment by andygresbach** [comment]
that does make sense.  thank you for trying either way!

**Comment by DanGough** [comment]
If you would accept a dirty web scraper into Evergreen, here is the custom script I have been using:

https://gist.github.com/DanGough/5756295e4d70fcc009f63e2b5da1d2b3

**Comment by DanGough** [comment]
PowerBI Desktop is available in [Nevergreen](https://github.com/DanGough/Nevergreen) until a suitable feed is found.
