### ISSUE TITLE
SumatraPDF

### ISSUE THREAD

**Issue by haavarstein** [aaronparker/Evergreen#98]
API Update Check from Application : https://www.sumatrapdfreader.org/update-check-rel.txt

Download URI : 

x64 : https://www.sumatrapdfreader.org/dl2/SumatraPDF-3.2-64-install.exe
x32 : https://www.sumatrapdfreader.org/dl2/SumatraPDF-3.2-install.exe

Silent Install (default goes to AppData)

SumatraPDF-64-install.exe -d "C:\Program Files\SumatraPDF" -s

**Comment by msfreaks** [comment]
Version info can also be found here: https://github.com/sumatrapdfreader/sumatrapdf

**Comment by haavarstein** [comment]
Yes, problem is that the repo doesn't provide any sources

Get-GitHubRelease -uri https://api.github.com/repos/sumatrapdfreader/sumatrapdf/releases/latest

WARNING: Get-GitHubRelease: Failed to return a usable object from the repo.

**Comment by aaronparker** [comment]
Added in 9d50a8d3fb9c47ee3a70bb0554c1128e972dd8c4
